import type { AccountingParityCapture } from './accounting-parity-definitions';

export const accountingParitySource3 = [
  {
    route: 'general-ledger/reports/aging',
    title: 'تجزیه سنی',
    sourcePath: 'مالی / دفتر کل / گزارش ها / تجزیه سنی',
    sourcePage: 'Financial/Reports/AgingOfReceivablesPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsToFiscalYear_Input',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherType_Input',
      },
      {
        label: 'ویژگی',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpReportFeature_ComboBox_Input',
      },
      {
        label: 'نمایش حساب های با ماهیت مهم نیست',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkNoneNatureSL',
      },
      {
        label: 'ازماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFromMonth_Input',
      },
      {
        label: 'تا ماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboToMonth_Input',
      },
      {
        label: 'نوع گزارش',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpReportType_ComboBox_Input',
      },
      {
        label: 'درصد مانده از ابتدا',
        type: 'text',
        disabled: false,
        sourceControlId: 'numPercent',
      },
    ],
    columns: [
      'شناسه',
      'کد',
      'عنوان',
      'عنوان 1',
      'عنوان به زبان دوم',
      'از تاریخ',
      'تا تاریخ',
      'درصد',
      'نام ماه',
      'عنوان دوره',
      'کد معین',
      'عنوان معین',
      'عنوان سطح4',
      'عنوان سطح5',
      'عنوان سطح6',
      'بدهکار',
      'بستانکار تطبیق نشده',
      'هزینه مطالبات مشکوک الوصول',
      'کاربر جاری',
      'دفتر کل',
      'شناسه معین',
      'شناسه شعبه',
      'کد سطح 4',
      'کد سطح 5',
      'کد سطح6',
      'کد سطح7',
      'کد سطح 8',
      'کد سطح 9',
      'تاریخ شروع',
      'تاریخ پایان',
      'ارز',
    ],
    actions: [
      'گزارش',
      'چاپ گزارش',
      'راهنما (Ctrl+H)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'برای مرتب سازی اینجا کلیک کنید',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'جدید',
      'حذف',
      'بارگذاری مجدد',
      'ارسال به Excel',
      'عدم نمایش فیلتر',
      'انتخاب یک رکوردی',
      'ستونها',
      'شناسه',
      'کد',
      'عنوان',
      'عنوان 1',
      'عنوان به زبان دوم',
      'دریافت از Excel',
      'چاپ',
      'مدیریت فرم های چاپی ...',
      'افزودن (Insert)',
      'حذف (Delete)',
      'جستجو (Ctrl+F)',
      'عنوان دوره',
      'کد معین',
      'عنوان معین',
      'عنوان سطح4',
      'عنوان سطح5',
      'عنوان سطح6',
      'عنوان سطح7',
      'عنوان سطح8',
      'عنوان سطح9',
      'بدهکار',
      'بستانکار تطبیق نشده',
      'درصد',
      'هزینه مطالبات مشکوک الوصول',
      'کاربر جاری',
      'دفتر کل',
      'شناسه معین',
      'شناسه شعبه',
      'کد سطح 4',
      'کد سطح 5',
      'کد سطح6',
      'کد سطح7',
      'کد سطح 8',
      'کد سطح 9',
      'تاریخ شروع',
      'تاریخ پایان',
      'ارز',
      'نمایش جزییات اقلام بستانکار تطبیق نشده',
    ],
    stage: 'تجزیه سنی',
  },
  {
    route: 'general-ledger/reports/journal-browser',
    title: 'مرور اسناد',
    sourcePath: 'مالی / دفتر کل / گزارش ها / مرور اسناد',
    sourcePage: 'Financial/Reports/VoucherDetailPages/VoucherDetails.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsToFiscalYear_Input',
      },
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkFromDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkToDate_MaskedTextBox',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherType_Input',
      },
      {
        label: 'تعدیل حساب های بودجه ای هزینه ای',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i0_chkTitleVoucherType',
      },
      {
        label: 'تعدیل حساب های بودجه ای سرمایه ای',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i1_chkTitleVoucherType',
      },
      {
        label: 'سند حسابداری اعلامیه بدهکار/بستانکار',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i2_chkTitleVoucherType',
      },
      {
        label: 'عمومی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i3_chkTitleVoucherType',
      },
      {
        label: 'بستن حساب ها',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i4_chkTitleVoucherType',
      },
      {
        label: 'افتتاحیه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i5_chkTitleVoucherType',
      },
      {
        label: 'اختتامیه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i6_chkTitleVoucherType',
      },
      {
        label: 'تعدیل ماهیت ابتدای دوره',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i7_chkTitleVoucherType',
      },
      {
        label: 'تعدیل ماهیت انتهای دوره',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i8_chkTitleVoucherType',
      },
      {
        label: 'تسعیر ارز',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i9_chkTitleVoucherType',
      },
      {
        label: 'دریافت و پرداخت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i10_chkTitleVoucherType',
      },
      {
        label: 'انبار',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i11_chkTitleVoucherType',
      },
      {
        label: 'خرید',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i12_chkTitleVoucherType',
      },
      {
        label: 'دارایی ثابت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i13_chkTitleVoucherType',
      },
      {
        label: 'پورسانت فروش',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i14_chkTitleVoucherType',
      },
      {
        label: 'سند فروش',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i15_chkTitleVoucherType',
      },
      {
        label: 'سند برگشت از فروش',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i16_chkTitleVoucherType',
      },
      {
        label: 'سند حسابداری اعلامیه فروش',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i17_chkTitleVoucherType',
      },
      {
        label: 'سند حسابداری فروش خرده فروشی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i18_chkTitleVoucherType',
      },
      {
        label: 'سند حسابداری برگشت از فروش خرده فروشی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i19_chkTitleVoucherType',
      },
      {
        label: 'سند حسابداری برگشت امانی ظرف',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i20_chkTitleVoucherType',
      },
      {
        label: 'سند حسابداری تحویل امانی ظرف',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i21_chkTitleVoucherType',
      },
      {
        label: 'جبران خدمات',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i22_chkTitleVoucherType',
      },
      {
        label: 'بهای تمام شده',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i23_chkTitleVoucherType',
      },
      {
        label: 'وضعیت سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherState_Input',
      },
      {
        label: 'موقت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherState_i0_chkTitleVoucherState',
      },
      {
        label: 'یادداشت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherState_i1_chkTitleVoucherState',
      },
      {
        label: 'در حال بررسی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherState_i2_chkTitleVoucherState',
      },
      {
        label: 'بررسی شده',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherState_i3_chkTitleVoucherState',
      },
      {
        label: 'قطعی شده',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherState_i4_chkTitleVoucherState',
      },
    ],
    columns: [
      'شناسه',
      'کلید سطر',
      'نام کاربر',
      'شناسه کاربر',
      'تعداد اسناد صادر شده',
      'تعداد ردیف های اسناد صادر شده',
      'تعداد اسناد تغییر یافته',
      'تعداد ردیف های اسناد تغییر یافته',
      'تعداد اسناد بررسی شده',
    ],
    actions: [
      'فیلتر مجدد',
      'مشاهده اسناد',
      'صادر شده',
      'تغییر یافته',
      'بررسی شده',
      'چاپ',
      'راهنما (Ctrl+H)',
      'کاربر',
      'نوع سند',
      'وضعیت',
      'روزانه',
      'ماهیانه',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'برای مرتب سازی اینجا کلیک کنید',
      'ارسال به Excel',
      'عدم نمایش فیلتر( Ctrl+F)',
      'ستونها',
      'شناسه',
      'کلید سطر',
      'نام کاربر',
      'شناسه کاربر',
      'تعداد اسناد صادر شده',
      'تعداد ردیف های اسناد صادر شده',
      'تعداد اسناد تغییر یافته',
      'تعداد ردیف های اسناد تغییر یافته',
      'تعداد اسناد بررسی شده',
      'محاسبه تعداد رکوردها و صفحات فهرست( Ctrl+K)',
      'دریافت از Excel',
      'مدیریت فرم های چاپی ...',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'عدم نمایش فیلتر',
    ],
    stage: 'مرور اسناد',
  },
  {
    route: 'general-ledger/reports/nature-conflict-range',
    title: 'حساب های خلاف ماهیت طی دوره',
    sourcePath: 'مالی / دفتر کل / گزارش ها /  خلاف ماهیت طی دوره',
    sourcePage:
      'Financial/Reports/PeriodicOppositNatureAccountPages/PeriodicOppositNatureSLs.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsToFiscalYear_Input',
      },
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkFromDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkToDate_MaskedTextBox',
      },
      {
        label: 'ویژگی',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpAccountSpecification_ComboBox_Input',
      },
      {
        label: 'ارز',
        type: 'text',
        disabled: true,
        sourceControlId: 'cboCurrency_Input',
      },
      {
        label: 'روزانه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkDaily',
      },
    ],
    columns: [
      'شناسه',
      'کد',
      'عنوان',
      'عنوان 1',
      'عنوان به زبان دوم',
      'شناسه معین',
      'کد سطح4',
      'کد سطح 5',
      'کد سطح6',
      'شناسه شعبه',
      'کد معین',
      'عنوان معین',
      'سطح 4',
      'سطح 5',
      'سطح 6',
      'ماهیت حساب',
      'مانده حساب',
      'شناسه ارز',
      'شناسه سند',
    ],
    actions: [
      'اجرا',
      'چاپ',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'اجرای فیلتر',
      'نمایش بدون فیلتر',
      'حذف همه شرطها',
      'بارگذاری',
      'حذف از لیست',
      'ذخیره فیلتر',
      'برای مرتب سازی اینجا کلیک کنید',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'جدید',
      'حذف',
      'بارگذاری مجدد',
      'ارسال به Excel',
      'عدم نمایش فیلتر',
      'انتخاب یک رکوردی',
      'ستونها',
      'شناسه',
      'کد',
      'عنوان',
      'عنوان 1',
      'عنوان به زبان دوم',
      'دریافت از Excel',
      'مدیریت فرم های چاپی ...',
      'شناسه معین',
      'کد سطح4',
      'کد سطح 5',
      'کد سطح6',
      'کد سطح7',
      'کد سطح 8',
      'کد سطح 9',
      'کد سطح10',
      'کد سطح11',
      'کد سطح12',
      'کد سطح13',
      'کد سطح14',
      'کد سطح15',
      'کد سطح16',
      'کد سطح17',
      'کد سطح18',
      'کد سطح19',
      'کد سطح20',
      'شناسه شعبه',
      'کد معین',
      'عنوان معین',
      'سطح 4',
      'سطح 5',
      'سطح 6',
      'سطح 7',
      'سطح 8',
      'سطح 9',
      'سطح 10',
      'سطح 11',
      'سطح 12',
      'سطح 13',
      'سطح 14',
      'سطح 15',
      'سطح 16',
      'سطح 17',
      'سطح 18',
      'سطح 19',
      'سطح 20',
      'تاریخ',
      'Labels_EndDate',
      'ماهیت حساب',
      'مانده حساب',
      'شناسه ارز',
      'عنوان ارز مبنا',
      'شناسه سند',
      'نمایش جزییات اقلام خلاف ماهیت شده',
    ],
    stage: 'حساب های خلاف ماهیت طی دوره',
  },
  {
    route: 'general-ledger/reports/analysis',
    title: 'آنالیز',
    sourcePath: 'مالی / دفتر کل / گزارش ها / آنالیز',
    sourcePage: 'Financial/Analysis/AnalysePages/Analyse.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsToFiscalYear_Input',
      },
      {
        label: 'وضعیت سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherState_Input',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherType_Input',
      },
      {
        label: 'نوع تفصیلی',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboDLType_Input',
      },
      {
        label: 'فیلتر',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFilter_Input',
      },
      {
        label: 'از ماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFromMonth_Input',
      },
      {
        label: 'تا ماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboToMonth_Input',
      },
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkFromDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkToDate_MaskedTextBox',
      },
      {
        label: 'نوع حساب',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboType_Input',
      },
      {
        label: 'نوع آنالیز',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpAnalyseType_ComboBox_Input',
      },
      {
        label: 'ویژگی',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpAccountSpecification_ComboBox_Input',
      },
      {
        label: 'ارز',
        type: 'text',
        disabled: true,
        sourceControlId: 'sltCurrency_Input',
      },
      {
        label: 'معین',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltSLSelector_Input',
      },
      {
        label: 'حساب تفصیلی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltDL_Input',
      },
      {
        label: 'اقلام تطبیق نشده',
        type: 'text',
        disabled: false,
        sourceControlId: 'rdoMisMatchedItem',
      },
      {
        label: 'اقلام تطبیق شده',
        type: 'text',
        disabled: false,
        sourceControlId: 'rdoMatchedItem',
      },
      {
        label: 'همه اقلام',
        type: 'text',
        disabled: false,
        sourceControlId: 'rdoAllItems',
      },
      {
        label: 'تفصیلی سطح 4',
        type: 'text',
        disabled: true,
        sourceControlId: 'sltDLLevel4_Input',
      },
      {
        label: 'تفصیلی سطح 5',
        type: 'text',
        disabled: true,
        sourceControlId: 'sltDLLevel5_Input',
      },
      {
        label: 'تفصیلی سطح6',
        type: 'text',
        disabled: true,
        sourceControlId: 'sltDLLevel6_Input',
      },
      {
        label: 'سطح تفصیلی',
        type: 'text',
        disabled: true,
        sourceControlId: 'lkpdlLevel_ComboBox_Input',
      },
      {
        label: 'بدهکار کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'decTotalDebit_input',
      },
      {
        label: 'بدهکار تطبیق نشده کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'decTotalMisMatchDebit_input',
      },
      {
        label: 'بدهکار تطبیق شده کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'decTotalDebitMatchableValue_input',
      },
      {
        label: 'بستانکار کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'decTotalCredit_input',
      },
      {
        label: 'بستانکار تطبیق نشده کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'decTotalMisMatchCredit_input',
      },
      {
        label: 'بستانکار تطبیق شده کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'decTotalCreditMatchableValue_input',
      },
    ],
    columns: [
      'شناسه',
      'تطبیق شده',
      'شعبه',
      'شماره عطف',
      'تاریخ سند',
      'شرح',
      'بدهکار کل',
      'بستانکار کل',
      'بدهکار تطبیق نشده',
      'بستانکار تطبیق نشده',
      'بدهکار تطبیق شده',
      'بستانکار تطبیق شده',
      'شماره پیگیری',
      'تاریخ پیگیری',
      'شماره ردیف',
      'شماره سند',
      'عنوان ارز',
      'مبلغ ارز',
      'مقادیر بدهکار قابل تطبیق',
      'مقادیر بستانکار قابل تطبیق',
    ],
    actions: [
      'اجرا',
      'تطبیق',
      'تسهیم اقلام تطبیقی',
      'ریز تطبیق',
      'اتوماتیک',
      'تساوی مبلغ، شماره پیگیری و تاریخ پیگیری',
      'تساوی مبلغ و شماره پیگیری',
      'تساوی مبلغ و تاریخ پیگیری',
      'تساوی مبلغ',
      'تساوی شماره پیگیری',
      'تساوی نوع ارز و مبلغ ارز',
      'مشاهده سند',
      'چاپ',
      'حذف',
      'راهنما (Ctrl+H)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'برای مرتب سازی اینجا کلیک کنید',
      'بارگذاری مجدد( Ctrl+R)',
      'ارسال به Excel',
      'عدم نمایش فیلتر( Ctrl+F)',
      'انتخاب یک رکوردی( Ctrl+M)',
      'ستونها',
      'شناسه',
      'تطبیق شده',
      'شعبه',
      'شماره عطف',
      'تاریخ سند',
      'شرح',
      'بدهکار کل',
      'بستانکار کل',
      'بدهکار تطبیق نشده',
      'بستانکار تطبیق نشده',
      'بدهکار تطبیق شده',
      'بستانکار تطبیق شده',
      'شماره پیگیری',
      'تاریخ پیگیری',
      'شماره ردیف',
      'شماره سند',
      'عنوان ارز',
      'مبلغ ارز',
      'محاسبه تعداد رکوردها و صفحات فهرست( Ctrl+K)',
      'مدیریت فرم های چاپی ...',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'بارگذاری مجدد',
      'عدم نمایش فیلتر',
      'انتخاب یک رکوردی',
    ],
    stage: 'آنالیز',
  },
  {
    route: 'general-ledger/reports/journal-lines',
    title: 'اقلام سند',
    sourcePath: 'مالی / دفتر کل / گزارش ها /  اقلام سند',
    sourcePage: 'Financial/Reports/JournalVoucherDetailPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsToFiscalYear_Input',
      },
      {
        label: 'ویژگی',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpAccountSpecification_ComboBox_Input',
      },
      {
        label: 'مبلغ به ارز عملیاتی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkOperational',
      },
      {
        label: 'مبلغ به ارز',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkCurrency',
      },
      {
        label: 'فیلتر',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFilter_Input',
      },
      {
        label: 'از ماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFromMonth_Input',
      },
      {
        label: 'تا ماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboToMonth_Input',
      },
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkFromDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkToDate_MaskedTextBox',
      },
      {
        label: 'از سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtFromNumber',
      },
      {
        label: 'تا سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtToNumber',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherType_Input',
      },
      {
        label: 'وضعیت سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherState_Input',
      },
      {
        label: 'نوع حساب',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpAccount_ComboBox_Input',
      },
      {
        label: 'خلاصه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkAbstract',
      },
      {
        label: 'فیلتر سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpDescriptionFilterType_ComboBox_Input',
      },
      {
        label: 'شرح سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDescription',
      },
    ],
    columns: [],
    actions: [
      'مشاهده گزارش',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'اجرای گزارش',
      'بازگشت به گزارش پدر',
      'صفحه اول',
      'صفحه قبلی',
      'صفحه بعد',
      'صفحه آخر',
      'ارسال',
      'XML',
      'CSV',
      'PDF',
      'MHTML',
      'IMAGE',
      'WORD',
      'EXCEL',
      'داده ها به Excel',
      'چاپ',
      'پیش نمایش چاپ',
      'Cancel',
    ],
    stage: 'اقلام سند',
  },
  {
    route: 'general-ledger/reports/main-subledger-comparison',
    title: 'خطا',
    sourcePath: 'مالی / دفتر کل / گزارش ها /  مقایسه دفتر کل اصلی و فرعی',
    sourcePage:
      'Financial/Reports/ComparisionReportBetweenLedgersPages/Edit.aspx',
    evidenceStatus: 'source-error',
    fields: [],
    columns: [],
    actions: ['مشاهده اطلاعات بیشتر'],
    stage: 'خطا',
  },
  {
    route: 'general-ledger/reports/comprehensive',
    title: 'گزارش جامع',
    sourcePath: 'مالی / دفتر کل / گزارش ها / گزارش جامع',
    sourcePage: 'Financial/Reports/ComprehensivePages/ComprehensiveView.view',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltToFiscalYear_Input',
      },
      {
        label: 'نوع مانده',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpBalanceType_ComboBox_Input',
      },
      {
        label: 'فیلتر بر اساس',
        type: 'text',
        disabled: false,
        sourceControlId: 'cmbFilterBy_Input',
      },
      {
        label: 'از ماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cmbFromMonth_Input',
      },
      {
        label: 'تا ماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cmbToMonth_Input',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cmbVoucherType_Input',
      },
      {
        label: 'ویژگی',
        type: 'text',
        disabled: false,
        sourceControlId: 'cmbAccountSpecification_Input',
      },
      {
        label: 'مبنای ارز',
        type: 'text',
        disabled: false,
        sourceControlId: 'cmbCurrencyBase_Input',
      },
      {
        label: 'دارای گردش در تمام اولویت های انتخابی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkHasTurnOverInAllAccountPriorities',
      },
      {
        label: 'نمایش مبالغ ریالی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkShowOperationalCurrencyAmount',
      },
      {
        label: 'نمایش مبالغ ارزی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkShowCurrencyAmounts',
      },
      {
        label: 'بررسی کننده',
        type: 'text',
        disabled: false,
        sourceControlId: 'cmbReviewer_Input',
      },
      {
        label: 'نوع مانده ارزی',
        type: 'text',
        disabled: true,
        sourceControlId: 'lkpCurrencyRemainingType_ComboBox_Input',
      },
      {
        label: 'از مانده بدهکار',
        type: 'text',
        disabled: false,
        sourceControlId: 'decFromDebitRemaining_input',
      },
      {
        label: 'تا مانده بدهکار',
        type: 'text',
        disabled: false,
        sourceControlId: 'decToDebitRemaining_input',
      },
      {
        label: 'از مانده بستانکار',
        type: 'text',
        disabled: false,
        sourceControlId: 'decFromCreditRemaining_input',
      },
      {
        label: 'تا مانده بستانکار',
        type: 'text',
        disabled: false,
        sourceControlId: 'decToCreditRemaining_input',
      },
      {
        label: 'ساختار گزارش',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpReportStructure_ComboBox_Input',
      },
      {
        label: 'نمایش کد حساب تفصیل',
        type: 'text',
        disabled: false,
        sourceControlId: 'cmbCodeOption_Input',
      },
      {
        label: 'خروجی چاپ',
        type: 'text',
        disabled: false,
        sourceControlId: 'cmbPrintType_Input',
      },
      {
        label: 'چاپ حساب ها در صفحات مجزا',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkPrintInSeperatePage',
      },
      {
        label: 'افتتاحیه در ستون مجزا',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkIsOpeningInSeperatly',
      },
      {
        label: 'احتساب گردش از سال گذشته',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkConsiderLastYearTurnOver',
      },
      {
        label: 'نمایش نوع اسناد پایان سال انتخاب شده',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkShowYearEndVoucherTypes',
      },
      {
        label: 'فیلتر',
        type: 'text',
        disabled: false,
        sourceControlId: 'filter4_cmbSLFilterType_Input',
      },
      {
        label: 'نوع تفصیلی',
        type: 'text',
        disabled: false,
        sourceControlId: 'filter4_cmbLevelType_Input',
      },
    ],
    columns: ['عنوان', 'اولویت', 'شناسه', 'کد', 'عنوان 1', 'عنوان به زبان دوم'],
    actions: [
      'اجرای گزارش',
      'سطح تفصیلی',
      'نوع تفصیلی',
      'تراز',
      'دفاتر',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'اجرای فیلتر',
      'نمایش بدون فیلتر',
      'حذف همه شرطها',
      'بارگذاری',
      'حذف از لیست',
      'ذخیره فیلتر',
      'اضافه',
      'حذف',
      'بالا',
      'پایین',
      'حساب معین',
      'برای مرتب سازی اینجا کلیک کنید',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'جدید',
      'بارگذاری مجدد',
      'ارسال به Excel',
      'عدم نمایش فیلتر',
      'انتخاب یک رکوردی',
      'ستونها',
      'شناسه',
      'کد',
      'عنوان',
      'عنوان 1',
      'عنوان به زبان دوم',
      'دریافت از Excel',
      'چاپ',
      'مدیریت فرم های چاپی ...',
    ],
    stage: 'گزارش جامع',
  },
  {
    route: 'general-ledger/reports/matrix',
    title: 'گزارش ماتریسی',
    sourcePath: 'مالی / دفتر کل / گزارش ها / ماتریسی',
    sourcePage: 'Financial/Reports/MatrixPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsToFiscalYear_Input',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherType_Input',
      },
      {
        label: 'تعدیل حساب های بودجه ای هزینه ای',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i0_chkTitleVoucherType',
      },
      {
        label: 'تعدیل حساب های بودجه ای سرمایه ای',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i1_chkTitleVoucherType',
      },
      {
        label: 'سند حسابداری اعلامیه بدهکار/بستانکار',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i2_chkTitleVoucherType',
      },
      {
        label: 'عمومی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i3_chkTitleVoucherType',
      },
      {
        label: 'بستن حساب ها',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i4_chkTitleVoucherType',
      },
      {
        label: 'افتتاحیه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i5_chkTitleVoucherType',
      },
      {
        label: 'اختتامیه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i6_chkTitleVoucherType',
      },
      {
        label: 'تعدیل ماهیت ابتدای دوره',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i7_chkTitleVoucherType',
      },
      {
        label: 'تعدیل ماهیت انتهای دوره',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i8_chkTitleVoucherType',
      },
      {
        label: 'تسعیر ارز',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i9_chkTitleVoucherType',
      },
      {
        label: 'دریافت و پرداخت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i10_chkTitleVoucherType',
      },
      {
        label: 'انبار',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i11_chkTitleVoucherType',
      },
      {
        label: 'خرید',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i12_chkTitleVoucherType',
      },
      {
        label: 'دارایی ثابت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i13_chkTitleVoucherType',
      },
      {
        label: 'پورسانت فروش',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i14_chkTitleVoucherType',
      },
      {
        label: 'سند فروش',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i15_chkTitleVoucherType',
      },
      {
        label: 'سند برگشت از فروش',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i16_chkTitleVoucherType',
      },
      {
        label: 'سند حسابداری اعلامیه فروش',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i17_chkTitleVoucherType',
      },
      {
        label: 'سند حسابداری فروش خرده فروشی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i18_chkTitleVoucherType',
      },
      {
        label: 'سند حسابداری برگشت از فروش خرده فروشی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i19_chkTitleVoucherType',
      },
      {
        label: 'سند حسابداری برگشت امانی ظرف',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i20_chkTitleVoucherType',
      },
      {
        label: 'سند حسابداری تحویل امانی ظرف',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i21_chkTitleVoucherType',
      },
      {
        label: 'جبران خدمات',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i22_chkTitleVoucherType',
      },
      {
        label: 'بهای تمام شده',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboVoucherType_i23_chkTitleVoucherType',
      },
      {
        label: 'فیلتر',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFilter_Input',
      },
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkFromDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkToDate_MaskedTextBox',
      },
      {
        label: 'از سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtFromNumber',
      },
      {
        label: 'تا سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtToNumber',
      },
      {
        label: 'سطر',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboRow_Input',
      },
      {
        label: 'نوع تفصیلی',
        type: 'text',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_Input',
      },
      {
        label: 'شخص',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i0_chkTitleDLTypeRow',
      },
      {
        label: 'شرکت',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i1_chkTitleDLTypeRow',
      },
      {
        label: 'شعبه',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i2_chkTitleDLTypeRow',
      },
      {
        label: 'مرکز هزینه',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i3_chkTitleDLTypeRow',
      },
      {
        label: 'پروژه',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i4_chkTitleDLTypeRow',
      },
      {
        label: 'منبع تامین اعتبار',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i5_chkTitleDLTypeRow',
      },
      {
        label: 'دوره مالی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i6_chkTitleDLTypeRow',
      },
      {
        label: 'کد',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i7_chkTitleDLTypeRow',
      },
      {
        label: 'طبقه خدمت',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i8_chkTitleDLTypeRow',
      },
      {
        label: 'حساب بانکی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i9_chkTitleDLTypeRow',
      },
      {
        label: 'صندوق',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i10_chkTitleDLTypeRow',
      },
      {
        label: 'تنخواه',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i11_chkTitleDLTypeRow',
      },
      {
        label: 'تسهیلات مالی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i12_chkTitleDLTypeRow',
      },
      {
        label: 'سفارشات',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i13_chkTitleDLTypeRow',
      },
      {
        label: 'قرارداد خرید',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i14_chkTitleDLTypeRow',
      },
      {
        label: 'مرکز نگهداری',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i15_chkTitleDLTypeRow',
      },
      {
        label: 'انبار',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i16_chkTitleDLTypeRow',
      },
      {
        label: 'طبقه',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i17_chkTitleDLTypeRow',
      },
      {
        label: 'کالا',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i18_chkTitleDLTypeRow',
      },
      {
        label: 'قرارداد فروش',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i19_chkTitleDLTypeRow',
      },
      {
        label: 'طبقه حساب مشتری',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i20_chkTitleDLTypeRow',
      },
      {
        label: 'طبقه حساب محصول',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i21_chkTitleDLTypeRow',
      },
      {
        label: 'بخش',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i22_chkTitleDLTypeRow',
      },
      {
        label: 'کانال فروش',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i23_chkTitleDLTypeRow',
      },
      {
        label: 'مرکز فروش',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i24_chkTitleDLTypeRow',
      },
      {
        label: 'ماهیت تسویه',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLTypeRow_i25_chkTitleDLTypeRow',
      },
      {
        label: 'سطوح تفصیلی',
        type: 'text',
        disabled: true,
        sourceControlId: 'cboRowLevel_Input',
      },
      {
        label: 'گروه‌بندی',
        type: 'text',
        disabled: false,
        sourceControlId: 'btnShowGroupingRow',
      },
      {
        label: 'ستون',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboColumn_Input',
      },
      {
        label: 'نوع تفصیلی',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_Input',
      },
      {
        label: 'شخص',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i0_chkTitleDLTypeColumn',
      },
      {
        label: 'شرکت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i1_chkTitleDLTypeColumn',
      },
      {
        label: 'شعبه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i2_chkTitleDLTypeColumn',
      },
      {
        label: 'مرکز هزینه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i3_chkTitleDLTypeColumn',
      },
      {
        label: 'پروژه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i4_chkTitleDLTypeColumn',
      },
      {
        label: 'منبع تامین اعتبار',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i5_chkTitleDLTypeColumn',
      },
      {
        label: 'دوره مالی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i6_chkTitleDLTypeColumn',
      },
      {
        label: 'کد',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i7_chkTitleDLTypeColumn',
      },
      {
        label: 'طبقه خدمت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i8_chkTitleDLTypeColumn',
      },
      {
        label: 'حساب بانکی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i9_chkTitleDLTypeColumn',
      },
      {
        label: 'صندوق',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i10_chkTitleDLTypeColumn',
      },
      {
        label: 'تنخواه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i11_chkTitleDLTypeColumn',
      },
      {
        label: 'تسهیلات مالی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i12_chkTitleDLTypeColumn',
      },
      {
        label: 'سفارشات',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i13_chkTitleDLTypeColumn',
      },
      {
        label: 'قرارداد خرید',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i14_chkTitleDLTypeColumn',
      },
      {
        label: 'مرکز نگهداری',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i15_chkTitleDLTypeColumn',
      },
      {
        label: 'انبار',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i16_chkTitleDLTypeColumn',
      },
      {
        label: 'طبقه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i17_chkTitleDLTypeColumn',
      },
      {
        label: 'کالا',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i18_chkTitleDLTypeColumn',
      },
      {
        label: 'قرارداد فروش',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i19_chkTitleDLTypeColumn',
      },
      {
        label: 'طبقه حساب مشتری',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i20_chkTitleDLTypeColumn',
      },
      {
        label: 'طبقه حساب محصول',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i21_chkTitleDLTypeColumn',
      },
      {
        label: 'بخش',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i22_chkTitleDLTypeColumn',
      },
      {
        label: 'کانال فروش',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i23_chkTitleDLTypeColumn',
      },
      {
        label: 'مرکز فروش',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i24_chkTitleDLTypeColumn',
      },
      {
        label: 'ماهیت تسویه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboDLTypeColumn_i25_chkTitleDLTypeColumn',
      },
      {
        label: 'سطوح تفصیلی',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboColumnLevel_Input',
      },
      {
        label: 'گروه‌بندی',
        type: 'text',
        disabled: false,
        sourceControlId: 'btnShowGroupingColumn',
      },
    ],
    columns: ['شناسه', 'کد', 'عنوان', 'عنوان 1', 'عنوان به زبان دوم'],
    actions: [
      'گزارش',
      'راهنما (Ctrl+H)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'اجرای فیلتر',
      'نمایش بدون فیلتر',
      'حذف همه شرطها',
      'بارگذاری',
      'حذف از لیست',
      'ذخیره فیلتر',
      'برای مرتب سازی اینجا کلیک کنید',
      'جدید',
      'حذف',
      'بارگذاری مجدد',
      'ارسال به Excel',
      'انتخاب یک رکوردی',
      'ستونها',
      'شناسه',
      'کد',
      'عنوان',
      'عنوان 1',
      'عنوان به زبان دوم',
      'دریافت از Excel',
      'چاپ',
      'مدیریت فرم های چاپی ...',
    ],
    stage: 'گزارش ماتریسی',
  },
  {
    route: 'general-ledger/reports/electronic-trade-books',
    title: 'دفاتر تجاری الکترونیکی',
    sourcePath: 'مالی / دفتر کل / گزارش ها / دفاتر تجاری الکترونیکی',
    sourcePage: 'Financial/Reports/ElectronicBookPages/ElectonicBookPage.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpFromDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpToDate_MaskedTextBox',
      },
      {
        label: 'نوع فایل خروجی',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFileType_Input',
      },
      {
        label: 'همراه با کد حساب معین',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkShowSLCode',
      },
      {
        label: 'همراه با عنوان حساب معین',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkShowSLTitle',
      },
      {
        label: 'همراه با شرح سند حسابداری',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkShowDescription',
      },
    ],
    columns: [],
    actions: ['ارسال به فایل'],
    stage: 'دفاتر تجاری الکترونیکی',
  },
  {
    route: 'receipts-payments/base-information/standard-descriptions',
    title: 'خطا',
    sourcePath: 'مالی / دریافت و پرداخت / اطلاعات پایه / شرح استاندارد',
    sourcePage:
      'General/DescriptionManagement/StandardDescriptionPages/Edit.aspx',
    evidenceStatus: 'source-error',
    fields: [],
    columns: [],
    actions: ['مشاهده اطلاعات بیشتر'],
    stage: 'خطا',
  },
  {
    route: 'taxpayer-system/settings',
    title: 'تنظیمات ارسال صورت حساب',
    sourcePath:
      'مالی / ارتباط با سامانه مودیان مالیاتی / تنظیمات سامانه مالیاتی',
    sourcePage: 'General/TaxPayerManagement/TaxPaymentProfilePages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'نوع ارسال صورت حساب',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpSendingType_ComboBox_Input',
      },
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle',
      },
      {
        label: 'شناسه حافظه مالیاتی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDirectTaxMemoryID',
      },
      {
        label: 'کلید خصوصی مودی',
        type: 'textarea',
        disabled: false,
        sourceControlId: 'txtDirectPrivate',
      },
      {
        label: 'گواهی امضا',
        type: 'textarea',
        disabled: false,
        sourceControlId: 'txtDirectCertificate',
      },
      {
        label: 'نام معتمد',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpIndirectCompany_ComboBox_Input',
      },
      {
        label: 'رمز سرویس معتمد',
        type: 'password',
        disabled: false,
        sourceControlId: 'txtIndirectServicePass',
      },
      {
        label: 'آدرس سرویس معتمد',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtIndirectServiceAddress',
      },
      {
        label: 'نام کاربر سرویس معتمد',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtIndirectUserName',
      },
      {
        label: 'کلید سرویس معتمد',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtIndirectServiceKey',
      },
    ],
    columns: [],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'اطلاعات اصلی',
      'یادداشت',
    ],
    stage: 'تنظیمات ارسال صورت حساب',
  },
  {
    route: 'taxpayer-system/seller-information',
    title: 'اطلاعات فروشنده',
    sourcePath: 'مالی / ارتباط با سامانه مودیان مالیاتی / اطلاعات فروشنده',
    sourcePage:
      'General/TaxPayerManagement/TaxPayerSellerInformationPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'عنوان فروشنده',
        type: 'text',
        disabled: true,
        sourceControlId: 'fvwMain_SellerNameTB',
      },
      {
        label: 'نوع فروشنده',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_lkpPartyType_ComboBox_Input',
      },
      {
        label: 'شناسه ملی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_txtNationalID',
      },
      {
        label: 'کد اقتصادی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_txtEconomicID',
      },
      {
        label: 'شناسه مشارکت مدنی',
        type: 'text',
        disabled: true,
        sourceControlId: 'fvwMain_txtCivilParticipationID',
      },
    ],
    columns: [],
    actions: [
      'ذخیره (Ctrl+S)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'اطلاعات اصلی',
      'یادداشت',
    ],
    stage: 'اطلاعات فروشنده',
  },
  {
    route: 'taxpayer-system/send-invoices',
    title: 'خطا',
    sourcePath:
      'مالی / ارتباط با سامانه مودیان مالیاتی / جمع آوری / ارسال صورتحساب',
    sourcePage:
      'General/TaxPayerManagement/TaxPayerBillPages/TaxPayerBillList.aspx',
    evidenceStatus: 'source-error',
    fields: [],
    columns: [],
    actions: ['مشاهده اطلاعات بیشتر'],
    stage: 'خطا',
  },
  {
    route: 'taxpayer-system/reconciliation',
    title: 'مغایرت گیری صورتحسابهای راهکاران و کارپوشه',
    sourcePath:
      'مالی / ارتباط با سامانه مودیان مالیاتی / مغایرت گیری صورتحسابهای راهکاران و کارپوشه',
    sourcePage:
      'General/TaxPayerManagement/ConflictPages/TaxPayerBillConflictReport.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'wzdConflict_step1_dpFromDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'wzdConflict_step1_dpToDate_MaskedTextBox',
      },
      {
        label: 'فایل داده ها',
        type: 'text',
        disabled: false,
        sourceControlId: 'wzdConflict_step1_fuUploadExcel',
      },
      {
        label: 'عدم وجود صورتحساب در راهکاران',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'wzdConflict_step1_chbAbsenceOfBillingInRahkaranStep',
      },
      {
        label: 'عدم وجود صورتحساب در کارپوشه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'wzdConflict_step1_chbAbsenceOfBillingInIntamediaStep',
      },
      {
        label: 'وضعیت صورتحساب',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'wzdConflict_step1_chbTaxPayerBillStateStep',
      },
      {
        label: 'مغایرت مبلغی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'wzdConflict_step1_chbAmountDiscrepancyStep',
      },
      {
        label: 'وضعیت صورتحساب در کارپوشه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'wzdConflict_step1_chbTaxpayerSystemStatusStep',
      },
      {
        label: 'عملیات رد صورتحساب برای صورتحساب های "رد موقت"',
        type: 'checkbox',
        disabled: false,
        sourceControlId:
          'wzdConflict_step1_chbTaxpayerSystemRejectStrategyStep',
      },
      {
        label: 'صدور ابطال سیستمی برای توالی صورتحساب ها',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'wzdConflict_step1_chbInvalidNonCanceledChains',
      },
    ],
    columns: [
      'شماره مالیاتی صورتحساب',
      'موضوع صورتحساب',
      'وضعیت صورتحساب',
      'مجموع صورتحساب',
      'مالیات بر ارزش افزوده',
      'تاریخ صدور صورتحساب',
    ],
    actions: [
      'ورود اطلاعات',
      'عدم وجود صورتحساب در راهکاران',
      'عدم وجود صورتحساب در کارپوشه',
      'وضعیت صورتحساب',
      'مغایرت مبلغی',
      'وضعیت صورتحساب در کارپوشه',
      'عملیات رد صورتحساب برای صورتحساب های "رد موقت"',
      'صدور ابطال سیستمی برای توالی صورتحساب ها',
      'شروع مغایرت گیری',
      'شماره مالیاتی صورتحساب',
      'موضوع صورتحساب',
      'مجموع صورتحساب',
      'مالیات بر ارزش افزوده',
      'تاریخ صدور صورتحساب',
      'جستجو (Ctrl+F)',
      'ارسال به Excel',
      'تعداد ردیف: 0',
    ],
    stage: 'مغایرت گیری صورتحسابهای راهکاران و کارپوشه',
  },
  {
    route: 'taxpayer-system/cancellation-invoice',
    title: 'صدور صورتحساب ابطال',
    sourcePath: 'مالی / ارتباط با سامانه مودیان مالیاتی / صدور صورتحساب ابطال',
    sourcePage:
      'General/TaxPayerManagement/TaxPayerCancellationBillPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'شماره مالیاتی ابطال',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtUniqueBillNumber',
      },
      {
        label: 'تاریخ ابطال',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpCancellationDate_MaskedTextBox',
      },
      {
        label: 'شماره مالیاتی مرجع',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtUniqueBillNumberRef',
      },
      {
        label: 'موضوع مرجع',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpReferenceActionType_ComboBox_Input',
      },
      {
        label: 'تاریخ مرجع',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpReferenceDate_MaskedTextBox',
      },
      {
        label: 'شناسه موجودیت',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtReferenceRef',
      },
    ],
    columns: [],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'اطلاعات اصلی',
      'یادداشت',
    ],
    stage: 'صدور صورتحساب ابطال',
  },
  {
    route: 'taxpayer-system/middleware-information',
    title: 'اطلاعات میدلور',
    sourcePath: 'مالی / ارتباط با سامانه مودیان مالیاتی / اطلاعات میدلور',
    sourcePage:
      'General/TaxPayerManagement/MiddlewareInformationPages/Info.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'آخرین تاریخ و زمان دریافت اطلاعات',
        type: 'date',
        disabled: false,
        sourceControlId: 'txtLastReceiveDateTime',
      },
      {
        label: 'ورژن میدلور',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtMiddlewareVersion',
      },
      {
        label: 'نام کامپیوتر',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtComputerName',
      },
      {
        label: 'مسیر میدلور',
        type: 'textarea',
        disabled: false,
        sourceControlId: 'txtMiddlewarePath',
      },
      {
        label: 'آدرس های IP',
        type: 'textarea',
        disabled: false,
        sourceControlId: 'txtIPAddresses',
      },
    ],
    columns: [],
    actions: [
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'تغییر وضعیت (Ctrl+J)',
      'اطلاعات اصلی',
      'تاریخچه تغییر وضعیت',
      'مکالمات',
      'یادداشت',
      'فرآیندهای مرتبط',
    ],
    stage: 'اطلاعات میدلور',
  },
  {
    route: 'tax-accounting/base-information/quarterly-thresholds',
    title: 'حد نصاب تجمیع گزارش فصلی',
    sourcePath:
      'مالی / حسابداری مالیاتی / اطلاعات پایه / معرفی حد نصاب تجمیع گزارش فصلی',
    sourcePage: 'Financial/VAT/TaxInformationPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle',
      },
      {
        label: 'مبلغ حد نصاب معاملات کوچک',
        type: 'text',
        disabled: false,
        sourceControlId: 'decSmallDealsQuorum_input',
      },
      {
        label: 'موثر از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpEffectiveDate_MaskedTextBox',
      },
      {
        label: 'درصد تجمیع معاملات کوچک',
        type: 'text',
        disabled: false,
        sourceControlId: 'decSmallDealsMergeRate_input',
      },
      {
        label: 'مبلغ حد نصاب تجمیع معاملات',
        type: 'text',
        disabled: false,
        sourceControlId: 'decSmallDealsMergeAmount_input',
      },
    ],
    columns: [],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'اطلاعات اصلی',
      'یادداشت',
    ],
    stage: 'حد نصاب تجمیع گزارش فصلی',
  },
] as const satisfies readonly AccountingParityCapture[];
