import type { AccountingParityCapture } from './accounting-parity-definitions';

export const accountingParitySource2 = [
  {
    route: 'general-ledger/documents/subledger-transfer',
    title: 'ارسال سند به دفترکل فرعی',
    sourcePath: 'مالی / دفتر کل / اسناد / ارسال سند به دفترکل فرعی',
    sourcePage:
      'Financial/VoucherManagement/SendVoucherToAnotherLedgerPages/SendVoucherToAnotherLedger.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'فیلتر',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFilter_Input',
      },
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkFromDate_MaskedTextBox',
      },
      {
        label: 'از سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtFromNumber',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkToDate_MaskedTextBox',
      },
      {
        label: 'تا سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtToNumber',
      },
      {
        label: 'ارسال تجمیعی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkAccumulatedSending',
      },
      {
        label: 'تاریخ اسناد ارسالی',
        type: 'date',
        disabled: false,
        sourceControlId: 'cboDates_Input',
      },
      {
        label: 'تاریخ',
        type: 'date',
        disabled: true,
        sourceControlId: 'dpkVouchersDate_MaskedTextBox',
      },
    ],
    columns: [
      'شناسه',
      'سند ارزی',
      'شماره سند',
      'تاریخ',
      'وضعیت',
      'نوع سند',
      'شرح',
      'شماره عطف',
      'شماره فرعی',
      'مبلغ سند',
    ],
    actions: [
      'فیلتر',
      'ارسال',
      'ارسال همه',
      'برای مرتب سازی اینجا کلیک کنید',
      'بارگذاری مجدد( Ctrl+R)',
      'ارسال به Excel',
      'عدم نمایش فیلتر( Ctrl+F)',
      'انتخاب یک رکوردی( Ctrl+M)',
      'ستونها',
      'شناسه',
      'سند ارزی',
      'شماره سند',
      'تاریخ',
      'وضعیت',
      'نوع سند',
      'شرح',
      'شماره عطف',
      'شماره فرعی',
      'مبلغ سند',
      'محاسبه تعداد رکوردها و صفحات فهرست( Ctrl+K)',
      'دریافت از Excel',
      'مدیریت فرم های چاپی ...',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'بارگذاری مجدد',
      'عدم نمایش فیلتر',
      'انتخاب یک رکوردی',
      'چاپ',
    ],
    stage: 'ارسال سند به دفترکل فرعی',
  },
  {
    route: 'general-ledger/documents/deleted',
    title: 'اسناد حذف شده',
    sourcePath: 'مالی / دفتر کل / اسناد / اسناد حذف شده',
    sourcePage:
      'Financial/VoucherManagement/DeletedVoucherPages/DeletedVoucher.aspx',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [
      'شناسه',
      'تاریخ حذف سند',
      'حذف کننده سند',
      'شماره سند',
      'شماره عطف',
      'شماره روزانه',
      'تاریخ سند',
      'صادر کننده سند',
      'شماره ارجاع',
    ],
    actions: [
      'برای مرتب سازی اینجا کلیک کنید',
      'بارگذاری مجدد( Ctrl+R)',
      'ارسال به Excel',
      'عدم نمایش فیلتر( Ctrl+F)',
      'ستونها',
      'شناسه',
      'تاریخ حذف سند',
      'حذف کننده سند',
      'شماره سند',
      'شماره عطف',
      'شماره روزانه',
      'تاریخ سند',
      'صادر کننده سند',
      'شماره ارجاع',
      'محاسبه تعداد رکوردها و صفحات فهرست( Ctrl+K)',
      'مدیریت فرم های چاپی ...',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'بارگذاری مجدد',
      'عدم نمایش فیلتر',
      'چاپ',
    ],
    stage: 'اسناد حذف شده',
  },
  {
    route: 'general-ledger/year-end/closing-templates',
    title: 'الگوی بستن حساب',
    sourcePath: 'مالی / دفتر کل / عملیات پایان سال / تعریف الگوی بستن حساب',
    sourcePage:
      'Financial/VoucherManagement/ClosingPages/Edit.aspx?ActionContext=1201',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'کد',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtCode',
      },
      {
        label: 'فعال',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkState',
      },
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle',
      },
      {
        label: 'عنوان به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtEnTitle',
      },
      {
        label: 'شرح پیش فرض',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDescription',
      },
      {
        label: 'شرح پیش فرض به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtEnDescription',
      },
      {
        label: 'سطح تفصیلی',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpdlBasedOnLevelCount_ComboBox_Input',
      },
    ],
    columns: [
      'کد حساب معین',
      'سطح 4',
      'سطح 5',
      'سطح 6',
      'درصد',
      'شمول/عدم شمول',
      'انتخاب سطوح',
      'شناسه',
      'کد',
      'عنوان',
      'نوع تفصیلی',
      'تفصیلی پدر',
      'کد تفصیلی پدر',
      'عنوان تفصیل پدر',
      'شماره طبقه بندی',
      'نوع تفصیلی 1',
      'وضعیت',
    ],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'سایر عملیات (Ctrl+K)',
      'دریافت از Excel',
      'راهنما (Ctrl+H)',
      'اطلاعات اصلی',
      'یادداشت',
      'انتخاب',
      'افزودن (Insert)',
      'حذف (Delete)',
      'جستجو (Ctrl+F)',
      'انتخاب دسته ای معین',
      'انتخاب معین با سطوح مشخص',
      'انتخاب بر اساس کد تفصیلی',
      'اجرای فیلتر',
      'نمایش بدون فیلتر',
      'حذف همه شرطها',
      'بارگذاری',
      'حذف از لیست',
      'ذخیره فیلتر',
      'برای مرتب سازی اینجا کلیک کنید',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'جدید',
      'حذف',
      'بارگذاری مجدد',
      'ارسال به Excel',
      'عدم نمایش فیلتر',
      'انتخاب یک رکوردی',
      'ستونها',
      'شناسه',
      'کد',
      'عنوان',
      'نوع تفصیلی',
      'تفصیلی پدر',
      'کد تفصیلی پدر',
      'عنوان تفصیل پدر',
      'شماره طبقه بندی',
      'نوع تفصیلی 1',
      'وضعیت',
      'مدیریت فرم های چاپی ...',
    ],
    stage: 'الگوی بستن حساب',
  },
  {
    route: 'general-ledger/year-end/nature-adjustment',
    title: 'تعدیل ماهیت',
    sourcePath: 'مالی / دفتر کل / عملیات پایان سال / صدور سند تعدیل ماهیت',
    sourcePage:
      'Financial/VoucherManagement/AdjustmentVoucherPages/AdjustmentVoucherWizard.aspx',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [],
    actions: [
      'شرح راهبر',
      'مشخصات سند',
      'حساب های بدون طرف مقابل',
      'پیش نمایش سند',
      'پایان عملیات صدور سند تعدیل ماهیت',
      'ادامه',
    ],
    stage: 'تعدیل ماهیت',
  },
  {
    route: 'general-ledger/documents/posting',
    title: 'قطعی کردن اسناد',
    sourcePath: 'مالی / دفتر کل / اسناد / قطعی کردن اسناد',
    sourcePage:
      'Financial/VoucherManagement/FinalizeVoucherPages/FinalizeVoucher.aspx',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [],
    actions: [
      'شرح راهبر',
      'تعیین وضعیت فیلترها',
      'فهرست اسناد',
      'سند خلاف ماهیت',
      'پایان عملیات قطعی کردن',
      'ادامه',
    ],
    stage: 'قطعی کردن اسناد',
  },
  {
    route: 'general-ledger/year-end/closing',
    title: 'بستن حساب ها',
    sourcePath: 'مالی / دفتر کل / عملیات پایان سال / صدور سند بستن حساب ها',
    sourcePage:
      'Financial/VoucherManagement/ClosingPages/ClosingVoucherWizard.aspx',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [],
    actions: [
      'شرح راهبر',
      'انتخاب الگوی بستن حساب',
      'تعریف نرخ ارز',
      'پیش نمایش سند',
      'پایان عملیات',
      'ادامه',
    ],
    stage: 'بستن حساب ها',
  },
  {
    route: 'general-ledger/year-end/final',
    title: 'اختتامیه',
    sourcePath: 'مالی / دفتر کل / عملیات پایان سال / صدور سند اختتامیه',
    sourcePage:
      'Financial/VoucherManagement/EndingOpeningVoucher/EndingOpeningVoucherWizard.aspx?PageType=Ending',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'تاریخ سند',
        type: 'date',
        disabled: false,
        sourceControlId: 'dtpDate_MaskedTextBox',
      },
      {
        label: 'شماره فرعی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtAuxiliaryNumber',
      },
    ],
    columns: [],
    actions: ['ذخیره'],
    stage: 'اختتامیه',
  },
  {
    route: 'general-ledger/year-end/opening',
    title: 'افتتاحیه',
    sourcePath: 'مالی / دفتر کل / عملیات پایان سال / صدور سند افتتاحیه',
    sourcePage:
      'Financial/VoucherManagement/EndingOpeningVoucher/EndingOpeningVoucherWizard.aspx?PageType=Opening',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'تاریخ سند',
        type: 'date',
        disabled: false,
        sourceControlId: 'dtpDate_MaskedTextBox',
      },
      {
        label: 'شماره فرعی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtAuxiliaryNumber',
      },
      {
        label: 'صدور سند معکوس تعدیل ماهیت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'ckRevertAdjustment',
      },
    ],
    columns: [],
    actions: ['ذخیره'],
    stage: 'افتتاحیه',
  },
  {
    route: 'general-ledger/reports/account-browser',
    title: 'مرور حساب ها',
    sourcePath: 'مالی / دفتر کل / گزارش ها / مرور حساب ها',
    sourcePage: 'Financial/Analysis/ReviewPages/Review.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsToFiscalYear_Input',
      },
      {
        label: 'نوع حساب',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboType_Input',
      },
      {
        label: 'حساب های بامانده',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkWithBalance',
      },
      {
        label: 'نوع تفصیلی',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboDLType_Input',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherType_Input',
      },
      {
        label: 'وضعیت سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherState_Input',
      },
      {
        label: 'فیلتر',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFilter_Input',
      },
      {
        label: 'از ماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFromMonth_Input',
      },
      {
        label: 'تا ماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboToMonth_Input',
      },
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkFromDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkToDate_MaskedTextBox',
      },
      {
        label: 'از سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtFromNumber',
      },
      {
        label: 'تا سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtToNumber',
      },
    ],
    columns: [],
    actions: [
      'فیلتر مجدد',
      'مرور تفصیلی ها',
      'بر اساس سطح تفصیلی',
      'بر اساس نوع تفصیلی',
      'نمایش ستون شماره طبقه بندی',
      'راهنما (Ctrl+H)',
      'گزارش',
      'فیلتر اسناد',
      'گروه',
      'کل',
      'معین',
      'سطح چهار',
      'سطح پنج',
      'سطح شش',
      'ارز',
      'پیگیری',
      'حساب تفصیلی',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'بروز رسانی',
      'چاپ',
      'مشاهده گردش',
      'آنالیز',
      'اطلاعات ارزی',
      'صدور اعلامیه',
      'بدهکار',
      'بستانکار',
      'بدهکار/بستانکار',
      'تعداد رکوردها',
    ],
    stage: 'مرور حساب ها',
  },
  {
    route: 'general-ledger/reports/chart-structure',
    title: 'گزارش ساختار حساب ها',
    sourcePath: 'مالی / دفتر کل / گزارش ها / گزارش ساختار حساب ها',
    sourcePage: 'Financial/Reports/COAPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'گروه حساب',
        type: 'text',
        disabled: false,
        sourceControlId: 'rdbAccountGroup',
      },
      {
        label: 'عنوان به زبان دوم',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkACTitle_en',
      },
      {
        label: 'وضعیت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkACState',
      },
      {
        label: 'شرح',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkACDescription',
      },
      {
        label: 'حساب کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'rdbGL',
      },
      {
        label: 'عنوان به زبان دوم',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkGLTitle_en',
      },
      {
        label: 'نوع',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkGLType',
      },
      {
        label: 'ماهیت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkGLNature',
      },
      {
        label: 'وضعیت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkGLState',
      },
      {
        label: 'شرح',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkGLDescription',
      },
      {
        label: 'معین',
        type: 'text',
        disabled: false,
        sourceControlId: 'rdbSL',
      },
      {
        label: 'عنوان به زبان دوم',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkSLTitle_En',
      },
      {
        label: 'ویژگی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkFeature',
      },
      {
        label: 'ویژگی مالیاتی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkVATSLType',
      },
      {
        label: 'نوع',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkSLType',
      },
      {
        label: 'ارز پایه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkDefaultCurrency',
      },
      {
        label: 'انواع حساب مالیاتی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkTaxAccountType',
      },
      {
        label: 'ماهیت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkSLNature',
      },
      {
        label: 'تعداد سطوح',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkLevelCount',
      },
      {
        label: 'وضعیت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkSLState',
      },
      {
        label: 'حساب طرف مقابل',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkSLCounterPart',
      },
      {
        label: 'شرح',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkSLDescription',
      },
      {
        label: 'نگاشت به حساب',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkMapping',
      },
      {
        label: 'گزارش ساختاری',
        type: 'text',
        disabled: false,
        sourceControlId: 'rdbStructural',
      },
      {
        label: 'ساختار حساب ها',
        type: 'text',
        disabled: false,
        sourceControlId: 'rdCOA',
      },
      {
        label: 'انواع تفصیلی تخصیص داده شده به سطوح',
        type: 'text',
        disabled: false,
        sourceControlId: 'rdDLLevels',
      },
      {
        label: 'حساب های معین طرف مقابل',
        type: 'text',
        disabled: false,
        sourceControlId: 'rdCounterPart',
      },
    ],
    columns: [],
    actions: ['گزارش', 'راهنما (Ctrl+H)'],
    stage: 'گزارش ساختار حساب ها',
  },
  {
    route: 'general-ledger/reports/trial-balance',
    title: 'گزارش تراز',
    sourcePath: 'مالی / دفتر کل / گزارش ها / تراز',
    sourcePage: 'Financial/Reports/BalancePages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsToFiscalYear_Input',
      },
      {
        label: 'ساختار گزارش',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpStructure_ComboBox_Input',
      },
      {
        label: 'نوع مانده',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpBalanceType_ComboBox_Input',
      },
      {
        label: 'فیلتر',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFilter_Input',
      },
      {
        label: 'ازماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFromMonth_Input',
      },
      {
        label: 'تا ماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboToMonth_Input',
      },
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkFromDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkToDate_MaskedTextBox',
      },
      {
        label: 'از سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtFromNumber',
      },
      {
        label: 'تا سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtToNumber',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherType_Input',
      },
      {
        label: 'ویژگی',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboAccountSpecification_Input',
      },
      {
        label: 'مبنای ارز',
        type: 'text',
        disabled: true,
        sourceControlId: 'cboCurrencyBase_Input',
      },
      {
        label: 'نمایش مبالغ ریالی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkRial',
      },
      {
        label: 'نمایش مبالغ ارزی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkCurrency',
      },
      {
        label: 'نمایش فقط حساب های بدون تفصیلی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkSLWithNoDL',
      },
      {
        label: 'چاپ حساب ها در صفحات مجزا',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkPrintInSeperatePage',
      },
      {
        label: 'احتساب گردش از سال گذشته',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkLastYearBalance',
      },
      {
        label: 'افتتاحیه در ستون مجزا',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkOpeningInSeperatly',
      },
      {
        label: 'معین های فعال',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkShowOnlyActiveSLs',
      },
      {
        label: 'معین های دارای ویژگی پیگیری',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkShowTraceableSLs',
      },
    ],
    columns: ['عنوان'],
    actions: [
      'چاپ',
      'مرور تفصیلی ها',
      'سطح تفصیلی',
      'نوع تفصیلی',
      'راهنما (Ctrl+H)',
      'فیلتر اولیه',
      'فیلتر ثانویه',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'اضافه',
      'بالا',
      'پایین',
      'افزودن (Insert)',
      'حذف (Delete)',
      'جستجو (Ctrl+F)',
    ],
    stage: 'گزارش تراز',
  },
  {
    route: 'general-ledger/reports/legal-ledgers',
    title: 'گزارش دفاتر قانونی',
    sourcePath: 'مالی / دفتر کل / گزارش ها / دفاتر قانونی',
    sourcePage: 'Financial/Reports/JournalPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'نوع گزارش',
        type: 'text',
        disabled: false,
        sourceControlId: 'cmbReportFilter_Input',
      },
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsToFiscalYear_Input',
      },
      {
        label: 'فیلتر',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFilter_Input',
      },
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkFromDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkToDate_MaskedTextBox',
      },
      {
        label: 'از سند کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtFromNumber',
      },
      {
        label: 'تا سند کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtToNumber',
      },
      {
        label: 'حساب کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboType_Input',
      },
    ],
    columns: [],
    actions: [
      'مشاهده گزارش',
      'راهنما (Ctrl+H)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'اجرای گزارش',
      'بازگشت به گزارش پدر',
      'صفحه اول',
      'صفحه قبلی',
      'صفحه بعد',
      'صفحه آخر',
      'ارسال',
      'XML',
      'CSV',
      'PDF',
      'MHTML',
      'IMAGE',
      'WORD',
      'EXCEL',
      'داده ها به Excel',
      'چاپ',
      'پیش نمایش چاپ',
      'Cancel',
    ],
    stage: 'گزارش دفاتر قانونی',
  },
  {
    route: 'general-ledger/reports/ledgers',
    title: 'گزارش دفاتر',
    sourcePath: 'مالی / دفتر کل / گزارش ها / دفاتر',
    sourcePage: 'Financial/Reports/BookPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsToFiscalYear_Input',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherType_Input',
      },
      {
        label: 'احتساب آنالیز',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpMatch_ComboBox_Input',
      },
      {
        label: 'فیلتر',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFilter_Input',
      },
      {
        label: 'ازماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboFromMonth_Input',
      },
      {
        label: 'تا ماه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboToMonth_Input',
      },
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkFromDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkToDate_MaskedTextBox',
      },
      {
        label: 'از سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtFromNumber',
      },
      {
        label: 'تا سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'numtxtToNumber',
      },
      {
        label: 'ویژگی',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboAccountSpecification_Input',
      },
      {
        label: 'نوع گزارش',
        type: 'text',
        disabled: true,
        sourceControlId: 'cboCurrencyReportType_Input',
      },
      {
        label: 'مبنای ارز',
        type: 'text',
        disabled: true,
        sourceControlId: 'cboCurrencyType_Input',
      },
      {
        label: 'مبالغ ریالی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkOperational',
      },
      {
        label: 'مبالغ ارزی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkCurrency',
      },
      {
        label: 'نمایش فقط حساب های بدون تفصیلی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkSLWithNoDL',
      },
      {
        label: 'چاپ حساب ها در صفحات مجزا',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkPrintInSeperatePage',
      },
      {
        label: 'احتساب مانده از ابتدای دوره',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkRemainingFromInitialFiscalYear',
      },
      {
        label: 'احتساب گردش از سال گذشته',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkRemainingFromLastYear',
      },
      {
        label: 'معین های فعال',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkShowNonActiveSLs',
      },
      {
        label: 'معین های دارای ویژگی پیگیری',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkIsTraceable',
      },
    ],
    columns: ['عنوان'],
    actions: [
      'چاپ',
      'مرور تفصیلی ها',
      'سطح تفصیلی',
      'نوع تفصیلی',
      'راهنما (Ctrl+H)',
      'فیلتر اولیه',
      'فیلتر ثانویه',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'اضافه',
      'بالا',
      'پایین',
      'افزودن (Insert)',
      'حذف (Delete)',
      'جستجو (Ctrl+F)',
    ],
    stage: 'گزارش دفاتر',
  },
  {
    route: 'general-ledger/reports/debit-credit-notices',
    title: 'فهرست اعلامیه بدهکار- بستانکار',
    sourcePath: 'مالی / دفتر کل / گزارش ها / اعلامیه بدهکار / بستانکار',
    sourcePage:
      'List.aspx?ComponentName=SystemGroup.Financial.Analysis&EntityName=DebitCreditStatement',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [
      'شناسه',
      'عنوان تفصیلی',
      'شماره',
      'شماره براساس گیرنده',
      'تاریخ',
      'نوع',
      'وضعیت',
      'شرح',
      'بدهکار کل',
      'بستانکار کل',
    ],
    actions: [
      'اجرای فیلتر',
      'نمایش بدون فیلتر',
      'حذف همه شرطها',
      'پاک کردن',
      'ویرایش',
      'بارگذاری',
      'حذف از لیست',
      'ذخیره فیلتر',
      'جدید (Ctrl+B)',
      'حذف (Ctrl+D)',
      'ویرایش (Ctrl+L)',
      'چاپ',
      'بارگذاری مجدد( Ctrl+R)',
      'دریافت اطلاع از تغییرات',
      'ارسال به Excel',
      'عدم نمایش فیلتر( Ctrl+F)',
      'انتخاب چند رکوردی( Ctrl+M)',
      'ستونها',
      'شناسه',
      'عنوان تفصیلی',
      'شماره',
      'شماره براساس گیرنده',
      'تاریخ',
      'نوع',
      'وضعیت',
      'شرح',
      'بدهکار کل',
      'بستانکار کل',
      'محاسبه تعداد رکوردها و صفحات فهرست( Ctrl+K)',
      'مدیریت فرم های چاپی ...',
      'برای مرتب سازی اینجا کلیک کنید',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'جدید',
      'حذف',
      'سایر عملیات',
      'بارگذاری مجدد',
      'عدم نمایش فیلتر',
      'انتخاب چند رکوردی',
    ],
    stage: 'فهرست اعلامیه بدهکار- بستانکار',
  },
  {
    route: 'general-ledger/reports/nature-conflict-period',
    title: 'گزارش خلاف ماهیت برای یک دوره مالی',
    sourcePath: 'مالی / دفتر کل / گزارش ها / خلاف ماهیت برای یک دوره مالی',
    sourcePage: 'Financial/Reports/AdjustmentPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'نوع ماهیت',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboNature_Input',
      },
      {
        label: 'بدهکار',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboNature_i0_chkTitleNature',
      },
      {
        label: 'بستانکار',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboNature_i1_chkTitleNature',
      },
      {
        label: 'نوع حساب',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboType_Input',
      },
      {
        label: 'دائم',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboType_i0_chkTitleType',
      },
      {
        label: 'موقت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboType_i1_chkTitleType',
      },
      {
        label: 'انتظامی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboType_i2_chkTitleType',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkToDate_MaskedTextBox',
      },
      {
        label: 'نمایش حساب های طرف مقابل',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkCounterPart',
      },
    ],
    columns: [],
    actions: [
      'مشاهده گزارش',
      'راهنما (Ctrl+H)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'اجرای گزارش',
      'بازگشت به گزارش پدر',
      'صفحه اول',
      'صفحه قبلی',
      'صفحه بعد',
      'صفحه آخر',
      'ارسال',
      'XML',
      'CSV',
      'PDF',
      'MHTML',
      'IMAGE',
      'WORD',
      'EXCEL',
      'داده ها به Excel',
      'چاپ',
      'پیش نمایش چاپ',
      'Cancel',
    ],
    stage: 'گزارش خلاف ماهیت برای یک دوره مالی',
  },
  {
    route: 'general-ledger/reports/comparative',
    title: 'گزارش مقایسه ای',
    sourcePath: 'مالی / دفتر کل / گزارش ها / مقایسه ای',
    sourcePage: 'Financial/Reports/ComparitivePages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsToFiscalYear_Input',
      },
      {
        label: 'ماهیت حساب ها',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpBalanceType_ComboBox_Input',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherType_Input',
      },
      {
        label: 'وضعیت سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboVoucherState_Input',
      },
      {
        label: 'ویژگی',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboAccountSpecification_Input',
      },
      {
        label: 'ارز',
        type: 'text',
        disabled: true,
        sourceControlId: 'cboCurrency_Input',
      },
      {
        label: 'مانده / گردش دوره',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkRemaining',
      },
      {
        label: 'مغایرت دو دوره',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkDifference',
      },
      {
        label: 'نسبت تغییر',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkChangeRatio',
      },
      {
        label: 'نرخ رشد',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkGrowthRate',
      },
      {
        label: 'نمایش تجمیعی ستون ها',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkIntegratedValues',
      },
      {
        label: 'نمایش فقط حساب های بدون تفصیلی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkSLWithNoDL',
      },
      {
        label: 'چاپ حساب ها در صفحات مجزا',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkPrintInSeperatePage',
      },
      {
        label: 'ازماه',
        type: 'text',
        disabled: true,
        sourceControlId: 'cboFromMonth_Input',
      },
      {
        label: 'تا ماه',
        type: 'text',
        disabled: true,
        sourceControlId: 'cboToMonth_Input',
      },
    ],
    columns: ['عنوان', 'از تاریخ', 'تا تاریخ'],
    actions: [
      'گزارش',
      'راهنما (Ctrl+H)',
      'فیلتر اولیه',
      'فیلتر ثانویه',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'اضافه',
      'بالا',
      'پایین',
      'افزودن (Insert)',
      'حذف (Delete)',
      'جستجو (Ctrl+F)',
    ],
    stage: 'گزارش مقایسه ای',
  },
  {
    route: 'general-ledger/reports/dormant-accounts',
    title: 'گزارش حساب های راکد',
    sourcePath: 'مالی / دفتر کل / گزارش ها / حساب های راکد',
    sourcePage: 'Financial/Reports/StagnantAccountsPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsFromFiscalYear_Input',
      },
      {
        label: 'تا دوره مالی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sgsToFiscalYear_Input',
      },
      {
        label: 'سطح',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpReportLevel_ComboBox_Input',
      },
      {
        label: 'نوع تفصیلی',
        type: 'text',
        disabled: true,
        sourceControlId: 'cboDLType_Input',
      },
      {
        label: 'شخص',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i0_chkTitleDLType',
      },
      {
        label: 'شرکت',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i1_chkTitleDLType',
      },
      {
        label: 'شعبه',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i2_chkTitleDLType',
      },
      {
        label: 'مرکز هزینه',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i3_chkTitleDLType',
      },
      {
        label: 'پروژه',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i4_chkTitleDLType',
      },
      {
        label: 'منبع تامین اعتبار',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i5_chkTitleDLType',
      },
      {
        label: 'دوره مالی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i6_chkTitleDLType',
      },
      {
        label: 'کد',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i7_chkTitleDLType',
      },
      {
        label: 'طبقه خدمت',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i8_chkTitleDLType',
      },
      {
        label: 'حساب بانکی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i9_chkTitleDLType',
      },
      {
        label: 'صندوق',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i10_chkTitleDLType',
      },
      {
        label: 'تنخواه',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i11_chkTitleDLType',
      },
      {
        label: 'تسهیلات مالی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i12_chkTitleDLType',
      },
      {
        label: 'سفارشات',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i13_chkTitleDLType',
      },
      {
        label: 'قرارداد خرید',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i14_chkTitleDLType',
      },
      {
        label: 'مرکز نگهداری',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i15_chkTitleDLType',
      },
      {
        label: 'انبار',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i16_chkTitleDLType',
      },
      {
        label: 'طبقه',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i17_chkTitleDLType',
      },
      {
        label: 'کالا',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i18_chkTitleDLType',
      },
      {
        label: 'قرارداد فروش',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i19_chkTitleDLType',
      },
      {
        label: 'طبقه حساب مشتری',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i20_chkTitleDLType',
      },
      {
        label: 'طبقه حساب محصول',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i21_chkTitleDLType',
      },
      {
        label: 'بخش',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i22_chkTitleDLType',
      },
      {
        label: 'کانال فروش',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i23_chkTitleDLType',
      },
      {
        label: 'مرکز فروش',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i24_chkTitleDLType',
      },
      {
        label: 'ماهیت تسویه',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'cboDLType_i25_chkTitleDLType',
      },
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkFromDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkToDate_MaskedTextBox',
      },
      {
        label: 'ویژگی',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboAccountSpecification_Input',
      },
      {
        label: 'از مانده',
        type: 'text',
        disabled: false,
        sourceControlId: 'numFromBalance',
      },
      {
        label: 'تا مانده',
        type: 'text',
        disabled: false,
        sourceControlId: 'numToBalance',
      },
    ],
    columns: [],
    actions: [
      'گزارش',
      'راهنما (Ctrl+H)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
    ],
    stage: 'گزارش حساب های راکد',
  },
] as const satisfies readonly AccountingParityCapture[];
