import type { AccountingParityCapture } from './accounting-parity-definitions';

export const accountingParitySource1 = [
  {
    route: 'general-ledger/base-information/fiscal-years',
    title: 'دوره مالی',
    sourcePath: 'مالی / دفتر کل / اطلاعات پایه / معرفی دوره مالی',
    sourcePage: 'General/FiscalStructure/FiscalYearPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_txtTitle',
      },
      {
        label: 'عنوان به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_txtTitle_En',
      },
      {
        label: 'توضیحات',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_txtDescription',
      },
    ],
    columns: [],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'اطلاعات تفصیلی',
      'ایجاداطلاعات تفصیلی',
      'حذف اطلاعات تفصیلی',
      'دریافت اطلاع از تغییرات',
      'راهنما (Ctrl+H)',
    ],
    stage: 'دوره مالی',
  },
  {
    route: 'general-ledger/base-information/ledgers',
    title: 'دفتر کل',
    sourcePath: 'مالی / دفتر کل / اطلاعات پایه / معرفی دفتر کل',
    sourcePage: 'General/FiscalStructure/LedgerPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'کد',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtCode',
      },
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle',
      },
      {
        label: 'دفتر کل اصلی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkIsLeading',
      },
      {
        label: 'امکان صدور سند حسابداری در دفتر کل',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkIsFinancial',
      },
      {
        label: 'عنوان به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle_En',
      },
      {
        label: 'توضیحات',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDescription',
      },
      {
        label: 'فعال',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkState',
      },
    ],
    columns: ['سال مالی', 'تاریخ شروع', 'تاریخ پایان', 'سال مالی میلادی'],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'راهنما (Ctrl+H)',
      'افزودن (Insert)',
      'حذف (Delete)',
      'جستجو (Ctrl+F)',
    ],
    stage: 'دفتر کل',
  },
  {
    route: 'general-ledger/base-information/voucher-types',
    title: 'نوع سند',
    sourcePath: 'مالی / دفتر کل / اطلاعات پایه / تعریف نوع سند',
    sourcePage: 'Financial/VoucherManagement/VoucherTypePages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_txtTitle',
      },
      {
        label: 'عنوان به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_txtTitle_En',
      },
      {
        label: 'توضیحات',
        type: 'textarea',
        disabled: false,
        sourceControlId: 'fvwMain_txtDescription',
      },
    ],
    columns: [],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'راهنما (Ctrl+H)',
    ],
    stage: 'نوع سند',
  },
  {
    route: 'general-ledger/accounts/chart',
    title: 'تعریف ساختار حساب ها',
    sourcePath: 'مالی / دفتر کل / حساب ها / تعریف ساختار حساب ها',
    sourcePage: 'Financial/COAManagement/COAPages/COA.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'کد',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtCode',
      },
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle',
      },
      {
        label: 'نوع',
        type: 'text',
        disabled: false,
        sourceControlId: 'ctl15',
      },
    ],
    columns: ['کد', 'عنوان'],
    actions: [
      'جدید (Ctrl+N)',
      'حذف (Ctrl+D)',
      'مرتب سازی',
      'کد',
      'عنوان',
      'بارگذاری مجدد',
      'راهنما (Ctrl+H)',
      'گروه حساب جدید',
      'حساب کل جدید',
      'حساب معین جدید',
      'حذف',
    ],
    stage: 'تعریف ساختار حساب ها',
  },
  {
    route: 'general-ledger/accounts/detail-types',
    title: 'نوع تفصیلی',
    sourcePath: 'مالی / دفتر کل / حساب ها / تعریف نوع تفصیلی',
    sourcePage: 'Financial/COAManagement/DLTypePages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle',
      },
      {
        label: 'عنوان به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle_En',
      },
      {
        label: 'اولین کد پیش فرض',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDefaultCode',
      },
      {
        label: 'نوع تفصیلی پدر',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltParentDLTypeRef_Input',
      },
      {
        label: 'طول شماره طبقه بندی',
        type: 'text',
        disabled: false,
        sourceControlId: 'numCalssificationNumberLength',
      },
      {
        label: 'کنترل رابطه پدر فرزندی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkIsParentRequired',
      },
      {
        label: 'توضیحات',
        type: 'textarea',
        disabled: false,
        sourceControlId: 'txtDescription',
      },
    ],
    columns: [],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'راهنما (Ctrl+H)',
    ],
    stage: 'نوع تفصیلی',
  },
  {
    route: 'general-ledger/accounts/details',
    title: 'حساب تفصیلی',
    sourcePath: 'مالی / دفتر کل / حساب ها / تعریف حساب تفصیلی',
    sourcePage: 'Financial/COAManagement/DLPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'نوع تفصیلی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltDLType_Input',
      },
      {
        label: 'تفصیلی پدر',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltParentDL_Input',
      },
      {
        label: 'فعال',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkState',
      },
      {
        label: 'کد',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtCode',
      },
      {
        label: 'شماره طبقه بندی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtClassificationNumber',
      },
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltOwner_Input',
      },
      {
        label: 'عنوان به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle_En',
      },
      {
        label: 'ارز پیش فرض',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltCurrency_Input',
      },
      {
        label: 'توضیحات',
        type: 'textarea',
        disabled: false,
        sourceControlId: 'txtDescription',
      },
    ],
    columns: [],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'سایر عملیات (Ctrl+K)',
      'دریافت از Excel',
      'راهنما (Ctrl+H)',
    ],
    stage: 'حساب تفصیلی',
  },
  {
    route: 'general-ledger/documents/journals',
    title: 'سند حسابداری',
    sourcePath: 'مالی / دفتر کل / اسناد / صدور سند حسابداری',
    sourcePage: 'Financial/VoucherManagement/VoucherPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'شماره سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtNumber',
      },
      {
        label: 'تاریخ سند',
        type: 'date',
        disabled: false,
        sourceControlId: 'dtStartDate',
      },
      {
        label: 'شماره روزانه',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDailyNumber',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltVoucherType_Input',
      },
      {
        label: 'شماره فرعی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtAuxiliaryNumber',
      },
      {
        label: 'شماره عطف',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtSequence',
      },
      {
        label: 'صادر کننده',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtCreator',
      },
      {
        label: 'شرح',
        type: 'textarea',
        disabled: false,
        sourceControlId: 'txtDescription',
      },
      {
        label: 'شرح به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDescription_En',
      },
      {
        label: 'گروه حساب',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtAccountGroupTitle',
      },
      {
        label: 'حساب کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtGLTitle',
      },
      {
        label: 'حساب معین',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtSLTitle',
      },
      {
        label: 'عنوان سطح 4',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDLLevel4Title',
      },
      {
        label: 'عنوان سطح 5',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDLLevel5Title',
      },
      {
        label: 'عنوان سطح 6',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDLLevel6Title',
      },
      {
        label: 'وضعیت مالیاتی',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpTaxState_ComboBox_Input',
      },
      {
        label: 'کالا/خدمت',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpItemOrService_ComboBox_Input',
      },
      {
        label: 'خرید/فروش',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpPurchaseOrSale_ComboBox_Input',
      },
      {
        label: 'نوع معامله',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpTransactionType_ComboBox_Input',
      },
      {
        label: 'وضعیت مالیاتی',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpTaxHolding_ComboBox_Input',
      },
      {
        label: 'شخص/شرکت',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltParty_Input',
      },
      {
        label: 'مبلغ مالیات',
        type: 'text',
        disabled: false,
        sourceControlId: 'decTaxAmount_input',
      },
      {
        label: 'مبلغ عوارض',
        type: 'text',
        disabled: false,
        sourceControlId: 'decTollAmount_input',
      },
      {
        label: 'مالیات غیر قابل استرداد',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cbIsTaxPrepaymentUnrefundable',
      },
      {
        label: 'عوارض غیر قابل استرداد',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cbIsTollPrepaymentUnrefundable',
      },
    ],
    columns: [
      'وضعیت مالیاتی',
      'ردیف',
      'کد حساب معین',
      'سطح 4',
      'سطح 5',
      'سطح 6',
      'شرح',
      'بدهکار',
      'بستانکار',
      'شماره پیگیری',
      'تاریخ پیگیری',
      'شرح به زبان دوم',
    ],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'ذخیره یادداشت (Ctrl+Shift+S)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'نمایش فیلد های ارزی',
      'سایر عملیات (Ctrl+K)',
      'دریافت از Excel',
      'راهنما (Ctrl+H)',
      'افزودن (Insert)',
      'حذف (Delete)',
      'جستجو (Ctrl+F)',
      'جابجایی بدهکار و بستانکار (Ctrl+Shift+L)',
      'کپی (Ctrl+Shift+C)',
      'بریدن (Ctrl+Shift+X)',
      'درج (Ctrl+Shift+V)',
      'بالا (Ctrl+Shift+U)',
      'پایین (Ctrl+Shift+D)',
      'انتقال به ردیف مورد نظر',
      'لغو تغییرات (Ctrl+Shift+Z)',
      'اعمال مجدد تغییرات (Ctrl+Shift+R)',
      'تراز ارزی (Ctrl+Shift+Q)',
      'تراز ارزی سند',
      'گردش',
      'صدور اعلامیه',
      'صدور اعلامیه ارزی',
    ],
    stage: 'سند حسابداری',
  },
  {
    route: 'general-ledger/accounts/account-groups',
    title: 'گروهبندی حساب ها',
    sourcePath: 'مالی / دفتر کل / حساب ها / گروهبندی حساب ها',
    sourcePage: 'Financial/Grouping/COAGroupingPages/Main.aspx',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [],
    actions: ['گروه جدید (Ctrl+N)', 'حذف', 'بارگذاری مجدد (Ctrl+R)'],
    stage: 'گروهبندی حساب ها',
  },
  {
    route: 'general-ledger/accounts/mappings',
    title: 'نگاشت حساب',
    sourcePath: 'مالی / دفتر کل / حساب ها / نگاشت حساب',
    sourcePage: 'Financial/COAManagement/AccountMappingPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'معین دفتر کل اصلی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtLeadingSLCaption',
      },
      {
        label: 'ویژگی ارزی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkLeadingIsMultiCurrency',
      },
      {
        label: 'ویژگی پیگیری',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkLeadingIsTraceable',
      },
      {
        label: 'معین دفتر کل فرعی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtSecondarySLCaption',
      },
      {
        label: 'ویژگی ارزی',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkSecondaryIsMultiCurrency',
      },
      {
        label: 'ویژگی پیگیری',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'chkSecondaryIsTraceable',
      },
      {
        label: 'معین',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltSLSelector_Input',
      },
      {
        label: 'تفصیلی سطح 4',
        type: 'text',
        disabled: true,
        sourceControlId: 'sltDLLevel4_Input',
      },
      {
        label: 'تفصیلی سطح5',
        type: 'text',
        disabled: true,
        sourceControlId: 'sltDLLevel5_Input',
      },
      {
        label: 'تفصیلی سطح6',
        type: 'text',
        disabled: true,
        sourceControlId: 'sltDLLevel6_Input',
      },
    ],
    columns: [
      'عنوان-کد معین اصلی',
      'عنوان-کد معین فرعی',
      'تفصیلی سطح 4 دفتر کل فرعی',
      'تفصیلی سطح 5دفتر کل فرعی',
      'تفصیلی سطح 6دفتر کل فرعی',
      'شناسه',
      'کد',
      'عنوان',
      'نوع تفصیلی',
      'تفصیلی پدر',
      'کد تفصیلی پدر',
      'عنوان تفصیل پدر',
      'شماره طبقه بندی',
      'نوع تفصیلی 1',
      'وضعیت',
    ],
    actions: [
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'افزودن (Insert)',
      'حذف (Delete)',
      'جستجو (Ctrl+F)',
      'برای مرتب سازی اینجا کلیک کنید',
    ],
    stage: 'نگاشت حساب',
  },
  {
    route: 'general-ledger/accounts/detail-groups',
    title: 'گروهبندی حساب تفصیلی',
    sourcePath: 'مالی / دفتر کل / حساب ها / گروهبندی حساب تفصیلی',
    sourcePage: 'Financial/Grouping/DLGroupingPages/Main.aspx',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [],
    actions: ['گروه جدید (Ctrl+N)', 'حذف', 'بارگذاری مجدد (Ctrl+R)'],
    stage: 'گروهبندی حساب تفصیلی',
  },
  {
    route: 'general-ledger/accounts/detail-type-converter',
    title: 'مبدل نوع تفصیل',
    sourcePath: 'مالی / دفتر کل / حساب ها / ایجاد تبدیل نوع تفصیل',
    sourcePage: 'Financial/COAManagement/DLTypeConversionPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'نوع تفصیلی کاربر',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltUserDLType_Input',
      },
      {
        label: 'نوع تفصیلی سیستم',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltSystemDLType_Input',
      },
      {
        label: 'موجودیت',
        type: 'text',
        disabled: true,
        sourceControlId: 'sltEntity_Input',
      },
      {
        label: 'تاریخ',
        type: 'date',
        disabled: true,
        sourceControlId: 'dpDate_MaskedTextBox',
      },
      {
        label: 'توضیحات',
        type: 'textarea',
        disabled: false,
        sourceControlId: 'txtDescription',
      },
    ],
    columns: [],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
    ],
    stage: 'مبدل نوع تفصیل',
  },
  {
    route: 'general-ledger/documents/move',
    title: 'جابجایی اسناد',
    sourcePath: 'مالی / دفتر کل / اسناد / جابجایی اسناد',
    sourcePage: 'Financial/VoucherManagement/VoucherReorderPages/Reorder.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'تاریخ سند',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkDate_MaskedTextBox',
      },
    ],
    columns: [
      'شماره سند',
      'تاریخ سند',
      'وضعیت سند',
      'شرح',
      'شماره عطف',
      'شماره روزانه',
      'شماره فرعی',
    ],
    actions: [
      'ذخیره',
      'راهنما (Ctrl+H)',
      'افزودن (Insert)',
      'حذف (Delete)',
      'جستجو (Ctrl+F)',
      'بالا',
      'پایین',
    ],
    stage: 'جابجایی اسناد',
  },
  {
    route: 'general-ledger/documents/revaluation-templates',
    title: 'الگوی تسعیر ارز',
    sourcePath: 'مالی / دفتر کل / اسناد / الگوی تسعیر ارز',
    sourcePage: 'Financial/VoucherManagement/ConversionPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'کد',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtCode',
      },
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle',
      },
      {
        label: 'عنوان به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle_En',
      },
    ],
    columns: [
      'کد حساب معین',
      'سطح 4',
      'سطح 5',
      'سطح 6',
      'شناسه',
      'کد',
      'عنوان',
      'عنوان 1',
      'عنوان به زبان دوم',
    ],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'راهنما (Ctrl+H)',
      'افزودن (Insert)',
      'حذف (Delete)',
      'انتخاب',
      'جستجو (Ctrl+F)',
      'انتخاب دسته ای',
      'برای مرتب سازی اینجا کلیک کنید',
    ],
    stage: 'الگوی تسعیر ارز',
  },
  {
    route: 'general-ledger/documents/revaluation',
    title: 'تسعیر ارز',
    sourcePath: 'مالی / دفتر کل / اسناد / صدور سند تسعیر ارز',
    sourcePage: 'Financial/VoucherManagement/ConversionDocumentPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'ارز',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwConversion_sltCurrencyRef_Input',
      },
      {
        label: 'نرخ ارز',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwConversion_txtCurrencyRate_input',
      },
      {
        label: 'شرح',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwConversion_SgTextBox1',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'fvwConversion_dpkDate_MaskedTextBox',
      },
      {
        label: 'شماره فرعی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwConversion_txtAuxiliaryNumber',
      },
      {
        label: 'الگوی تسعیر',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwConversion_sltPattern_Input',
      },
      {
        label: 'شرح به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwConversion_SgTextBox2',
      },
    ],
    columns: [],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'راهنما (Ctrl+H)',
    ],
    stage: 'تسعیر ارز',
  },
  {
    route: 'general-ledger/documents/numbering',
    title: 'شماره گذاری اسناد',
    sourcePath: 'مالی / دفتر کل / اسناد / شماره گذاری اسناد',
    sourcePage:
      'Financial/VoucherManagement/VoucherNumberingPages/Numbering.aspx',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [],
    actions: [
      'شرح راهبر',
      'فیلتر',
      'فهرست اسناد',
      'پایان عملیات شماره گذاری',
      'ادامه',
    ],
    stage: 'شماره گذاری اسناد',
  },
  {
    route: 'general-ledger/documents/opening-deployment',
    title: 'سند حسابداری',
    sourcePath: 'مالی / دفتر کل / اسناد / صدور سند افتتاحیه استقرار',
    sourcePage:
      'Financial/VoucherManagement/VoucherPages/Edit.aspx?PageType=SetUp',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'شماره سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtNumber',
      },
      {
        label: 'تاریخ سند',
        type: 'date',
        disabled: false,
        sourceControlId: 'dtStartDate',
      },
      {
        label: 'شماره روزانه',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDailyNumber',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: true,
        sourceControlId: 'sltVoucherType_Input',
      },
      {
        label: 'شماره فرعی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtAuxiliaryNumber',
      },
      {
        label: 'شماره عطف',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtSequence',
      },
      {
        label: 'صادر کننده',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtCreator',
      },
      {
        label: 'شرح',
        type: 'textarea',
        disabled: false,
        sourceControlId: 'txtDescription',
      },
      {
        label: 'شرح به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDescription_En',
      },
      {
        label: 'گروه حساب',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtAccountGroupTitle',
      },
      {
        label: 'حساب کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtGLTitle',
      },
      {
        label: 'حساب معین',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtSLTitle',
      },
      {
        label: 'عنوان سطح 4',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDLLevel4Title',
      },
      {
        label: 'عنوان سطح 5',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDLLevel5Title',
      },
      {
        label: 'عنوان سطح 6',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtDLLevel6Title',
      },
      {
        label: 'وضعیت مالیاتی',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpTaxState_ComboBox_Input',
      },
      {
        label: 'کالا/خدمت',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpItemOrService_ComboBox_Input',
      },
      {
        label: 'خرید/فروش',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpPurchaseOrSale_ComboBox_Input',
      },
      {
        label: 'نوع معامله',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpTransactionType_ComboBox_Input',
      },
      {
        label: 'وضعیت مالیاتی',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpTaxHolding_ComboBox_Input',
      },
      {
        label: 'شخص/شرکت',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltParty_Input',
      },
      {
        label: 'مبلغ مالیات',
        type: 'text',
        disabled: false,
        sourceControlId: 'decTaxAmount_input',
      },
      {
        label: 'مبلغ عوارض',
        type: 'text',
        disabled: false,
        sourceControlId: 'decTollAmount_input',
      },
      {
        label: 'مالیات غیر قابل استرداد',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cbIsTaxPrepaymentUnrefundable',
      },
      {
        label: 'عوارض غیر قابل استرداد',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cbIsTollPrepaymentUnrefundable',
      },
    ],
    columns: [
      'وضعیت مالیاتی',
      'ردیف',
      'کد حساب معین',
      'سطح 4',
      'سطح 5',
      'سطح 6',
      'شرح',
      'بدهکار',
      'بستانکار',
      'شماره پیگیری',
      'تاریخ پیگیری',
      'شرح به زبان دوم',
    ],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'ذخیره یادداشت (Ctrl+Shift+S)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'نمایش فیلد های ارزی',
      'سایر عملیات (Ctrl+K)',
      'دریافت از Excel',
      'راهنما (Ctrl+H)',
      'اطلاعات اصلی',
      'یادداشت',
      'انتقال به ردیف مورد نظر',
      'تراز ارزی سند',
      'گردش',
      'معین',
      'سطح 4',
      'سطح 5',
      'سطح 6',
      'صدور اعلامیه',
      'صدور اعلامیه ارزی',
      'وضعیت مالیاتی',
      'ردیف',
      'کد حساب معین',
      'شرح',
      'بدهکار',
      'بستانکار',
      'شماره پیگیری',
      'تاریخ پیگیری',
      'شرح به زبان دوم',
      'افزودن (Insert)',
      'حذف (Delete)',
      'جستجو (Ctrl+F)',
      'جابجایی بدهکار و بستانکار (Ctrl+Shift+L)',
      'کپی (Ctrl+Shift+C)',
      'بریدن (Ctrl+Shift+X)',
      'درج (Ctrl+Shift+V)',
      'بالا (Ctrl+Shift+U)',
      'پایین (Ctrl+Shift+D)',
      'لغو تغییرات (Ctrl+Shift+Z)',
      'اعمال مجدد تغییرات (Ctrl+Shift+R)',
      'تراز ارزی (Ctrl+Shift+Q)',
    ],
    stage: 'سند حسابداری',
  },
  {
    route: 'general-ledger/documents/automatic-templates',
    title: 'الگوی سنداتوماتیک',
    sourcePath: 'مالی / دفتر کل / اسناد / تعریف الگوی سند اتوماتیک',
    sourcePage: 'Financial/VoucherManagement/AutomaticVoucherPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'کد',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_txtCode',
      },
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_txtTitle',
      },
      {
        label: 'عنوان به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_txtEnTitle',
      },
      {
        label: 'شرح پیش فرض',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_txtDescription',
      },
      {
        label: 'شرح پیش فرض به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_txtEnDescription',
      },
      {
        label: 'نمایش تفصیلی غیرفعال',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'fvwMain_chkShowDisableDLs',
      },
      {
        label: 'سطح تفصیلی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvwMain_lkpdlBasedOnLevelCount_ComboBox_Input',
      },
    ],
    columns: [
      'کد حساب معین',
      'سطح 4',
      'سطح 5',
      'سطح 6',
      'درصد',
      'انتخاب سطوح',
      'شناسه',
      'کد',
      'عنوان',
      'نوع تفصیلی',
      'تفصیلی پدر',
      'کد تفصیلی پدر',
      'عنوان تفصیل پدر',
      'شماره طبقه بندی',
      'نوع تفصیلی 1',
      'وضعیت',
    ],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'سایر عملیات (Ctrl+K)',
      'دریافت از Excel',
      'راهنما (Ctrl+H)',
      'اطلاعات اصلی',
      'یادداشت',
      'انتخاب',
      'افزودن (Insert)',
      'حذف (Delete)',
      'جستجو (Ctrl+F)',
      'انتخاب معین با سطوح مشخص',
      'انتخاب بر اساس کد تفصیلی',
      'اجرای فیلتر',
      'نمایش بدون فیلتر',
      'حذف همه شرطها',
      'بارگذاری',
      'حذف از لیست',
      'ذخیره فیلتر',
      'برای مرتب سازی اینجا کلیک کنید',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'جدید',
      'حذف',
      'بارگذاری مجدد',
      'ارسال به Excel',
      'عدم نمایش فیلتر',
      'انتخاب یک رکوردی',
      'ستونها',
      'شناسه',
      'کد',
      'عنوان',
      'نوع تفصیلی',
      'تفصیلی پدر',
      'کد تفصیلی پدر',
      'عنوان تفصیل پدر',
      'شماره طبقه بندی',
      'نوع تفصیلی 1',
      'وضعیت',
      'مدیریت فرم های چاپی ...',
    ],
    stage: 'الگوی سنداتوماتیک',
  },
] as const satisfies readonly AccountingParityCapture[];
