import type { AccountingParityCapture } from './accounting-parity-definitions';

export const accountingParitySource4 = [
  {
    route: 'tax-accounting/vat/tax-periods',
    title: 'دوره مالیاتی',
    sourcePath:
      'مالی / حسابداری مالیاتی / مالیات بر ارزش افزوده / معرفی دوره مالیاتی',
    sourcePage: 'Financial/VAT/TaxYearPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle',
      },
      {
        label: 'نحوه ارائه اطلاعات',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpGatheringType_ComboBox_Input',
      },
      {
        label: 'نحوه تجمیع اطلاعات',
        type: 'text',
        disabled: true,
        sourceControlId: 'sltMergePattern_Input',
      },
      {
        label: 'تاریخ شروع',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkStartDate_MaskedTextBox',
      },
      {
        label: 'تاریخ پایان',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkEndDate_MaskedTextBox',
      },
    ],
    columns: [],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'راهنما (Ctrl+H)',
      'اطلاعات اصلی',
      'یادداشت',
    ],
    stage: 'دوره مالیاتی',
  },
  {
    route: 'tax-accounting/vat/aggregation-methods',
    title: 'روش تجمیع اطلاعات خرید و فروش فصلی',
    sourcePath:
      'مالی / حسابداری مالیاتی / مالیات بر ارزش افزوده / معرفی روش تجمیع اطلاعات گزارش خرید و فروش فصلی',
    sourcePage: 'Financial/VAT/SeasonalReportMergePatternPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'شماره',
        type: 'text',
        disabled: false,
        sourceControlId: 'numNumber',
      },
      {
        label: 'عنوان',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTitle',
      },
      {
        label: 'تجمیع مودی مشمول ثبت نام در نظام مالیاتی حقیقی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'Buy_TaxPrayer_RealTaxPayerMergePattern',
      },
      {
        label: 'بر اساس طرف مقابل',
        type: 'checkbox',
        disabled: true,
        sourceControlId:
          'Buy_TaxPrayer_RealTaxPayerMergePattern_setting_ByCounterPartMerge',
      },
      {
        label: 'بر اساس حد نصاب معاملات کوچک',
        type: 'checkbox',
        disabled: true,
        sourceControlId:
          'Buy_TaxPrayer_RealTaxPayerMergePattern_setting_BySmallDealsMerge',
      },
      {
        label:
          'تجمیع مودی مشمول ثبت نام در نظام مالیاتی حقوقی براساس طرف مقابل',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'Buy_TaxPrayer_LegalTaxPayerMergePattern',
      },
      {
        label: 'تجمیع براساس نوع طرف معامله مشمولین ماده 81 ق.م.م',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'Buy_Dutiable_DutiablePartiesMergePattern',
      },
      {
        label: 'تجمیع کلیه طرف مقابل ها',
        type: 'checkbox',
        disabled: true,
        sourceControlId: 'Buy_Dutiable_DutiablePartiesMergePattern_setting',
      },
      {
        label:
          'تجمیع براساس نوع طرف معامله اشخاصی که ملزم به ثبت نام در نظام مالیاتی نیستند',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'Buy_NotRegistered_NotRegisteredPartiesMergePattern',
      },
      {
        label: 'تجمیع کلیه طرف مقابل ها',
        type: 'checkbox',
        disabled: true,
        sourceControlId:
          'Buy_NotRegistered_NotRegisteredPartiesMergePattern_setting',
      },
      {
        label: 'تجمیع مودی مشمول ثبت نام در نظام مالیاتی حقیقی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'Sale_TaxPrayer_RealTaxPayerMergePattern',
      },
      {
        label: 'بر اساس طرف مقابل',
        type: 'checkbox',
        disabled: true,
        sourceControlId:
          'Sale_TaxPrayer_RealTaxPayerMergePattern_setting_ByCounterPartMerge',
      },
      {
        label: 'بر اساس حد نصاب معاملات کوچک',
        type: 'checkbox',
        disabled: true,
        sourceControlId:
          'Sale_TaxPrayer_RealTaxPayerMergePattern_setting_BySmallDealsMerge',
      },
      {
        label:
          'تجمیع مودی مشمول ثبت نام در نظام مالیاتی حقوقی براساس طرف مقابل',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'Sale_TaxPrayer_LegalTaxPayerMergePattern',
      },
      {
        label: 'تجمیع براساس نوع طرف معامله مشمولین ماده 81 ق.م.م',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'Sale_Dutiable_DutiablePartiesMergePattern',
      },
      {
        label:
          'تجمیع براساس نوع طرف معامله اشخاصی که ملزم به ثبت نام در نظام مالیاتی نیستند',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'Sale_NotRegistered_NotRegisteredPartiesMergePattern',
      },
      {
        label:
          'تجمیع تمام قلم هایی که نوع طرف معامله مالیاتی آن ها مصرف کننده نهائی است',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'Sale_FinalConsumer_FinalConsumerMergePattern',
      },
    ],
    columns: [],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'راهنما (Ctrl+H)',
      'اطلاعات اصلی',
      'یادداشت',
    ],
    stage: 'روش تجمیع اطلاعات خرید و فروش فصلی',
  },
  {
    route: 'tax-accounting/vat/taxpayer-identity',
    title: 'اطلاعات پایه',
    sourcePath:
      'مالی / حسابداری مالیاتی / مالیات بر ارزش افزوده / تعریف اطلاعات هویتی مودی',
    sourcePage: 'Financial/VAT/VATBaseInformationPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'کد',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtNumber',
      },
      {
        label: 'کد اقتصادی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtEconomicCode',
      },
      {
        label: 'وضعیت عضویت',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpRegistrationStatus_ComboBox_Input',
      },
      {
        label: 'کد پستی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtZipCode',
      },
      {
        label: 'پیش شماره',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtLocalCode',
      },
      {
        label: 'منطقه جغرافیایی اداره مالیات',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltSeasonalZone_Input',
      },
      {
        label: 'شماره فرعی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtSecondaryNumber',
      },
      {
        label: 'فعال',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkState',
      },
      {
        label: 'شرکت',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltParty_Input',
      },
      {
        label: 'شماره ثبت',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtRegistrationCode',
      },
      {
        label: 'نام کاربری',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtUserName',
      },
      {
        label: 'آدرس',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtAddress',
      },
      {
        label: 'شماره تلفن',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtPhoneNumber',
      },
      {
        label: 'اداره کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'cmbAdministrationCode_Input',
      },
      {
        label: 'نام و نام خانوادگی مودی اصلی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtTaxPayer',
      },
      {
        label: 'نام شرکت',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtCompanyName',
      },
      {
        label: 'کدملی',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtNationalCode',
      },
      {
        label: 'آدرس شرکت',
        type: 'text',
        disabled: true,
        sourceControlId: 'sltPartyAddress_Input',
      },
      {
        label: 'نمابر',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtFaxNumber',
      },
      {
        label: 'شماره همراه',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtMobileNumber',
      },
      {
        label: 'شماره شعبه',
        type: 'text',
        disabled: false,
        sourceControlId: 'txtBranchNumber',
      },
      {
        label: 'تابعیت',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpNationality_ComboBox_Input',
      },
    ],
    columns: [],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'دریافت اطلاع از تغییرات',
      'راهنما (Ctrl+H)',
      'اطلاعات اصلی',
      'یادداشت',
    ],
    stage: 'اطلاعات پایه',
  },
  {
    route: 'tax-accounting/vat/quarterly-mappings',
    title: 'نگاشت اطلاعات فصلی',
    sourcePath:
      'مالی / حسابداری مالیاتی / مالیات بر ارزش افزوده / نگاشت اطلاعات فصلی',
    sourcePage: 'Financial/VAT/MappingPages/InformationMapping.aspx',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [
      'منطقه جغرافیایی راهکاران',
      'منطقه جغرافیایی اداره مالیات',
      'ارز راهکاران',
      'ارز اداره مالیات',
    ],
    actions: [
      'ذخیره',
      'راهنما (Ctrl+H)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'افزودن (Insert)',
      'حذف (Delete)',
      'جستجو (Ctrl+F)',
    ],
    stage: 'نگاشت اطلاعات فصلی',
  },
  {
    route: 'tax-accounting/vat/general-return',
    title: 'اظهارنامه عمومی',
    sourcePath:
      'مالی / حسابداری مالیاتی / مالیات بر ارزش افزوده / تهیه اظهارنامه عمومی',
    sourcePage: 'Financial/VAT/GeneralVATStatementPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'شماره اظهارنامه',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtCode',
      },
      {
        label: 'تاریخ اظهارنامه',
        type: 'date',
        disabled: false,
        sourceControlId: 'fvmMain_dpkDate_MaskedTextBox',
      },
      {
        label: 'دوره مالیاتی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_slctTaxYear_Input',
      },
      {
        label: 'تاریخ شروع',
        type: 'date',
        disabled: true,
        sourceControlId: 'fvmMain_dpkStartDate_MaskedTextBox',
      },
      {
        label: 'آخرین تغییر دهنده',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtCreator',
      },
      {
        label: 'تاریخ پایان',
        type: 'date',
        disabled: true,
        sourceControlId: 'fvmMain_dpkEndDate_MaskedTextBox',
      },
      {
        label: 'شماره اقتصادی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtEconomicNo',
      },
      {
        label: 'شماره فرعی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtAuxillaryNo',
      },
      {
        label: 'شماره شعبه',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtBranchNo',
      },
      {
        label: 'نام بنگاه',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtCompany',
      },
      {
        label: 'شماره ثبت',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtRegistrationCode',
      },
      {
        label: 'اداره کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtGeneralOffice',
      },
      {
        label: 'کد پستی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtZipCode',
      },
      {
        label: 'تلفن',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtPhone',
      },
      {
        label: 'نمابر',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtFax',
      },
      {
        label: 'جزییات آدرس',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtAddress',
      },
      {
        label: 'درخواست استرداد اضافه پرداختی وجود دارد',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'fvmMain_chkRequestRefund',
      },
      {
        label: 'جمع اقلام فروش',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumSaleAggregateItems_input',
      },
      {
        label: 'جمع اقلام مالیات برارزش افزوده پرداختنی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumVATPayableAggregateItems_input',
      },
      {
        label: 'جمع اقلام عوارض پرداختنی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumTollPayableAggregateItems_input',
      },
      {
        label: 'مبلغ نهایی فروش',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumSaleFinalAmount_input',
      },
      {
        label: 'مبلغ نهایی مالیات بر ارزش افزوده پرداختنی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumVATPayableFinalAmount_input',
      },
      {
        label: 'مبلغ نهایی عوارض پرداختنی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumTollPayableFinalAmount_input',
      },
      {
        label: 'جمع اقلام خرید',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumPurchaseAggregateItems_input',
      },
      {
        label: 'جمع اقلام پیش پرداخت مالیات برارزش افزوده',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumVATPrepaymentAggregateItems_input',
      },
      {
        label: 'جمع اقلام پیش پرداخت عوارض',
        type: 'text',
        disabled: false,
        sourceControlId:
          'fvmMain_decInputSumTollPrepaymentAggregateItems_input',
      },
      {
        label: 'مبلغ نهایی خرید',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumPurchaseFinalAmount_input',
      },
      {
        label: 'مبلغ نهایی پیش پرداخت مالیات بر ارزش افزوده',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumVATPrepaymentFinalAmount_input',
      },
      {
        label: 'مبلغ نهایی پیش پرداخت عوارض',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumTollPrepaymentFinalAmount_input',
      },
      {
        label: 'مبلغ اولیه مالیات پرداختی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumPaidTaxFirstAmount_input',
      },
      {
        label: 'مبلغ اولیه عوارض پرداختی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumPaidTollFirstAmount_input',
      },
      {
        label: 'مبلغ نهایی مالیات پرداختی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumPaidTaxFinalAmount_input',
      },
      {
        label: 'مبلغ نهایی عوارض پرداختی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumPaidTollFinalAmount_input',
      },
      {
        label: 'مبلغ اولیه مالیات',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumTaxFirstAmount_input',
      },
      {
        label: 'مبلغ اولیه عوارض',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumTollFirstAmount_input',
      },
      {
        label: 'مبلغ نهایی مالیات',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumTaxFinalAmount_input',
      },
      {
        label: 'مبلغ نهایی عوارض',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_decInputSumTollFinalAmount_input',
      },
    ],
    columns: [
      'نوع',
      'جمع اقلام فروش',
      'مبلغ نهایی فروش',
      'جمع اقلام مالیات بر ارزش افزوده پرداختنی',
      'مبلغ نهایی مالیات بر ارزش افزوده پرداختنی',
      'جمع اقلام عوارض پرداختنی',
      'مبلغ نهایی عوارض پرداختنی',
      'جمع اقلام خرید',
      'مبلغ نهایی خرید',
      'جمع اقلام پیش پرداخت مالیات بر ارزش افزوده',
      'مبلغ نهایی پیش پرداخت مالیات بر ارزش افزوده',
      'جمع اقلام پیش پرداخت عوارض',
      'مبلغ نهایی پیش پرداخت عوارض',
      'مبلغ اولیه مالیات پرداختی',
      'مبلغ نهایی مالیات پرداختی',
      'مبلغ اولیه عوارض پرداختی',
      'مبلغ نهایی عوارض پرداختی',
      'مبلغ اولیه مالیات',
      'مبلغ نهایی مالیات',
      'مبلغ اولیه عوارض',
      'مبلغ نهایی عوارض',
    ],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'چاپ اظهارنامه',
      'صدور اظهارنامه عمومی',
      'دریافت اطلاع از تغییرات',
      'راهنما (Ctrl+H)',
      'اطلاعات اصلی',
      'یادداشت',
    ],
    stage: 'اظهارنامه عمومی',
  },
  {
    route: 'tax-accounting/vat/pollution-return',
    title: 'اظهارنامه آلایندگی',
    sourcePath:
      'مالی / حسابداری مالیاتی / مالیات بر ارزش افزوده / تهیه اظهارنامه آلایندگی',
    sourcePage: 'Financial/VAT/ContaminationTollVATStatementPages/Edit.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'شماره اظهارنامه',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtCode',
      },
      {
        label: 'تاریخ اظهارنامه',
        type: 'date',
        disabled: false,
        sourceControlId: 'fvmMain_dpkDate_MaskedTextBox',
      },
      {
        label: 'دوره مالیاتی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_slctTaxYear_Input',
      },
      {
        label: 'تاریخ شروع',
        type: 'date',
        disabled: true,
        sourceControlId: 'fvmMain_dpkStartDate_MaskedTextBox',
      },
      {
        label: 'آخرین تغییر دهنده',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtCreator',
      },
      {
        label: 'تاریخ پایان',
        type: 'date',
        disabled: true,
        sourceControlId: 'fvmMain_dpkEndDate_MaskedTextBox',
      },
      {
        label: 'شماره اقتصادی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtEconomicNo',
      },
      {
        label: 'شماره فرعی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtAuxillaryNo',
      },
      {
        label: 'شماره شعبه',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtBranchNo',
      },
      {
        label: 'نام بنگاه',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtCompany',
      },
      {
        label: 'شماره ثبت',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtRegistrationCode',
      },
      {
        label: 'اداره کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtGeneralOffice',
      },
      {
        label: 'کد پستی',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtZipCode',
      },
      {
        label: 'تلفن',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtPhone',
      },
      {
        label: 'نمابر',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtFax',
      },
      {
        label: 'جزییات آدرس',
        type: 'text',
        disabled: false,
        sourceControlId: 'fvmMain_txtAddress',
      },
    ],
    columns: ['نوع', 'جمع مبالغ فروش', 'مبلغ نهایی فروش', 'درصد', 'مبلغ عوارض'],
    actions: [
      'جدید (Ctrl+B)',
      'باز کردن (Ctrl+L)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'ذخیره (Ctrl+S)',
      'ذخیره و جدید (Ctrl+Shift+B)',
      'ذخیره و بستن (Ctrl+Shift+F4)',
      'حذف و بستن',
      'حذف و جدید',
      'بارگذاری مجدد (Ctrl+R)',
      'چاپ',
      'فرم های چاپی را اضافه یا کم نمایید',
      'چاپ اظهارنامه',
      'صدور اظهارنامه آلایندگی',
      'دریافت اطلاع از تغییرات',
      'راهنما (Ctrl+H)',
      'اطلاعات اصلی',
      'یادداشت',
    ],
    stage: 'اظهارنامه آلایندگی',
  },
  {
    route: 'tax-accounting/vat/return-lines',
    title: 'گزارش ریز اقلام اظهارنامه',
    sourcePath:
      'مالی / حسابداری مالیاتی / مالیات بر ارزش افزوده / گزارش ریز اقلام اظهار نامه',
    sourcePage: 'Financial/VAT/ReportPages/DeclarationItemsDetail.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از دوره مالیاتی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltFromTaxYear_Input',
      },
      {
        label: 'تا دوره مالیاتی',
        type: 'text',
        disabled: false,
        sourceControlId: 'sltToTaxYear_Input',
      },
      {
        label: 'تجمیع مالیات و عوارض',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkTaxAndToll',
      },
      {
        label: 'اظهارنامه',
        type: 'text',
        disabled: false,
        sourceControlId: 'lkpVatStatement_ComboBox_Input',
      },
      {
        label: 'جزئیات اقلام',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboItemsDetail_Input',
      },
      {
        label: 'نام ماژول مبدا',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i0_chkTitleItemsDetail',
      },
      {
        label: 'نوع سند مبدا',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i1_chkTitleItemsDetail',
      },
      {
        label: 'شماره سند مبدا',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i2_chkTitleItemsDetail',
      },
      {
        label: 'تاریخ سند مبدا',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i3_chkTitleItemsDetail',
      },
      {
        label: 'شرح قلم',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i4_chkTitleItemsDetail',
      },
      {
        label: 'نام انبار',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i5_chkTitleItemsDetail',
      },
      {
        label: 'نام خریدار/ فروشنده',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i6_chkTitleItemsDetail',
      },
      {
        label: 'نام گمرک',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i7_chkTitleItemsDetail',
      },
      {
        label: 'شماره برگ گمرک',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i8_chkTitleItemsDetail',
      },
      {
        label: 'کد اقتصادی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i9_chkTitleItemsDetail',
      },
      {
        label: 'کد ملی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i10_chkTitleItemsDetail',
      },
      {
        label: 'شماره پروانه صادراتی',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i11_chkTitleItemsDetail',
      },
      {
        label: 'تاریخ صدور پروانه',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i12_chkTitleItemsDetail',
      },
      {
        label: 'کشور مقصد',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i13_chkTitleItemsDetail',
      },
      {
        label: 'شماره قرارداد',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i14_chkTitleItemsDetail',
      },
      {
        label: 'تاریخ قرار داد',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboItemsDetail_i15_chkTitleItemsDetail',
      },
      {
        label: 'تجمیع مبلغ قابل استرداد و غیر قابل استرداد',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkRefundableAndUnRefundable',
      },
      {
        label: 'اقلام خرید',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboPurchaseItems_Input',
      },
      {
        label: 'خرید کالاهای مشمول با پرداخت مالیات و عوارض',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboPurchaseItems_i0_chkTitlePurchaseItems',
      },
      {
        label: 'خرید خدمات مشمول با پرداخت مالیات وعوارض',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboPurchaseItems_i1_chkTitlePurchaseItems',
      },
      {
        label: 'خرید کالاهای معاف و مشمول بدون پرداخت مالیات و عوارض',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboPurchaseItems_i2_chkTitlePurchaseItems',
      },
      {
        label: 'خرید خدمات معاف و مشمول بدون پرداخت مالیات و عوارض',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboPurchaseItems_i3_chkTitlePurchaseItems',
      },
      {
        label: 'واردات کالاهای مشمول',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboPurchaseItems_i4_chkTitlePurchaseItems',
      },
      {
        label: 'واردات خدمات مشمول',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboPurchaseItems_i5_chkTitlePurchaseItems',
      },
      {
        label: 'واردات کالاهای معاف',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboPurchaseItems_i6_chkTitlePurchaseItems',
      },
      {
        label: 'واردات خدمات معاف',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboPurchaseItems_i7_chkTitlePurchaseItems',
      },
      {
        label: 'اقلام فروش',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboSaleItems_Input',
      },
      {
        label: 'فروش کالاهای مشمول',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboSaleItems_i0_chkTitleSaleItems',
      },
      {
        label: 'فروش خدمات مشمول',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboSaleItems_i1_chkTitleSaleItems',
      },
      {
        label: 'فروش کالاهای معاف',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboSaleItems_i2_chkTitleSaleItems',
      },
      {
        label: 'فروش خدمات معاف',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboSaleItems_i3_chkTitleSaleItems',
      },
      {
        label: 'صادرات کالا(مشمول و معاف)',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboSaleItems_i4_chkTitleSaleItems',
      },
      {
        label: 'صادرات خدمات(مشمول و معاف)',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'cboSaleItems_i5_chkTitleSaleItems',
      },
      {
        label: 'نمایش مغایرت',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'chkContrast',
      },
    ],
    columns: [],
    actions: [
      'گزارش',
      'راهنما (Ctrl+H) (Ctrl+H)',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
      'اجرای گزارش',
      'بازگشت به گزارش پدر',
      'صفحه اول',
      'صفحه قبلی',
      'صفحه بعد',
      'صفحه آخر',
      'ارسال',
      'XML',
      'CSV',
      'PDF',
      'MHTML',
      'IMAGE',
      'WORD',
      'EXCEL',
      'داده ها به Excel',
      'چاپ',
      'پیش نمایش چاپ',
      'Cancel',
    ],
    stage: 'گزارش ریز اقلام اظهارنامه',
  },
  {
    route: 'tax-accounting/vat/quarterly-sales-report',
    title: 'خطا',
    sourcePath:
      'مالی / حسابداری مالیاتی / مالیات بر ارزش افزوده / گزارش خرید و فروش فصلی',
    sourcePage: 'Financial/VAT/SeasonalReportPages/SeasonalReport.aspx',
    evidenceStatus: 'source-error',
    fields: [],
    columns: [],
    actions: ['مشاهده اطلاعات بیشتر'],
    stage: 'خطا',
  },
  {
    route: 'taxpayer-system/lists/batch-schedules',
    title: 'فهرست زمانبندی عملیات دسته جمعی',
    sourcePath:
      'مالی / ارتباط با سامانه مودیان مالیاتی / فهرست ها / زمانبندی عملیات دسته جمعی',
    sourcePage:
      'List.aspx?ComponentName=SystemGroup.General.TaxPayerManagement&EntityName=TaxPayerBillBatchJobScheduling',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [
      'شناسه',
      'عنوان',
      'وضعیت',
      'تاریخ اجرا',
      'فاصله اجرا (روز)',
      'عملیات دسته جمعی',
      'زمان آخرین اجرا',
      'موضوع صورتحساب',
      'نوع صورتحساب',
      'الگوی صورتحساب',
    ],
    actions: [
      'اجرای فیلتر',
      'نمایش بدون فیلتر',
      'حذف همه شرطها',
      'پاک کردن',
      'ویرایش',
      'بارگذاری',
      'حذف از لیست',
      'ذخیره فیلتر',
      'جدید (Ctrl+B)',
      'حذف (Ctrl+D)',
      'ویرایش (Ctrl+L)',
      'بارگذاری مجدد( Ctrl+R)',
      'دریافت اطلاع از تغییرات',
      'ارسال به Excel',
      'عدم نمایش فیلتر( Ctrl+F)',
      'انتخاب چند رکوردی( Ctrl+M)',
      'ستونها',
      'شناسه',
      'عنوان',
      'وضعیت',
      'تاریخ اجرا',
      'فاصله اجرا (روز)',
      'عملیات دسته جمعی',
      'زمان آخرین اجرا',
      'موضوع صورتحساب',
      'نوع صورتحساب',
      'الگوی صورتحساب',
      'محاسبه تعداد رکوردها و صفحات فهرست( Ctrl+K)',
      'مدیریت فرم های چاپی ...',
      'برای مرتب سازی اینجا کلیک کنید',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'جدید',
      'حذف',
      'بارگذاری مجدد',
      'عدم نمایش فیلتر',
      'انتخاب چند رکوردی',
      'تغییر وضعیت',
      'چاپ',
    ],
    stage: 'فهرست زمانبندی عملیات دسته جمعی',
  },
  {
    route: 'taxpayer-system/lists/invoices',
    title: 'فهرست صورتحساب',
    sourcePath:
      'مالی / ارتباط با سامانه مودیان مالیاتی / فهرست ها / لیست صورتحساب ها',
    sourcePage:
      'List.aspx?ComponentName=SystemGroup.General.TaxPayerManagement&EntityName=TaxPayerBill',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [
      'شناسه',
      'شناسه یکتای صورتحساب',
      'شناسه مرجع صورتحساب',
      'شماره سریال صورت حساب',
      'موضوع صورتحساب',
      'دلیل ایجاد صورتحساب',
      'شناسه لاگ',
      'وضعیت',
      'نوع موجودیت',
      'وضعیت در کارپوشه مودیان',
      'دلیل رد صورتحساب',
      'دارای مبلغ منفی',
      'شناسه موجودیت',
      'تاریخ موجودیت',
      'متن خطا',
      'شماره',
      'نوع صورت حساب',
      'الگوی صورت حساب',
      'کد اقتصادی فروشنده',
      'کد شعبه خریدار',
      'نوع شخص خریدار',
      'کد مشتری',
      'عنوان مشتری',
      'کد/شناسه ملی/کدفراگیر/شناسه مشارکت مدنی',
      'شماره اقتصادی',
      'شماره پروانه گمركی فروشنده',
      'كد گمرک محل اظهار',
      'مجموع مبلغ قبل از كسر تخفیف',
      'مجموع تخفیفات',
      'مجموع مبلغ پس از كسر تخفیف',
      'مجموع مالیات بر ارزش افزوده',
      'مجموع سایر مالیات، عوارض و وجوه قانونی',
      'مجموع صورتحساب',
      'روش تسویه',
      'مجموع مبلغ پرداختی نقدی',
      'مبلغ پرداختی نقدی (مجموع مبلغ نقدی اقلام از پرداخت )',
      'مجموع سهم نقدی مالیات بر ارزش افزوده از پرداخت',
      'مجموع سهم نقدی سایر مالیات و عوارض از پرداخت',
      'مجموع مبلغ نسیه کل',
      'مجموع مبلغ نسیه اقلام',
      'مجموع مبلغ نسیه مالیات بر ارزش افزوده',
      'مجموع مبلغ نسیه سایر مالیات و عوارض',
      'ورژن نرم افزار ارسال صورتحساب',
    ],
    actions: [
      'اجرای فیلتر',
      'نمایش بدون فیلتر',
      'حذف همه شرطها',
      'پاک کردن',
      'ویرایش',
      'بارگذاری',
      'حذف از لیست',
      'ذخیره فیلتر',
      'حذف (Ctrl+D)',
      'ویرایش (Ctrl+L)',
      'تایید همه / آماده سازی ارسال همه',
      'تایید / آماده سازی ارسال',
      'ارسال همه',
      'ارسال',
      'ارسال مجدد همه',
      'ارسال مجدد',
      'برگشت از تایید همه',
      'بازگشت از تایید',
      'حذف همه',
      'استعلام همه',
      'استعلام',
      'تنظیمات لحظه جمع آوری صورتحساب',
      'اطلاعات پرداخت صورتحساب',
      'تایید صورتحساب در کارپوشه مودیان',
      'رد صورتحساب در کارپوشه مودیان',
      'بازگرداندن وضعیت صورتحساب در کارپوشه مودیان به حالت پیش فرض',
      'تایید صورتحساب ها در کارپوشه به صورت دسته جمعی',
      'رد صورتحساب ها در کارپوشه به صورت دسته جمعی',
      'بازگرداندن وضعیت صورتحساب ها در کارپوشه به حالت پیش فرض به صورت دسته جمعی',
      'تغییر تاریخ صورتحساب',
      'بارگذاری مجدد( Ctrl+R)',
      'دریافت اطلاع از تغییرات',
      'ارسال به Excel',
      'عدم نمایش فیلتر( Ctrl+F)',
      'انتخاب چند رکوردی( Ctrl+M)',
      'ستونها',
      'شناسه',
      'شناسه یکتای صورتحساب',
      'شناسه مرجع صورتحساب',
      'شماره سریال صورت حساب',
      'موضوع صورتحساب',
      'دلیل ایجاد صورتحساب',
      'شناسه لاگ',
      'وضعیت',
      'نوع موجودیت',
      'وضعیت در کارپوشه مودیان',
      'دلیل رد صورتحساب',
      'دارای مبلغ منفی',
      'شناسه موجودیت',
      'تاریخ موجودیت',
      'متن خطا',
      'شماره',
      'نوع صورت حساب',
      'الگوی صورت حساب',
      'کد اقتصادی فروشنده',
      'کد شعبه خریدار',
      'نوع شخص خریدار',
      'کد مشتری',
      'عنوان مشتری',
      'کد/شناسه ملی/کدفراگیر/شناسه مشارکت مدنی',
      'شماره اقتصادی',
      'شماره پروانه گمركی فروشنده',
      'كد گمرک محل اظهار',
      'مجموع مبلغ قبل از كسر تخفیف',
      'مجموع تخفیفات',
      'مجموع مبلغ پس از كسر تخفیف',
      'مجموع مالیات بر ارزش افزوده',
      'مجموع سایر مالیات، عوارض و وجوه قانونی',
      'مجموع صورتحساب',
      'روش تسویه',
      'مجموع مبلغ پرداختی نقدی',
      'مبلغ پرداختی نقدی (مجموع مبلغ نقدی اقلام از پرداخت )',
      'مجموع سهم نقدی مالیات بر ارزش افزوده از پرداخت',
      'مجموع سهم نقدی سایر مالیات و عوارض از پرداخت',
      'مجموع مبلغ نسیه کل',
      'مجموع مبلغ نسیه اقلام',
      'مجموع مبلغ نسیه مالیات بر ارزش افزوده',
      'مجموع مبلغ نسیه سایر مالیات و عوارض',
      'ورژن نرم افزار ارسال صورتحساب',
      'محاسبه تعداد رکوردها و صفحات فهرست( Ctrl+K)',
      'مدیریت فرم های چاپی ...',
      'برای مرتب سازی اینجا کلیک کنید',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'حذف',
      'سایر عملیات',
      'عملیات دسته جمعی',
      'بارگذاری مجدد',
      'عدم نمایش فیلتر',
      'انتخاب چند رکوردی',
      'چاپ',
    ],
    stage: 'فهرست صورتحساب',
  },
  {
    route: 'taxpayer-system/lists/settings',
    title: 'فهرست تنظیمات ارسال صورت حساب',
    sourcePath:
      'مالی / ارتباط با سامانه مودیان مالیاتی / فهرست ها / لیست تنظیمات سامانه مالیاتی',
    sourcePage:
      'List.aspx?ComponentName=SystemGroup.General.TaxPayerManagement&EntityName=TaxPaymentProfile',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: ['شناسه', 'عنوان', 'نوع ارسال صورت حساب'],
    actions: [
      'اجرای فیلتر',
      'نمایش بدون فیلتر',
      'حذف همه شرطها',
      'پاک کردن',
      'ویرایش',
      'بارگذاری',
      'حذف از لیست',
      'ذخیره فیلتر',
      'جدید (Ctrl+B)',
      'حذف (Ctrl+D)',
      'ویرایش (Ctrl+L)',
      'بارگذاری مجدد( Ctrl+R)',
      'دریافت اطلاع از تغییرات',
      'ارسال به Excel',
      'عدم نمایش فیلتر( Ctrl+F)',
      'انتخاب چند رکوردی( Ctrl+M)',
      'ستونها',
      'شناسه',
      'عنوان',
      'نوع ارسال صورت حساب',
      'محاسبه تعداد رکوردها و صفحات فهرست( Ctrl+K)',
      'مدیریت فرم های چاپی ...',
      'برای مرتب سازی اینجا کلیک کنید',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'جدید',
      'حذف',
      'بارگذاری مجدد',
      'عدم نمایش فیلتر',
      'انتخاب چند رکوردی',
      'چاپ',
    ],
    stage: 'فهرست تنظیمات ارسال صورت حساب',
  },
  {
    route: 'taxpayer-system/lists/cancellations',
    title: 'فهرست صورتحساب ابطال',
    sourcePath:
      'مالی / ارتباط با سامانه مودیان مالیاتی / فهرست ها / فهرست صورتحساب‌های ابطال',
    sourcePage:
      'List.aspx?ComponentName=SystemGroup.General.TaxPayerManagement&EntityName=TaxPayerCancellationBill',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [
      'شناسه',
      'شماره مالیاتی ابطال',
      'تاریخ ابطال',
      'وضعیت',
      'شماره مالیاتی مرجع',
      'تاریخ مرجع',
      'موضوع مرجع',
      'شناسه موجودیت',
      'متن خطا',
    ],
    actions: [
      'اجرای فیلتر',
      'نمایش بدون فیلتر',
      'حذف همه شرطها',
      'پاک کردن',
      'ویرایش',
      'بارگذاری',
      'حذف از لیست',
      'ذخیره فیلتر',
      'جدید (Ctrl+B)',
      'حذف (Ctrl+D)',
      'ویرایش (Ctrl+L)',
      'تایید همه / آماده سازی ارسال همه',
      'ارسال همه',
      'استعلام مجدد صورتحساب های خطادار',
      'بارگذاری مجدد( Ctrl+R)',
      'دریافت اطلاع از تغییرات',
      'ارسال به Excel',
      'عدم نمایش فیلتر( Ctrl+F)',
      'انتخاب چند رکوردی( Ctrl+M)',
      'ستونها',
      'شناسه',
      'شماره مالیاتی ابطال',
      'تاریخ ابطال',
      'وضعیت',
      'شماره مالیاتی مرجع',
      'تاریخ مرجع',
      'موضوع مرجع',
      'شناسه موجودیت',
      'متن خطا',
      'محاسبه تعداد رکوردها و صفحات فهرست( Ctrl+K)',
      'مدیریت فرم های چاپی ...',
      'برای مرتب سازی اینجا کلیک کنید',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'جدید',
      'حذف',
      'سایر عملیات',
      'عملیات دسته جمعی',
      'بارگذاری مجدد',
      'عدم نمایش فیلتر',
      'انتخاب چند رکوردی',
      'چاپ',
    ],
    stage: 'فهرست صورتحساب ابطال',
  },
  {
    route: 'general-ledger/documents/automatic-runs',
    title: 'سند اتوماتیک',
    sourcePath: 'مالی / دفتر کل / اسناد / صدور سند اتوماتیک',
    sourcePage:
      'Financial/VoucherManagement/AutomaticVoucherPages/AutomaticVoucherWizard.aspx',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [],
    actions: [
      'شرح راهبر',
      'انتخاب الگوی سند اتوماتیک',
      'پیش نمایش سند',
      'پایان عملیات',
      'ادامه',
    ],
    stage: 'سند اتوماتیک',
  },
  {
    route: 'general-ledger/documents/automatic-runs',
    title: 'سند اتوماتیک',
    sourcePath: 'مالی / دفتر کل / اسناد / صدور سند اتوماتیک',
    sourcePage:
      'Financial/VoucherManagement/AutomaticVoucherPages/AutomaticVoucherWizard.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'انتخاب الگو',
        type: 'text',
        disabled: false,
        sourceControlId: 'wzrAutomaticVoucher_slcPattern_Input',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'wzrAutomaticVoucher_dpkToDate_MaskedTextBox',
      },
      {
        label: 'شرح',
        type: 'text',
        disabled: false,
        sourceControlId: 'wzrAutomaticVoucher_txtDescription',
      },
      {
        label: 'شماره پیگیری',
        type: 'text',
        disabled: false,
        sourceControlId: 'wzrAutomaticVoucher_txtFollowUpNumber',
      },
      {
        label: 'نوع سند',
        type: 'text',
        disabled: false,
        sourceControlId: 'wzrAutomaticVoucher_cboVoucherType_Input',
      },
      {
        label: 'پیش نمایش سند',
        type: 'checkbox',
        disabled: false,
        sourceControlId: 'wzrAutomaticVoucher_chkVoucherPreview',
      },
      {
        label: 'شماره فرعی',
        type: 'text',
        disabled: false,
        sourceControlId: 'wzrAutomaticVoucher_txtAuxillaryNo',
      },
      {
        label: 'تاریخ سند',
        type: 'date',
        disabled: false,
        sourceControlId: 'wzrAutomaticVoucher_dpkVoucherDate_MaskedTextBox',
      },
      {
        label: 'شرح به زبان دوم',
        type: 'text',
        disabled: false,
        sourceControlId: 'wzrAutomaticVoucher_txtDescription_En',
      },
      {
        label: 'تاریخ پیگیری',
        type: 'date',
        disabled: false,
        sourceControlId: 'wzrAutomaticVoucher_dpkFollowupDate_MaskedTextBox',
      },
    ],
    columns: [],
    actions: [
      'شرح راهبر',
      'انتخاب الگوی سند اتوماتیک',
      'پیش نمایش سند',
      'پایان عملیات',
      'ادامه',
      'بازگشت',
      'انصراف',
      'پاک کردن',
      'ویرایش',
      'محدود کردن جستجو',
      'برداشتن محدودیت جستجو',
    ],
    stage: 'انتخاب الگو',
  },
  {
    route: 'general-ledger/documents/posting',
    title: 'قطعی کردن اسناد',
    sourcePath: 'مالی / دفتر کل / اسناد / قطعی کردن اسناد',
    sourcePage:
      'Financial/VoucherManagement/FinalizeVoucherPages/FinalizeVoucher.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'از تاریخ',
        type: 'date',
        disabled: true,
        sourceControlId: 'wzrApproving_dpkStartDate_MaskedTextBox',
      },
      {
        label: 'تا تاریخ',
        type: 'date',
        disabled: false,
        sourceControlId: 'wzrApproving_dpkEndDate_MaskedTextBox',
      },
    ],
    columns: [],
    actions: [
      'شرح راهبر',
      'تعیین وضعیت فیلترها',
      'فهرست اسناد',
      'سند خلاف ماهیت',
      'پایان عملیات قطعی کردن',
      'ادامه',
      'بازگشت',
      'انصراف',
    ],
    stage: 'مرحله دوم',
  },
  {
    route: 'general-ledger/year-end/closing',
    title: 'خطای پیش‌شرط',
    sourcePath: 'مالی / دفتر کل / عملیات پایان سال / صدور سند بستن حساب ها',
    sourcePage:
      'Financial/VoucherManagement/ClosingPages/ClosingVoucherWizard.aspx',
    evidenceStatus: 'observed-layout',
    fields: [],
    columns: [],
    actions: [],
    blocker: 'در دوره مالی جاری سند قطعی وجود ندارد',
    stage: 'پیش‌شرط',
  },
  {
    route: 'general-ledger/documents/review',
    title: 'بررسی اسناد',
    sourcePath: 'مالی / دفتر کل / اسناد / بررسی',
    sourcePage:
      'Financial/VoucherManagement/ReviewVoucherPages/ReviewVoucher.aspx',
    evidenceStatus: 'observed-layout',
    fields: [
      {
        label: 'شعبه',
        type: 'text',
        disabled: false,
        sourceControlId: 'cboBranches_Input',
      },
      {
        label: 'گروه حساب',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtAccountGroupTitle',
      },
      {
        label: 'حساب کل',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtGLTitle',
      },
      {
        label: 'حساب معین',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtSLTitle',
      },
      {
        label: 'عنوان سطح 4',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel4Title',
      },
      {
        label: 'عنوان سطح 5',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel5Title',
      },
      {
        label: 'عنوان سطح 6',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel6Title',
      },
      {
        label: 'عنوان سطح 10',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel10Title',
      },
      {
        label: 'عنوان سطح 11',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel11Title',
      },
      {
        label: 'عنوان سطح 12',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel12Title',
      },
      {
        label: 'عنوان سطح 13',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel13Title',
      },
      {
        label: 'عنوان سطح 14',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel14Title',
      },
      {
        label: 'عنوان سطح 15',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel15Title',
      },
      {
        label: 'عنوان سطح 16',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel16Title',
      },
      {
        label: 'عنوان سطح 17',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel17Title',
      },
      {
        label: 'عنوان سطح 18',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel18Title',
      },
      {
        label: 'عنوان سطح 19',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel19Title',
      },
      {
        label: 'عنوان سطح 20',
        type: 'text',
        disabled: false,
        sourceControlId: 'UCPreviewVoucher1_ucVoucherView_txtDLLevel20Title',
      },
      {
        label: 'تاریخ بررسی',
        type: 'date',
        disabled: false,
        sourceControlId: 'dpkReviewDate_MaskedTextBox',
      },
      {
        label: 'شرح',
        type: 'textarea',
        disabled: false,
        sourceControlId: 'txtDescription',
      },
    ],
    columns: [
      'شناسه',
      'شماره سند',
      'تاریخ',
      'شماره بررسی',
      'تاریخ بررسی',
      'وضعیت',
      'نوع سند',
      'شرح',
      'شماره عطف',
      'شماره فرعی',
      'شماره روزانه',
      'مبلغ سند',
      'صادر کننده',
      'پیوست',
      'شماره ردیف',
      'عنوان حساب معین',
      'کد حساب معین',
      'سطح 4',
      'عنوان سطح 4',
      'سطح 5',
      'عنوان سطح 5',
      'سطح 6',
      'عنوان سطح 6',
      'بدهکار',
      'بستانکار',
      'شماره پیگیری',
      'تاریخ پیگیری',
      'بدهکار 1',
      'بستانکار 1',
      'حساب کل',
      'گروه حساب',
    ],
    actions: [
      'بررسی',
      'بررسی اسناد انتخابی',
      'بررسی کلیه اسناد',
      'لغو بررسی',
      'لغو بررسی اسناد انتخابی',
      'لغو بررسی کلیه اسناد',
      'نمایش سند',
      'بارگذاری مجدد (Ctrl+R)',
      'راهنما (Ctrl+H)',
      'اجرای فیلتر',
      'نمایش بدون فیلتر',
      'حذف همه شرطها',
      'پاک کردن',
      'ویرایش',
      'بارگذاری',
      'حذف از لیست',
      'ذخیره فیلتر',
      'برای مرتب سازی اینجا کلیک کنید',
      'جدید (Ctrl+B)',
      'حذف (Ctrl+D)',
      'ویرایش (Ctrl+L)',
      'چاپ سند',
      'چاپ مستقیم سند',
      'چاپ گروهی',
      'کپی سند',
      'بارگذاری مجدد( Ctrl+R)',
      'ارسال به Excel',
      'عدم نمایش فیلتر( Ctrl+F)',
      'انتخاب یک رکوردی( Ctrl+M)',
      'ستونها',
      'شناسه',
      'شماره سند',
      'تاریخ',
      'شماره بررسی',
      'تاریخ بررسی',
      'وضعیت',
      'نوع سند',
      'شرح',
      'شماره عطف',
      'شماره فرعی',
      'شماره روزانه',
      'مبلغ سند',
      'صادر کننده',
      'پیوست',
      'محاسبه تعداد رکوردها و صفحات فهرست( Ctrl+K)',
      'دریافت از Excel',
      'مدیریت فرم های چاپی ...',
      'ویرایش سند',
      'بزرگتر از',
      'کوچکتر از',
      'بزرگتر یا مساوی',
      'کوچکتر یا مساوی',
      'مشخصات سند',
      'تاریخچه تغییر وضعیت',
      'بارگذاری مجدد',
      'عدم نمایش فیلتر',
      'شماره ردیف',
      'عنوان حساب معین',
      'کد حساب معین',
      'سطح 4',
      'عنوان سطح 4',
      'سطح 5',
      'عنوان سطح 5',
      'سطح 6',
      'عنوان سطح 6',
      'بدهکار',
      'بستانکار',
      'ارز',
      'نرخ ارز',
      'ارز مبنا',
      'نرخ تبدیل ارز',
      'مبلغ ارز',
      'مبلغ به ارز مبنا',
      'شماره پیگیری',
      'تاریخ پیگیری',
      'بدهکار 1',
      'بستانکار 1',
      'حساب کل',
      'گروه حساب',
      'چاپ',
    ],
    stage: 'بررسی اسناد',
  },
] as const satisfies readonly AccountingParityCapture[];
