import type { SalesContractOutputV1 } from '@rubi/contracts';
export const printFixture: SalesContractOutputV1 = {
  version: 1,
  generatedAt: '2026-09-07T09:00:00Z',
  customer: {
    kind: 'person',
    address: 'نشانی آزمایشی - بدون اطلاعات مشتری واقعی',
  },
  ownerName: 'کارشناس نمونه',
  company: {
    id: 'company',
    code: 'NIYAYESH_SEIR_SAHAR',
    persianName: 'شرکت نمونه - فقط آزمایش',
    latinName: 'SAMPLE AGENCY',
    website: '',
    brandingVersion: 1,
  },
  contract: {
    id: 'contract',
    contractNumber: 'SAMPLE-001',
    customerId: 'buyer',
    customerNameSnapshot: 'مشتری نمونه',
    passengerNames: ['مسافر نمونه اول', 'مسافر نمونه دوم'],
    ownerUserId: 'owner',
    assignedUserId: null,
    branchId: 'branch',
    originId: 'tehran',
    destinationId: 'antalya',
    departureDate: '2026-09-19',
    returnNotBefore: '2026-09-26',
    services: ['FLIGHT', 'HOTEL', 'VISA', 'TRANSFER'],
    status: 'SENT_TO_RESERVATIONS',
    settlementStatus: 'PARTIALLY_SETTLED',
    reservationStatus: 'QUEUED',
    balances: [
      {
        amount: '123456789.25',
        currencyCode: 'IRR',
        confirmedPaid: '20000000',
        pendingFinance: '40000000',
        outstanding: '103456789.25',
      },
      {
        amount: '900.50',
        currencyCode: 'USD',
        confirmedPaid: '0',
        pendingFinance: '0',
        outstanding: '900.50',
      },
    ],
    version: 3,
    createdAt: '2026-09-07T08:30:00Z',
    updatedAt: '2026-09-07T09:00:00Z',
    tripType: 'ROUND_TRIP',
    payerCustomerId: 'buyer',
    servicesDetail: [
      { clientKey: 'flight-out', kind: 'FLIGHT', titleSnapshot: 'بلیط رفت' },
      {
        clientKey: 'flight-return',
        kind: 'FLIGHT',
        titleSnapshot: 'بلیط برگشت',
        metadata: { businessOutput: true },
      },
      { clientKey: 'hotel', kind: 'HOTEL', titleSnapshot: 'هتل' },
      { clientKey: 'visa', kind: 'VISA', titleSnapshot: 'ویزا' },
      {
        clientKey: 'transfer-out',
        kind: 'TRANSFER',
        titleSnapshot: 'ترانسفر رفت',
        metadata: { included: true },
      },
    ],
    passengersDetail: [
      {
        id: 'one',
        customerId: 'person1',
        displayNameSnapshot: 'مسافر نمونه اول',
        birthDate: '1990-01-01',
        serviceClientKeys: ['flight-out', 'flight-return', 'hotel', 'visa'],
        ageCategory: 'ADT',
      },
      {
        id: 'two',
        customerId: 'person2',
        displayNameSnapshot: 'مسافر نمونه دوم',
        birthDate: '2018-01-01',
        serviceClientKeys: ['flight-out', 'flight-return', 'hotel'],
        ageCategory: 'CHD',
      },
    ],
    ticketSelections: [
      {
        serviceClientKey: 'flight-out',
        direction: 'OUTBOUND',
        offerId: 'offer1',
        originId: 'tehran',
        destinationId: 'antalya',
        departureAt: '2026-09-19T07:00:00Z',
        arrivalAt: '2026-09-19T10:00:00Z',
        carrierNameSnapshot: 'ایرلاین نمونه',
        serviceNumberSnapshot: 'TEST-01',
        cabinClassCode: 'ECONOMY',
        quotedPrice: { amount: '999999999', currencyCode: 'IRR' },
      },
      {
        serviceClientKey: 'flight-return',
        direction: 'RETURN',
        offerId: 'offer2',
        originId: 'antalya',
        destinationId: 'tehran',
        departureAt: '2026-09-26T07:00:00Z',
        arrivalAt: '2026-09-26T10:00:00Z',
        carrierNameSnapshot: 'ایرلاین نمونه',
        serviceNumberSnapshot: 'TEST-02',
        cabinClassCode: 'ECONOMY',
      },
    ],
    hotelSelection: {
      serviceClientKey: 'hotel',
      hotelId: 'hotel-id',
      hotelNameSnapshot: 'هتل نمونه',
      cityId: 'antalya',
      checkInDate: '2026-09-20',
      checkOutDate: '2026-09-25',
      roomCount: 1,
      roomTypeId: 'double',
      mealServiceId: 'meal',
      occupancy: 2,
      inventoryStatus: 'NEEDS_RESERVATION_CONFIRMATION',
    },
    priceComponents: [
      {
        type: 'BASE',
        title: 'قیمت توافقی',
        amount: '123456789.25',
        currencyCode: 'IRR',
      },
    ],
    payments: [],
    fxSnapshot: null,
    pricingNotes: null,
  },
};
export const printReferences = {
  names: {
    tehran: 'تهران',
    antalya: 'آنتالیا',
    double: 'دوتخته',
    meal: 'UALL',
  },
  hotelGrade: '۵',
};
