export const masterDataResourceKeys = [
  'countries',
  'regions',
  'cities',
  'airports',
  'terminals',
  'currencies',
  'exchange-rates',
  'banks',
  'bank-branches',
  'payment-methods',
  'insurers',
  'insurance-plans',
  'insurance-coverages',
  'airlines',
  'aircraft-types',
  'cabin-classes',
  'baggage-rules',
  'manifest-templates',
  'rail-companies',
  'train-types',
  'bus-companies',
  'bus-types',
  'hotels',
  'hotel-chains',
  'room-types',
  'meal-services',
  'facilities',
  'composite-hotels',
  'organizations',
  'suppliers',
  'brokers',
  'travel-services',
  'organization-contacts',
  'leaders',
  'acquaintance-methods',
  'lead-sources',
  'sales-channels',
  'lost-reasons',
  'customer-types',
  'tags',
  'campaign-types',
] as const;

export type MasterDataResourceKey = (typeof masterDataResourceKeys)[number];
export type MasterDataFieldType =
  'text' | 'number' | 'datetime-local' | 'select';

export interface MasterDataFieldDefinition {
  key: string;
  label: string;
  type: MasterDataFieldType;
  placeholder: string;
  required?: boolean;
  hint?: string;
  options?: readonly { value: string; label: string }[];
}

export interface MasterDataCatalogItem {
  key: MasterDataResourceKey;
  label: string;
  singularLabel: string;
  group:
    | 'جغرافیا'
    | 'مالی'
    | 'اقامت'
    | 'حمل‌ونقل'
    | 'بیمه'
    | 'خدمات سفر'
    | 'سازمان‌ها'
    | 'فروش';
  description: string;
  fields: readonly MasterDataFieldDefinition[];
  preview: Readonly<Record<string, string>>;
}

const nameField: MasterDataFieldDefinition = {
  key: 'name',
  label: 'عنوان فارسی',
  type: 'text',
  placeholder: 'عنوان را وارد کنید',
  required: true,
};

export const masterDataCatalog: readonly MasterDataCatalogItem[] = [
  {
    key: 'countries',
    label: 'کشورها',
    singularLabel: 'کشور',
    group: 'جغرافیا',
    description: 'کشور مشترک بین شرکت‌ها با کد رسمی ISO-2 و نام فارسی/انگلیسی.',
    fields: [
      {
        key: 'iso2Code',
        label: 'کد ISO-2',
        type: 'text',
        placeholder: 'IR',
        required: true,
        hint: 'دو حرف رسمی کشور؛ با حروف بزرگ ذخیره می‌شود.',
      },
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Iran',
        required: true,
      },
    ],
    preview: { iso2Code: 'IR', name: 'ایران', englishName: 'Iran' },
  },
  {
    key: 'regions',
    label: 'استان‌ها و نواحی',
    singularLabel: 'استان/ناحیه',
    group: 'جغرافیا',
    description: 'ساختار سلسله‌مراتبی استان، ایالت و ناحیه در محدوده یک کشور.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Tehran Province',
        required: true,
      },
      {
        key: 'countryId',
        label: 'کشور',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'parentRegionId',
        label: 'ناحیه والد',
        type: 'text',
        placeholder: '',
      },
      {
        key: 'type',
        label: 'نوع ساختار',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'PROVINCE', label: 'استان' },
          { value: 'STATE', label: 'ایالت' },
          { value: 'REGION', label: 'ناحیه' },
          { value: 'TERRITORY', label: 'قلمرو' },
        ],
      },
    ],
    preview: { name: 'تهران', englishName: 'Tehran', type: 'PROVINCE' },
  },
  {
    key: 'cities',
    label: 'شهرها',
    singularLabel: 'شهر',
    group: 'جغرافیا',
    description: 'شهر وابسته به کشور و در صورت نیاز استان/ناحیه ساختاری.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Tehran',
        required: true,
      },
      {
        key: 'countryId',
        label: 'کشور',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'regionId',
        label: 'استان/ناحیه',
        type: 'text',
        placeholder: '',
      },
    ],
    preview: { name: 'تهران', englishName: 'Tehran', countryId: 'country_ir' },
  },
  {
    key: 'airports',
    label: 'فرودگاه‌ها',
    singularLabel: 'فرودگاه',
    group: 'جغرافیا',
    description:
      'فرودگاه با کدهای رسمی، Timezone معتبر IANA و مختصات کنترل‌شده.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Mehrabad International Airport',
        required: true,
      },
      {
        key: 'countryId',
        label: 'کشور',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'cityId',
        label: 'شهر',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'iataCode',
        label: 'کد IATA',
        type: 'text',
        placeholder: 'THR',
        required: true,
      },
      {
        key: 'icaoCode',
        label: 'کد ICAO',
        type: 'text',
        placeholder: 'OIII',
        required: true,
      },
      {
        key: 'ianaTimezone',
        label: 'Timezone IANA',
        type: 'text',
        placeholder: 'Asia/Tehran',
        required: true,
      },
      {
        key: 'latitude',
        label: 'عرض جغرافیایی',
        type: 'number',
        placeholder: '35.6892',
        required: true,
      },
      {
        key: 'longitude',
        label: 'طول جغرافیایی',
        type: 'number',
        placeholder: '51.3134',
        required: true,
      },
    ],
    preview: { iataCode: 'THR', icaoCode: 'OIII', ianaTimezone: 'Asia/Tehran' },
  },
  {
    key: 'terminals',
    label: 'ترمینال‌ها',
    singularLabel: 'ترمینال',
    group: 'جغرافیا',
    description: 'ترمینال وابسته به فرودگاه با نوع داخلی، بین‌المللی یا VIP.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Terminal 1',
      },
      {
        key: 'airportId',
        label: 'فرودگاه',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'terminalType',
        label: 'نوع ترمینال',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'DOMESTIC', label: 'داخلی' },
          { value: 'INTERNATIONAL', label: 'بین‌المللی' },
          { value: 'VIP', label: 'VIP' },
        ],
      },
    ],
    preview: {
      name: 'ترمینال ۱',
      airportId: 'airport_thr',
      terminalType: 'DOMESTIC',
    },
  },
  {
    key: 'currencies',
    label: 'ارزها',
    singularLabel: 'ارز',
    group: 'مالی',
    description:
      'مشخصات نمایشی ارز با کد رسمی ISO-4217، نام انگلیسی و سیاست نمایش مستقل.',
    fields: [
      {
        key: 'code',
        label: 'کد ISO-4217',
        type: 'text',
        placeholder: 'USD',
        required: true,
        hint: 'سه حرف بزرگ و یکتا.',
      },
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Iranian Rial',
        required: true,
      },
      { key: 'symbol', label: 'نماد نمایشی', type: 'text', placeholder: '﷼' },
      {
        key: 'decimalDigits',
        label: 'تعداد رقم اعشار',
        type: 'number',
        placeholder: '2',
      },
      {
        key: 'displayPolicy',
        label: 'سیاست نمایش',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'SYMBOL_BEFORE', label: 'نماد قبل از مبلغ' },
          { value: 'SYMBOL_AFTER', label: 'نماد بعد از مبلغ' },
          { value: 'CODE_BEFORE', label: 'کد قبل از مبلغ' },
          { value: 'CODE_AFTER', label: 'کد بعد از مبلغ' },
        ],
      },
    ],
    preview: { code: 'IRR', name: 'ریال ایران', symbol: '﷼' },
  },
  {
    key: 'exchange-rates',
    label: 'نرخ ارز',
    singularLabel: 'نرخ ارز',
    group: 'مالی',
    description:
      'طرح Contract برای snapshot نرخ؛ محاسبه authoritative با DEC-OPEN-004 مسدود است.',
    fields: [
      {
        key: 'fromCurrencyCode',
        label: 'ارز مبدأ',
        type: 'text',
        placeholder: 'USD',
        required: true,
      },
      {
        key: 'toCurrencyCode',
        label: 'ارز مقصد',
        type: 'text',
        placeholder: 'IRR',
        required: true,
      },
      {
        key: 'rate',
        label: 'نرخ Decimal',
        type: 'number',
        placeholder: '0.00',
        required: true,
      },
      {
        key: 'rateType',
        label: 'نوع نرخ',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'BUY', label: 'خرید' },
          { value: 'SELL', label: 'فروش' },
          { value: 'REFERENCE', label: 'مبنا/حسابداری' },
        ],
      },
      {
        key: 'source',
        label: 'منبع نرخ',
        type: 'text',
        placeholder: 'منبع تأییدشده',
        required: true,
      },
      {
        key: 'observedAt',
        label: 'زمان مشاهده UTC',
        type: 'datetime-local',
        placeholder: '',
        required: true,
      },
      {
        key: 'validFrom',
        label: 'شروع اعتبار UTC',
        type: 'datetime-local',
        placeholder: '',
        required: true,
      },
      {
        key: 'validTo',
        label: 'پایان اعتبار (اختیاری)',
        type: 'datetime-local',
        placeholder: '',
      },
      {
        key: 'correctionReason',
        label: 'توضیح اصلاح',
        type: 'text',
        placeholder: 'در صورت اصلاح نسخه قبلی',
      },
    ],
    preview: {
      fromCurrencyCode: 'USD',
      toCurrencyCode: 'IRR',
      rate: '—',
      source: 'Blocked',
    },
  },
  {
    key: 'banks',
    label: 'بانک‌ها',
    singularLabel: 'بانک',
    group: 'مالی',
    description: 'تعریف بانک و کشور مرجع؛ حساب و مانده متعلق به Finance است.',
    fields: [
      {
        key: 'code',
        label: 'کد بانک',
        type: 'text',
        placeholder: 'MELLAT',
        required: true,
      },
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Bank Mellat',
        required: true,
      },
      {
        key: 'countryId',
        label: 'کشور',
        type: 'text',
        placeholder: 'country_...',
        required: true,
      },
      {
        key: 'swiftCode',
        label: 'کد SWIFT',
        type: 'text',
        placeholder: 'BKMTIRTH',
      },
    ],
    preview: {
      code: 'BANK_SAMPLE',
      name: 'بانک نمونه',
      countryId: 'country_ir',
    },
  },
  {
    key: 'bank-branches',
    label: 'شعب بانک',
    singularLabel: 'شعبه بانک',
    group: 'مالی',
    description:
      'شعبه مستقل بانک با شهر، نشانی و تلفن عمومی؛ حساب و شبا در Finance نگهداری می‌شود.',
    fields: [
      {
        key: 'code',
        label: 'کد شعبه',
        type: 'text',
        placeholder: 'CENTRAL_001',
        required: true,
      },
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Central Branch',
      },
      {
        key: 'bankId',
        label: 'بانک',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'cityId',
        label: 'شهر',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'address',
        label: 'نشانی',
        type: 'text',
        placeholder: 'نشانی عمومی شعبه',
      },
      {
        key: 'phone',
        label: 'تلفن عمومی',
        type: 'text',
        placeholder: '021-...',
      },
    ],
    preview: { code: 'CENTRAL_001', name: 'شعبه مرکزی' },
  },
  {
    key: 'payment-methods',
    label: 'روش‌های پرداخت',
    singularLabel: 'روش پرداخت',
    group: 'مالی',
    description:
      'تعریف مرجع کانال دریافت/پرداخت؛ تنظیم درگاه، حساب مقصد و تراکنش متعلق به Finance است.',
    fields: [
      {
        key: 'code',
        label: 'کد روش',
        type: 'text',
        placeholder: 'BANK_TRANSFER',
        required: true,
      },
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Bank transfer',
      },
      {
        key: 'channel',
        label: 'کانال',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'CASH', label: 'نقدی' },
          { value: 'POS', label: 'کارت‌خوان' },
          { value: 'BANK_TRANSFER', label: 'حواله بانکی' },
          { value: 'ONLINE_GATEWAY', label: 'درگاه آنلاین' },
          { value: 'CREDIT', label: 'اعتباری' },
          { value: 'WALLET', label: 'کیف پول' },
          { value: 'OTHER', label: 'سایر' },
        ],
      },
      {
        key: 'direction',
        label: 'جهت',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'RECEIPT', label: 'دریافت' },
          { value: 'PAYMENT', label: 'پرداخت' },
          { value: 'BOTH', label: 'هر دو' },
        ],
      },
      {
        key: 'requiresManualApproval',
        label: 'نیازمند تأیید دستی',
        type: 'select',
        placeholder: '',
        options: [
          { value: 'false', label: 'خیر' },
          { value: 'true', label: 'بله' },
        ],
      },
      {
        key: 'displayOrder',
        label: 'ترتیب نمایش',
        type: 'number',
        placeholder: '0',
      },
      {
        key: 'description',
        label: 'توضیح',
        type: 'text',
        placeholder: 'تعریف مرجع روش پرداخت',
      },
    ],
    preview: { code: 'BANK_TRANSFER', name: 'حواله بانکی' },
  },
  {
    key: 'insurers',
    label: 'شرکت‌های بیمه',
    singularLabel: 'شرکت بیمه',
    group: 'بیمه',
    description:
      'مدیریت بیمه‌گران دارای Organization فعال با نقش بیمه‌گر؛ قرارداد خرید در Procurement است.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Insurance Company',
        required: true,
      },
      {
        key: 'organizationId',
        label: 'سازمان بیمه‌گر',
        type: 'text',
        placeholder: 'org_...',
        required: true,
      },
      {
        key: 'countryId',
        label: 'کشور',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'logoFileReference',
        label: 'Reference لوگو در Documents',
        type: 'text',
        placeholder: 'UUID معتبر Documents',
        hint: 'اختیاری؛ هیچ فایل یا شناسه ساختگی ذخیره نمی‌شود.',
      },
    ],
    preview: {
      name: 'بیمه نمونه',
      englishName: 'Sample Insurance',
      organizationId: 'org_insurer',
    },
  },
  {
    key: 'insurance-plans',
    label: 'طرح‌های بیمه',
    singularLabel: 'طرح بیمه',
    group: 'بیمه',
    description:
      'تعریف طرح‌های قابل استفاده بر اساس بیمه‌گر، مقصد، گروه سنی و بازه اعتبار.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Travel Insurance Plan',
      },
      {
        key: 'insurerId',
        label: 'بیمه‌گر',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'destinationRegion',
        label: 'مقصد یا منطقه',
        type: 'text',
        placeholder: 'شنگن / سراسر جهان',
        required: true,
      },
      {
        key: 'minimumAge',
        label: 'حداقل سن',
        type: 'number',
        placeholder: '0',
        required: true,
      },
      {
        key: 'maximumAge',
        label: 'حداکثر سن',
        type: 'number',
        placeholder: '65',
      },
      {
        key: 'validFrom',
        label: 'شروع اعتبار',
        type: 'datetime-local',
        placeholder: '',
        required: true,
      },
      {
        key: 'validTo',
        label: 'پایان اعتبار',
        type: 'datetime-local',
        placeholder: '',
      },
      {
        key: 'coverageIds',
        label: 'پوشش‌ها',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'description',
        label: 'شرح استفاده',
        type: 'text',
        placeholder: 'شرح مرجع طرح',
      },
    ],
    preview: {
      name: 'طرح نمونه',
      destinationRegion: 'منطقه مرجع',
      minimumAge: '0',
    },
  },
  {
    key: 'insurance-coverages',
    label: 'پوشش‌ها',
    singularLabel: 'پوشش',
    group: 'بیمه',
    description:
      'کاتالوگ پوشش‌های بیمه با سقف، ارز، فرانشیز و شرح قابل استفاده در طرح‌ها.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Medical Coverage',
      },
      {
        key: 'coverageLimit',
        label: 'سقف تعهد',
        type: 'text',
        placeholder: '10000.0000000000',
        required: true,
        hint: 'Decimal مثبت با حداکثر ۱۰ رقم اعشار.',
      },
      {
        key: 'currencyId',
        label: 'ارز',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'deductibleAmount',
        label: 'فرانشیز',
        type: 'text',
        placeholder: '0',
        hint: 'Decimal نامنفی و حداکثر برابر سقف تعهد.',
      },
      {
        key: 'description',
        label: 'شرح',
        type: 'text',
        placeholder: 'شرح مرجع پوشش',
      },
    ],
    preview: {
      name: 'پوشش نمونه',
      coverageLimit: '10000',
      deductibleAmount: '0',
    },
  },
  {
    key: 'airlines',
    label: 'ایرلاین‌ها',
    singularLabel: 'ایرلاین',
    group: 'حمل‌ونقل',
    description:
      'مشخصات مرجع ایرلاین با کدهای IATA/ICAO؛ Credential و اتصال Provider خارج از Master Data است.',
    fields: [
      {
        key: 'code',
        label: 'کد IATA',
        type: 'text',
        placeholder: 'W5',
        required: true,
      },
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Airline Name',
      },
      { key: 'icaoCode', label: 'کد ICAO', type: 'text', placeholder: 'IRM' },
      {
        key: 'organizationId',
        label: 'سازمان ایرلاین',
        type: 'text',
        placeholder: 'org_...',
        required: true,
      },
      {
        key: 'countryId',
        label: 'کشور مبدأ',
        type: 'text',
        placeholder: '',
      },
    ],
    preview: {
      code: 'W5',
      name: 'ایرلاین نمونه',
      icaoCode: 'IRM',
      organizationId: 'org_airline',
    },
  },
  {
    key: 'aircraft-types',
    label: 'انواع هواپیما',
    singularLabel: 'نوع هواپیما',
    group: 'حمل‌ونقل',
    description:
      'کاتالوگ سازنده، مدل و نوع بدنه هواپیما بدون وابستگی به ناوگان عملیاتی.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Airbus A320',
      },
      {
        key: 'manufacturer',
        label: 'سازنده',
        type: 'text',
        placeholder: 'Airbus',
        required: true,
      },
      {
        key: 'model',
        label: 'مدل',
        type: 'text',
        placeholder: 'A320-200',
        required: true,
      },
      {
        key: 'bodyType',
        label: 'نوع بدنه',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'NARROW_BODY', label: 'بدنه باریک' },
          { value: 'WIDE_BODY', label: 'بدنه پهن' },
          { value: 'TURBOPROP', label: 'توربوپراپ' },
          { value: 'REGIONAL', label: 'منطقه‌ای' },
          { value: 'OTHER', label: 'سایر' },
        ],
      },
    ],
    preview: {
      name: 'ایرباس ۳۲۰',
      manufacturer: 'Airbus',
      model: 'A320-200',
      bodyType: 'NARROW_BODY',
    },
  },
  {
    key: 'cabin-classes',
    label: 'کلاس‌های پروازی',
    singularLabel: 'کلاس پروازی',
    group: 'حمل‌ونقل',
    description:
      'کد رزرو و Cabin مرجع؛ قیمت و موجودی صندلی در Ticket Catalog/Reservations می‌ماند.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Economy',
      },
      {
        key: 'bookingCode',
        label: 'کد رزرو',
        type: 'text',
        placeholder: 'Y',
        required: true,
      },
      {
        key: 'cabinType',
        label: 'Cabin',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'ECONOMY', label: 'Economy' },
          { value: 'PREMIUM_ECONOMY', label: 'Premium Economy' },
          { value: 'BUSINESS', label: 'Business' },
          { value: 'FIRST', label: 'First' },
        ],
      },
      {
        key: 'displayOrder',
        label: 'ترتیب نمایش',
        type: 'number',
        placeholder: '0',
      },
    ],
    preview: { name: 'اکونومی', bookingCode: 'Y', cabinType: 'ECONOMY' },
  },
  {
    key: 'baggage-rules',
    label: 'قواعد بار',
    singularLabel: 'قاعده بار',
    group: 'حمل‌ونقل',
    description:
      'نسخه مستقل قواعد بار براساس ایرلاین، کلاس، مسافر، مسیر و بازه اعتبار.',
    fields: [
      nameField,
      {
        key: 'airlineId',
        label: 'ایرلاین',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'cabinClassId',
        label: 'کلاس پروازی',
        type: 'text',
        placeholder: '',
      },
      {
        key: 'passengerType',
        label: 'نوع مسافر',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'ADT', label: 'بزرگسال' },
          { value: 'CHD', label: 'کودک' },
          { value: 'INF', label: 'نوزاد' },
        ],
      },
      {
        key: 'routeScope',
        label: 'دامنه مسیر',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'ALL', label: 'همه مسیرها' },
          { value: 'DOMESTIC', label: 'داخلی' },
          { value: 'INTERNATIONAL', label: 'بین‌المللی' },
        ],
      },
      {
        key: 'allowance',
        label: 'مقدار مجاز',
        type: 'number',
        placeholder: '20',
        required: true,
      },
      {
        key: 'unit',
        label: 'واحد',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'KG', label: 'کیلوگرم' },
          { value: 'PC', label: 'قطعه' },
        ],
      },
      {
        key: 'pieceCount',
        label: 'تعداد قطعه',
        type: 'number',
        placeholder: '1',
      },
      {
        key: 'validFrom',
        label: 'شروع اعتبار',
        type: 'datetime-local',
        placeholder: '',
        required: true,
      },
      {
        key: 'validTo',
        label: 'پایان اعتبار',
        type: 'datetime-local',
        placeholder: '',
      },
      {
        key: 'description',
        label: 'توضیحات',
        type: 'text',
        placeholder: 'توضیح قاعده',
      },
    ],
    preview: {
      name: 'بار اکونومی',
      passengerType: 'ADT',
      allowance: '20',
      unit: 'KG',
    },
  },
  {
    key: 'manifest-templates',
    label: 'قالب‌های Manifest',
    singularLabel: 'قالب Manifest',
    group: 'حمل‌ونقل',
    description:
      'تعریف نسخه و ساختار ستون‌ها؛ فایل واقعی فقط با Reference سرویس Documents متصل می‌شود.',
    fields: [
      nameField,
      {
        key: 'airlineId',
        label: 'ایرلاین',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'versionNumber',
        label: 'شماره نسخه',
        type: 'number',
        placeholder: '1',
        required: true,
      },
      {
        key: 'fileFormat',
        label: 'فرمت فایل',
        type: 'select',
        placeholder: '',
        required: true,
        options: ['XLSX', 'CSV', 'XML', 'JSON'].map((value) => ({
          value,
          label: value,
        })),
      },
      {
        key: 'fileReferenceId',
        label: 'Reference سند',
        type: 'text',
        placeholder: 'UUID سرویس Documents',
        hint: 'شناسه ساختگی وارد نکنید.',
      },
      {
        key: 'sheetName',
        label: 'نام Sheet',
        type: 'text',
        placeholder: 'Passengers',
      },
      {
        key: 'headerRow',
        label: 'ردیف عنوان',
        type: 'number',
        placeholder: '1',
      },
      {
        key: 'dateFormat',
        label: 'قالب تاریخ',
        type: 'text',
        placeholder: 'yyyy-MM-dd',
      },
      {
        key: 'requiredColumns',
        label: 'ستون‌های الزامی',
        type: 'text',
        placeholder: 'firstName,lastName,passportNo',
        required: true,
      },
      {
        key: 'columnOrder',
        label: 'ترتیب ستون‌ها',
        type: 'text',
        placeholder: 'firstName,lastName,passportNo',
        required: true,
      },
      {
        key: 'validFrom',
        label: 'شروع اعتبار',
        type: 'datetime-local',
        placeholder: '',
        required: true,
      },
      {
        key: 'validTo',
        label: 'پایان اعتبار',
        type: 'datetime-local',
        placeholder: '',
      },
      {
        key: 'publicationStatus',
        label: 'وضعیت انتشار',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'DRAFT', label: 'پیش‌نویس' },
          { value: 'ACTIVE', label: 'فعال' },
          { value: 'EXPIRED', label: 'منقضی' },
        ],
      },
    ],
    preview: {
      name: 'Manifest مسافر',
      versionNumber: '1',
      fileFormat: 'XLSX',
      publicationStatus: 'DRAFT',
    },
  },
  {
    key: 'rail-companies',
    label: 'شرکت‌های ریلی',
    singularLabel: 'شرکت ریلی',
    group: 'حمل‌ونقل',
    description:
      'شرکت ریلی مرجع متصل به Organization؛ رزرو و اتصال Provider خارج از این دامنه است.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Rail Company',
      },
      {
        key: 'organizationId',
        label: 'سازمان ریلی',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'countryId',
        label: 'کشور',
        type: 'text',
        placeholder: '',
        required: true,
      },
    ],
    preview: { name: 'شرکت ریلی', organizationId: 'UUID', countryId: 'UUID' },
  },
  {
    key: 'train-types',
    label: 'انواع قطار',
    singularLabel: 'نوع قطار',
    group: 'حمل‌ونقل',
    description: 'کاتالوگ سازنده، مدل، دسته و امکانات نوع قطار.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Train Type',
      },
      {
        key: 'manufacturer',
        label: 'سازنده',
        type: 'text',
        placeholder: 'Manufacturer',
        required: true,
      },
      {
        key: 'model',
        label: 'مدل',
        type: 'text',
        placeholder: 'Model',
        required: true,
      },
      {
        key: 'category',
        label: 'دسته',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'SLEEPER', label: 'خواب‌دار' },
          { value: 'EXPRESS', label: 'سریع‌السیر' },
          { value: 'SALOON', label: 'سالنی' },
          { value: 'LUXURY', label: 'لوکس' },
          { value: 'OTHER', label: 'سایر' },
        ],
      },
      {
        key: 'amenities',
        label: 'امکانات',
        type: 'text',
        placeholder: 'کوپه،پذیرایی',
      },
    ],
    preview: {
      name: 'قطار خواب‌دار',
      manufacturer: 'Manufacturer',
      model: 'Model',
      category: 'SLEEPER',
    },
  },
  {
    key: 'bus-companies',
    label: 'شرکت‌های اتوبوس',
    singularLabel: 'شرکت اتوبوس',
    group: 'حمل‌ونقل',
    description:
      'شرکت اتوبوس مرجع متصل به Organization؛ فروش و تسویه در ماژول‌های مالک باقی می‌ماند.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Bus Company',
      },
      {
        key: 'organizationId',
        label: 'سازمان اتوبوس',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'countryId',
        label: 'کشور',
        type: 'text',
        placeholder: '',
        required: true,
      },
    ],
    preview: { name: 'شرکت اتوبوس', organizationId: 'UUID', countryId: 'UUID' },
  },
  {
    key: 'bus-types',
    label: 'انواع اتوبوس',
    singularLabel: 'نوع اتوبوس',
    group: 'حمل‌ونقل',
    description: 'کاتالوگ مدل، سازنده، کلاس خدمات و امکانات نوع اتوبوس.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Bus Type',
      },
      {
        key: 'manufacturer',
        label: 'سازنده',
        type: 'text',
        placeholder: 'Manufacturer',
        required: true,
      },
      {
        key: 'model',
        label: 'مدل',
        type: 'text',
        placeholder: 'Model',
        required: true,
      },
      {
        key: 'serviceClass',
        label: 'کلاس خدمات',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'STANDARD', label: 'استاندارد' },
          { value: 'VIP', label: 'VIP' },
          { value: 'LUXURY', label: 'لوکس' },
          { value: 'OTHER', label: 'سایر' },
        ],
      },
      {
        key: 'amenities',
        label: 'امکانات',
        type: 'text',
        placeholder: 'مانیتور،پذیرایی',
      },
    ],
    preview: {
      name: 'اتوبوس VIP',
      manufacturer: 'Manufacturer',
      model: 'Model',
      serviceClass: 'VIP',
    },
  },
  {
    key: 'hotels',
    label: 'هتل‌ها',
    singularLabel: 'هتل',
    group: 'اقامت',
    description:
      'پروفایل مرجع هتل، موقعیت، زنجیره و کاتالوگ خدمات؛ قرارداد و موجودی خارج از Master Data است.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Hotel English Name',
      },
      {
        key: 'cityId',
        label: 'شهر',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'chainId',
        label: 'زنجیره هتل',
        type: 'text',
        placeholder: '',
      },
      {
        key: 'starRating',
        label: 'درجه هتل',
        type: 'number',
        placeholder: '1 تا 5',
      },
      {
        key: 'address',
        label: 'آدرس',
        type: 'text',
        placeholder: 'نشانی مرجع هتل',
      },
      {
        key: 'website',
        label: 'وب‌سایت',
        type: 'text',
        placeholder: 'hotel.example',
      },
      {
        key: 'checkInTime',
        label: 'ساعت ورود',
        type: 'text',
        placeholder: '15:00',
      },
      {
        key: 'checkOutTime',
        label: 'ساعت خروج',
        type: 'text',
        placeholder: '12:00',
      },
      {
        key: 'latitude',
        label: 'عرض جغرافیایی',
        type: 'number',
        placeholder: '35.000000',
      },
      {
        key: 'longitude',
        label: 'طول جغرافیایی',
        type: 'number',
        placeholder: '51.000000',
      },
      {
        key: 'isSaleableReference',
        label: 'فروش‌پذیری مرجع',
        type: 'select',
        placeholder: '',
        options: [
          { value: 'true', label: 'فروش‌پذیر' },
          { value: 'false', label: 'غیرفروش‌پذیر' },
        ],
      },
      {
        key: 'mealServiceIds',
        label: 'وعده و سرویس',
        type: 'text',
        placeholder: '',
      },
      {
        key: 'roomTypeIds',
        label: 'نوع‌های اتاق',
        type: 'text',
        placeholder: '',
      },
      {
        key: 'facilityIds',
        label: 'امکانات',
        type: 'text',
        placeholder: '',
      },
    ],
    preview: {
      code: 'AUTO',
      name: 'عنوان هتل',
      cityId: 'UUID',
      starRating: '1-5',
    },
  },
  {
    key: 'hotel-chains',
    label: 'زنجیره‌های هتل',
    singularLabel: 'زنجیره هتل',
    group: 'اقامت',
    description: 'برند و گروه‌بندی مرجع هتل‌ها با کشور مبدأ و وب‌سایت.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'نام انگلیسی',
        type: 'text',
        placeholder: 'Chain English Name',
      },
      {
        key: 'countryId',
        label: 'کشور مبدأ',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'website',
        label: 'وب‌سایت',
        type: 'text',
        placeholder: 'chain.example',
      },
    ],
    preview: { code: 'AUTO', name: 'عنوان زنجیره', countryId: 'UUID' },
  },
  {
    key: 'room-types',
    label: 'نوع‌های اتاق',
    singularLabel: 'نوع اتاق',
    group: 'اقامت',
    description:
      'کاتالوگ استاندارد نوع اتاق؛ موجودی و تخصیص مسافر در Reservations است.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Room Type',
      },
      {
        key: 'referenceCapacity',
        label: 'ظرفیت استاندارد',
        type: 'number',
        placeholder: '1 تا 20',
      },
      {
        key: 'usageDescription',
        label: 'توضیح استفاده',
        type: 'text',
        placeholder: 'توضیح مرجع و غیرعملیاتی',
      },
    ],
    preview: { code: 'AUTO', name: 'نوع اتاق', referenceCapacity: '2' },
  },
  {
    key: 'meal-services',
    label: 'وعده و سرویس',
    singularLabel: 'وعده/سرویس',
    group: 'اقامت',
    description: 'کاتالوگ مستقل Meal Plan و Service Code با وعده‌های شامل‌شده.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Meal or Service',
      },
      {
        key: 'category',
        label: 'دسته',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'MEAL_PLAN', label: 'Meal Plan' },
          { value: 'SERVICE', label: 'Service' },
        ],
      },
      {
        key: 'includedMeals',
        label: 'وعده‌های شامل‌شده',
        type: 'text',
        placeholder: 'صبحانه،ناهار،شام',
      },
    ],
    preview: { code: 'AUTO', name: 'عنوان سرویس', category: 'MEAL_PLAN' },
  },
  {
    key: 'facilities',
    label: 'امکانات هتل',
    singularLabel: 'امکان',
    group: 'اقامت',
    description: 'کاتالوگ مستقل امکانات با دسته‌بندی و رابطه چندبه‌چند به هتل.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Facility',
      },
      {
        key: 'category',
        label: 'دسته',
        type: 'text',
        placeholder: 'عمومی، ورزشی، خانواده و ...',
      },
      {
        key: 'displayOrder',
        label: 'ترتیب نمایش',
        type: 'number',
        placeholder: '0',
      },
    ],
    preview: { code: 'AUTO', name: 'عنوان امکان', displayOrder: '0' },
  },
  {
    key: 'composite-hotels',
    label: 'هتل‌های ترکیبی',
    singularLabel: 'هتل ترکیبی',
    group: 'اقامت',
    description:
      'رکورد نمایشی فروش شامل چند هتل واقعی؛ رزرو و قرارداد روی هتل واقعی می‌ماند.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Composite Hotel',
      },
      {
        key: 'cityId',
        label: 'شهر',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'usageCondition',
        label: 'شرط استفاده',
        type: 'text',
        placeholder: 'شرط تخصیص و اطلاع‌رسانی',
        required: true,
      },
      {
        key: 'isSaleableReference',
        label: 'فروش‌پذیری مرجع',
        type: 'select',
        placeholder: '',
        options: [
          { value: 'true', label: 'فروش‌پذیر' },
          { value: 'false', label: 'در حال بررسی' },
        ],
      },
      {
        key: 'memberHotelIds',
        label: 'هتل‌های عضو به‌ترتیب اولویت',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'backupMemberIds',
        label: 'اعضای پشتیبان',
        type: 'text',
        placeholder: '',
      },
    ],
    preview: { code: 'AUTO', name: 'عنوان ترکیب', cityId: 'UUID' },
  },
  {
    key: 'organizations',
    label: 'آژانس‌ها و شرکت‌ها',
    singularLabel: 'سازمان',
    group: 'سازمان‌ها',
    description:
      'Profile مشترک Organization با roleهای چندگانه Agency/Corporate.',
    fields: [
      {
        key: 'legalName',
        label: 'نام ثبتی',
        type: 'text',
        placeholder: 'نام ثبتی',
        required: true,
      },
      {
        key: 'displayName',
        label: 'نام نمایشی',
        type: 'text',
        placeholder: 'نام نمایشی',
        required: true,
      },
      {
        key: 'roleCodes',
        label: 'Roleهای سازمان',
        type: 'text',
        placeholder: 'AGENCY,CORPORATE_CUSTOMER',
        required: true,
      },
    ],
    preview: {
      code: 'ORG_SAMPLE',
      legalName: 'شرکت نمونه',
      displayName: 'سازمان نمونه',
      roleCodes: 'AGENCY',
    },
  },
  {
    key: 'suppliers',
    label: 'تأمین‌کنندگان',
    singularLabel: 'تأمین‌کننده',
    group: 'سازمان‌ها',
    description:
      'پروفایل مرجع تأمین‌کننده متصل به Organization یکتا؛ قرارداد و بدهی در ماژول مالک باقی می‌ماند.',
    fields: [
      {
        key: 'organizationId',
        label: 'سازمان تأمین‌کننده',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'countryId',
        label: 'کشور',
        type: 'text',
        placeholder: '',
      },
      {
        key: 'cityId',
        label: 'شهر',
        type: 'text',
        placeholder: '',
      },
      {
        key: 'externalProviderReference',
        label: 'شناسه عمومی Provider/API',
        type: 'text',
        placeholder: 'PROVIDER-REF',
        hint: 'Credential یا Secret در این فیلد ذخیره نمی‌شود.',
      },
      {
        key: 'collaborationStatus',
        label: 'وضعیت همکاری',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'ACTIVE', label: 'همکاری فعال' },
          { value: 'UNDER_REVIEW', label: 'در حال بررسی' },
          { value: 'PURCHASE_SUSPENDED', label: 'تعلیق خرید' },
          { value: 'ENDED', label: 'پایان همکاری' },
        ],
      },
      {
        key: 'serviceCodes',
        label: 'کد خدمات',
        type: 'text',
        placeholder: 'HOTEL,FLIGHT',
        hint: 'کدهای کاتالوگ خدمات را با ویرگول جدا کنید.',
      },
    ],
    preview: {
      organizationId: 'org_supplier',
      collaborationStatus: 'UNDER_REVIEW',
    },
  },
  {
    key: 'brokers',
    label: 'کارگزاران',
    singularLabel: 'کارگزار',
    group: 'سازمان‌ها',
    description:
      'Profile عملیاتی کارگزار با reference سازمان؛ بدهی و قرارداد اینجا نگهداری نمی‌شود.',
    fields: [
      nameField,
      {
        key: 'organizationId',
        label: 'سازمان کارگزار',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'countryId',
        label: 'کشور',
        type: 'text',
        placeholder: '',
      },
      {
        key: 'cityId',
        label: 'شهر',
        type: 'text',
        placeholder: '',
      },
      {
        key: 'collaborationStatus',
        label: 'وضعیت همکاری',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'ACTIVE', label: 'همکاری فعال' },
          { value: 'UNDER_REVIEW', label: 'در حال بررسی' },
          { value: 'PURCHASE_SUSPENDED', label: 'تعلیق خرید' },
          { value: 'ENDED', label: 'پایان همکاری' },
        ],
      },
      {
        key: 'serviceCodes',
        label: 'کد خدمات',
        type: 'text',
        placeholder: 'HOTEL,FLIGHT',
        hint: 'کدهای کاتالوگ خدمات را با ویرگول جدا کنید.',
      },
    ],
    preview: {
      code: 'BROKER_SAMPLE',
      name: 'کارگزار نمونه',
      organizationId: 'org_broker',
      collaborationStatus: 'UNDER_REVIEW',
    },
  },
  {
    key: 'travel-services',
    label: 'خدمات مرجع سفر',
    singularLabel: 'خدمت مرجع',
    group: 'سازمان‌ها',
    description:
      'کاتالوگ رابطه‌ای خدمات قابل ارائه برای تأمین‌کننده و کارگزار؛ بدون ستون‌های Boolean ثابت.',
    fields: [
      {
        key: 'code',
        label: 'کد خدمت',
        type: 'text',
        placeholder: 'HOTEL',
        required: true,
      },
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Hotel',
      },
    ],
    preview: { code: 'HOTEL', name: 'هتل', englishName: 'Hotel' },
  },
  {
    key: 'organization-contacts',
    label: 'اطلاعات تماس',
    singularLabel: 'مخاطب',
    group: 'سازمان‌ها',
    description:
      'مخاطبان متعدد سازمان با رمزنگاری مستقل، نمایش ماسک‌شده و Unmask مجوزمحور.',
    fields: [
      {
        key: 'organizationId',
        label: 'سازمان',
        type: 'text',
        placeholder: '',
        required: true,
      },
      {
        key: 'fullName',
        label: 'نام مخاطب',
        type: 'text',
        placeholder: 'نام و نام خانوادگی',
        required: true,
      },
      {
        key: 'jobTitle',
        label: 'سمت',
        type: 'text',
        placeholder: 'مدیر فروش',
      },
      {
        key: 'preferredChannel',
        label: 'کانال ترجیحی',
        type: 'select',
        placeholder: '',
        required: true,
        options: [
          { value: 'PHONE', label: 'تلفن' },
          { value: 'WHATSAPP', label: 'WhatsApp' },
          { value: 'EMAIL', label: 'ایمیل' },
          { value: 'TELEGRAM', label: 'Telegram' },
          { value: 'OTHER', label: 'سایر' },
        ],
      },
      {
        key: 'phone',
        label: 'شماره تماس',
        type: 'text',
        placeholder: '+98912...',
        hint: 'پس از ذخیره رمزنگاری می‌شود و در فهرست فقط ماسک نمایش داده می‌شود.',
      },
      {
        key: 'email',
        label: 'ایمیل',
        type: 'text',
        placeholder: 'name@example.com',
      },
      {
        key: 'hasWhatsapp',
        label: 'دارای WhatsApp',
        type: 'select',
        placeholder: '',
        options: [
          { value: 'false', label: 'خیر' },
          { value: 'true', label: 'بله' },
        ],
      },
      {
        key: 'isPrimary',
        label: 'مخاطب اصلی',
        type: 'select',
        placeholder: '',
        options: [
          { value: 'false', label: 'خیر' },
          { value: 'true', label: 'بله' },
        ],
      },
    ],
    preview: {
      organizationId: 'org_supplier',
      fullName: 'مخاطب نمونه',
      preferredChannel: 'PHONE',
    },
  },
  {
    key: 'leaders',
    label: 'لیدرها',
    singularLabel: 'لیدر',
    group: 'خدمات سفر',
    description:
      'اطلاعات مرجع لیدر؛ سند، حساب بانکی و دستمزد با permission و ماژول مالک نگهداری می‌شود.',
    fields: [
      nameField,
      {
        key: 'languages',
        label: 'زبان‌ها',
        type: 'text',
        placeholder: 'fa,en',
        required: true,
      },
      {
        key: 'expertise',
        label: 'تخصص/مقصد',
        type: 'text',
        placeholder: 'تور داخلی',
      },
    ],
    preview: {
      code: 'LEADER_SAMPLE',
      name: 'لیدر نمونه',
      languages: 'fa,en',
      expertise: 'تور داخلی',
    },
  },
  {
    key: 'acquaintance-methods',
    label: 'نحوه آشنایی',
    singularLabel: 'نحوه آشنایی',
    group: 'فروش',
    description:
      'Reference مستقل از Sales Channel و Campaign برای منشأ آشنایی مشتری.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Referral',
      },
      {
        key: 'description',
        label: 'توضیح',
        type: 'text',
        placeholder: 'توضیح اختیاری',
      },
      {
        key: 'displayOrder',
        label: 'ترتیب نمایش',
        type: 'number',
        placeholder: '0',
      },
    ],
    preview: {
      code: 'REFERRAL',
      name: 'معرفی دوستان',
      description: 'نمونه طراحی',
    },
  },
  {
    key: 'lead-sources',
    label: 'منابع سرنخ',
    singularLabel: 'منبع سرنخ',
    group: 'فروش',
    description:
      'منشأ ورود Lead؛ مستقل از نحوه آشنایی مشتری، کانال فروش و کمپین.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Lead Source',
      },
      {
        key: 'description',
        label: 'توضیحات',
        type: 'text',
        placeholder: 'تعریف منبع سرنخ',
      },
      {
        key: 'displayOrder',
        label: 'ترتیب نمایش',
        type: 'number',
        placeholder: '0',
      },
    ],
    preview: { code: 'AUTO', name: 'منبع سرنخ', displayOrder: '0' },
  },
  {
    key: 'sales-channels',
    label: 'کانال‌های فروش',
    singularLabel: 'کانال فروش',
    group: 'فروش',
    description:
      'کانال انجام فروش؛ رابطه استفاده و تراکنش فروش در ماژول Sales باقی می‌ماند.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Sales Channel',
      },
      {
        key: 'description',
        label: 'توضیحات',
        type: 'text',
        placeholder: 'تعریف کانال فروش',
      },
      {
        key: 'displayOrder',
        label: 'ترتیب نمایش',
        type: 'number',
        placeholder: '0',
      },
    ],
    preview: { code: 'AUTO', name: 'کانال فروش', displayOrder: '0' },
  },
  {
    key: 'lost-reasons',
    label: 'دلایل از دست رفتن',
    singularLabel: 'دلیل از دست رفتن',
    group: 'فروش',
    description:
      'دلیل مرجع پایان ناموفق Lead/Opportunity؛ وضعیت چرخه فروش در Customer Affairs/Sales است.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Lost Reason',
      },
      {
        key: 'description',
        label: 'توضیحات',
        type: 'text',
        placeholder: 'تعریف دلیل',
      },
      {
        key: 'displayOrder',
        label: 'ترتیب نمایش',
        type: 'number',
        placeholder: '0',
      },
    ],
    preview: { code: 'AUTO', name: 'دلیل از دست رفتن', displayOrder: '0' },
  },
  {
    key: 'customer-types',
    label: 'انواع مشتری',
    singularLabel: 'نوع مشتری',
    group: 'فروش',
    description:
      'طبقه‌بندی مرجع نوع مشتری؛ مستقل از Tag و بدون تغییر مدل Customers.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Customer Type',
      },
      {
        key: 'description',
        label: 'توضیحات',
        type: 'text',
        placeholder: 'تعریف نوع مشتری',
      },
      {
        key: 'displayOrder',
        label: 'ترتیب نمایش',
        type: 'number',
        placeholder: '0',
      },
    ],
    preview: { code: 'AUTO', name: 'نوع مشتری', displayOrder: '0' },
  },
  {
    key: 'tags',
    label: 'Tagها',
    singularLabel: 'Tag',
    group: 'فروش',
    description:
      'برچسب مرجع چندمنظوره؛ رابطه چندبه‌چند هر مصرف‌کننده در همان ماژول مالک است.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Tag',
      },
      {
        key: 'colorHex',
        label: 'رنگ',
        type: 'text',
        placeholder: '#2563EB',
        hint: 'کد Hex شش‌رقمی؛ فقط برای نمایش.',
      },
      {
        key: 'description',
        label: 'توضیحات',
        type: 'text',
        placeholder: 'تعریف Tag',
      },
      {
        key: 'displayOrder',
        label: 'ترتیب نمایش',
        type: 'number',
        placeholder: '0',
      },
    ],
    preview: { code: 'AUTO', name: 'Tag', colorHex: '#2563EB' },
  },
  {
    key: 'campaign-types',
    label: 'انواع کمپین',
    singularLabel: 'نوع کمپین',
    group: 'فروش',
    description:
      'نوع مرجع کمپین؛ خود کمپین، بودجه و Attribution در Marketing نگه‌داری می‌شود.',
    fields: [
      nameField,
      {
        key: 'englishName',
        label: 'عنوان انگلیسی',
        type: 'text',
        placeholder: 'Campaign Type',
      },
      {
        key: 'description',
        label: 'توضیحات',
        type: 'text',
        placeholder: 'تعریف نوع کمپین',
      },
      {
        key: 'displayOrder',
        label: 'ترتیب نمایش',
        type: 'number',
        placeholder: '0',
      },
    ],
    preview: { code: 'AUTO', name: 'نوع کمپین', displayOrder: '0' },
  },
];

export function getMasterDataDefinition(resource: MasterDataResourceKey) {
  const definition = masterDataCatalog.find((item) => item.key === resource);
  if (!definition) throw new Error(`Unknown master data resource: ${resource}`);
  return definition;
}
