export type DashboardDateBasis = 'created' | 'issued' | 'paid' | 'effective';
export type DashboardVisualKind =
  'line' | 'bar' | 'stacked-bar' | 'funnel' | 'table' | 'queue';
export type DashboardKpiRole =
  'outcome' | 'driver' | 'guardrail' | 'diagnostic';

export interface DashboardKpiDefinition {
  id: string;
  title: string;
  technicalName: string;
  grain: string;
  source: readonly string[];
  rule: string;
  exclusions: string;
  dateBasis: DashboardDateBasis | 'policy-dependent' | 'as-of';
  currency: 'required' | 'not-applicable';
  permission: string;
  openDecision?: string | undefined;
  role: DashboardKpiRole;
  decision: string;
  comparison: string;
  reportCode: string;
}

export interface DashboardVisualDefinition {
  id: string;
  title: string;
  description: string;
  kind: DashboardVisualKind;
  source: readonly string[];
  permission: string;
  drilldown: string;
  openDecision?: string | undefined;
}

export interface DashboardPageDefinition {
  id: string;
  title: string;
  technicalName: string;
  description: string;
  kpiIds: readonly string[];
  visualizations: readonly DashboardVisualDefinition[];
}

export interface DashboardNavigationItem {
  pageId: string;
  children?: readonly DashboardNavigationItem[];
}

const salesContract = 'reporting_sales_contract_facts';
const serviceItem = 'reporting_contract_service_facts';
const reservation = 'reporting_reservation_facts';
const payment = 'reporting_payment_facts';
const journalBalance = 'reporting_journal_balance_facts';
const ticket = 'reporting_ticket_facts';
const travelFacts = 'reporting.travel.facts.v1';
const salesPipeline = 'reporting_sales_contract_pipeline_facts_v1';
const ticketCapacity = 'reporting_ticket_capacity_facts_v1';
const supplierPayments = 'reporting_supplier_payment_queue_facts_v1';
const deliveryReadiness = 'reporting_reservation_delivery_readiness_facts_v1';
const leadPipeline = 'reporting_customer_affairs_lead_facts_v1';
const supportTickets = 'reporting_support_ticket_facts_v1';
const customerSatisfaction = 'reporting_customer_satisfaction_facts_v1';
const customerConsent = 'reporting_customer_consent_facts_v1';
const customerPortfolio = 'reporting_customer_portfolio_growth_facts_v1';
const agencyRisk = 'reporting_b2b_agency_risk_facts_v1';
const campaign = 'reporting_campaign_facts_v1';
const employeePerformance = 'reporting_employee_performance_facts_v1';
const hrRecordExpiry = 'reporting_hr_record_expiry_facts_v1';
const hotelRates = 'reporting_hotel_rate_comparison_facts_v1';

export const dashboardKpis: readonly DashboardKpiDefinition[] = [
  {
    id: 'gross-sales',
    title: 'فروش ناخالص',
    technicalName: 'Gross Sales',
    grain: 'یک قرارداد فروش یا قلم خدمت، پیش از refund',
    source: [salesContract, serviceItem],
    rule: 'جمع sale total رکوردهای واجد وضعیت فروش در grain منبع',
    exclusions: 'void، test و sandbox به‌صورت پیش‌فرض خارج‌اند.',
    dateBasis: 'effective',
    currency: 'required',
    permission: 'reports.dashboard.sales.read',
    role: 'outcome',
    decision: 'آیا حجم فروش در مسیر و خدمت هدف قرار دارد؟',
    comparison: 'دوره قبل، کانال و نوع خدمت',
    reportCode: 'RPT-002',
  },
  {
    id: 'net-sales',
    title: 'فروش خالص',
    technicalName: 'Net Sales',
    grain: 'قرارداد/قلم خدمت با refund allocation تأییدشده',
    source: [salesContract, serviceItem, payment],
    rule: 'Gross Sales منهای completed refund و تخفیف طبق policy',
    exclusions: 'درخواست refund تکمیل‌نشده و ارز بدون policy تبدیل خارج است.',
    dateBasis: 'effective',
    currency: 'required',
    permission: 'reports.dashboard.sales.read',
    openDecision: 'DEC-OPEN-004',
    role: 'outcome',
    decision: 'رشد واقعی درآمد پس از تخفیف و استرداد چقدر است؟',
    comparison: 'دوره قبل و ارز مستقل',
    reportCode: 'RPT-001',
  },
  {
    id: 'collected',
    title: 'وصول',
    technicalName: 'Collected Amount',
    grain: 'یک تراکنش پرداخت',
    source: [payment],
    rule: 'فقط paymentهای VERIFIED یا SETTLED پس از reversal',
    exclusions: 'pending، failed، void و reversed خارج‌اند.',
    dateBasis: 'paid',
    currency: 'required',
    permission: 'reports.dashboard.finance.read',
    role: 'outcome',
    decision: 'چه مقدار از فروش واقعاً به وجه تأییدشده تبدیل شده است؟',
    comparison: 'دوره قبل، روش پرداخت و ارز',
    reportCode: 'RPT-008',
  },
  {
    id: 'refunded',
    title: 'استرداد',
    technicalName: 'Refunded Amount',
    grain: 'یک refund/payment transaction',
    source: [payment],
    rule: 'فقط refundهای COMPLETED',
    exclusions: 'refund request مبلغ نهایی محسوب نمی‌شود.',
    dateBasis: 'paid',
    currency: 'required',
    permission: 'reports.dashboard.finance.read',
    role: 'guardrail',
    decision: 'حجم خروج نقدی ناشی از استرداد چقدر است؟',
    comparison: 'دوره قبل و علت استرداد',
    reportCode: 'RPT-008',
  },
  {
    id: 'gross-profit',
    title: 'سود ناخالص',
    technicalName: 'Gross Profit',
    grain: 'یک قلم خدمت قرارداد',
    source: [serviceItem, 'reporting_purchase_request_facts'],
    rule: 'recognized sale revenue منهای matched purchase cost و تعدیلات مستقیم',
    exclusions:
      'بدون policy نهایی FX، tax، rounding و recognition منتشر نمی‌شود.',
    dateBasis: 'policy-dependent',
    currency: 'required',
    permission: 'reports.dashboard.profit.read',
    openDecision: 'DEC-OPEN-004',
    role: 'outcome',
    decision: 'کدام قرارداد و خدمت ارزش اقتصادی واقعی ایجاد می‌کند؟',
    comparison: 'خدمت، قرارداد و دوره قبل',
    reportCode: 'RPT-004',
  },
  {
    id: 'receivables',
    title: 'مطالبات',
    technicalName: 'Receivables',
    grain: 'حساب/طرف حساب در زمان as-of',
    source: [journalBalance],
    rule: 'مانده فقط از invoice/journal posted معتبر',
    exclusions: 'draft و void خارج‌اند.',
    dateBasis: 'as-of',
    currency: 'required',
    permission: 'reports.dashboard.finance.read',
    openDecision: 'DEC-OPEN-001',
    role: 'guardrail',
    decision: 'چه میزان از منابع شرکت نزد طرف‌حساب‌ها باقی مانده است؟',
    comparison: 'طرف‌حساب، سن مانده و ارز',
    reportCode: 'RPT-005',
  },
  {
    id: 'provider-payables',
    title: 'بدهی Provider',
    technicalName: 'Provider Payables',
    grain: 'Provider/account در زمان as-of',
    source: ['reporting_purchase_request_facts', journalBalance],
    rule: 'Purchase Invoice تأییدشده با reconciliation معتبر',
    exclusions: 'درخواست خرید و invoice تأییدنشده بدهی قطعی نیست.',
    dateBasis: 'as-of',
    currency: 'required',
    permission: 'reports.dashboard.finance.read',
    role: 'guardrail',
    decision: 'تعهد نقدی نزدیک شرکت به Providerها چقدر است؟',
    comparison: 'Provider، سررسید و ارز',
    reportCode: 'RPT-023',
  },
  {
    id: 'account-balance',
    title: 'مانده حساب',
    technicalName: 'Account Balance',
    grain: 'account/currency/day',
    source: [journalBalance],
    rule: 'جمع posted journal lines در همان account/currency',
    exclusions: 'draft، void و جمع ارزهای تبدیل‌نشده خارج‌اند.',
    dateBasis: 'as-of',
    currency: 'required',
    permission: 'reports.dashboard.balance.read',
    openDecision: 'DEC-OPEN-001',
    role: 'diagnostic',
    decision: 'کدام حساب ظرفیت پرداخت یا نیاز به انتقال دارد؟',
    comparison: 'حساب، بانک و ارز',
    reportCode: 'RPT-006',
  },
  {
    id: 'new-orders',
    title: 'قراردادهای جدید',
    technicalName: 'New Orders / Contracts',
    grain: 'یک قرارداد فروش',
    source: [salesContract],
    rule: 'تعداد قرارداد ایجادشده در بازه',
    exclusions: 'test/sandbox خارج است.',
    dateBasis: 'created',
    currency: 'not-applicable',
    permission: 'reports.dashboard.sales.read',
    role: 'driver',
    decision: 'آیا ورودی قرارداد برای تحقق فروش آینده کافی است؟',
    comparison: 'دوره قبل، کانال و کارشناس',
    reportCode: 'RPT-020',
  },
  {
    id: 'awaiting-payment',
    title: 'در انتظار پرداخت',
    technicalName: 'Awaiting Payment',
    grain: 'یک قرارداد فعال',
    source: [salesContract, payment],
    rule: 'قرارداد فعال با outstanding amount تأییدشده',
    exclusions: 'قرارداد لغوشده خارج است.',
    dateBasis: 'effective',
    currency: 'required',
    permission: 'reports.dashboard.sales.read',
    role: 'driver',
    decision: 'کدام قرارداد نیازمند پیگیری مالی فوری است؟',
    comparison: 'مدت انتظار، مسئول و ارز',
    reportCode: 'RPT-001',
  },
  {
    id: 'awaiting-issue',
    title: 'در انتظار صدور',
    technicalName: 'Awaiting Issue',
    grain: 'یک reservation واجد شرایط',
    source: [reservation],
    rule: 'reservation پرداخت‌شده بدون issue نهایی',
    exclusions: 'لغو، void و فاقد eligibility خارج‌اند.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.operations.read',
    role: 'driver',
    decision: 'حجم صف صدور و ظرفیت عملیاتی مورد نیاز چقدر است؟',
    comparison: 'Provider، خدمت و زمان انتظار',
    reportCode: 'RPT-009',
  },
  {
    id: 'paid-not-issued',
    title: 'پرداخت موفق بدون صدور',
    technicalName: 'Paid Not Issued',
    grain: 'یک قرارداد/reservation',
    source: [payment, reservation],
    rule: 'verified allocated payment و issue غیر ISSUED پس از threshold',
    exclusions: 'threshold و eligibility باید در projection نسخه‌دار باشد.',
    dateBasis: 'paid',
    currency: 'not-applicable',
    permission: 'reports.dashboard.operations.read',
    role: 'guardrail',
    decision: 'کدام پرداخت تأییدشده در معرض شکست تحویل است؟',
    comparison: 'زمان انتظار، Provider و خدمت',
    reportCode: 'RPT-009',
  },
  {
    id: 'issued-documents',
    title: 'اسناد صادرشده',
    technicalName: 'Issued Documents',
    grain: 'یک سند صادرشده برای هر مسافر',
    source: [ticket],
    rule: 'تعداد issued document نهایی در بازه',
    exclusions: 'void خارج است.',
    dateBasis: 'issued',
    currency: 'not-applicable',
    permission: 'reports.dashboard.operations.read',
    role: 'outcome',
    decision: 'چه تعداد خدمت با موفقیت به سند نهایی تبدیل شده است؟',
    comparison: 'دوره قبل، مسیر و ایرلاین',
    reportCode: 'RPT-015',
  },
  {
    id: 'cancelled-orders',
    title: 'قراردادهای لغوشده',
    technicalName: 'Cancelled Orders',
    grain: 'یک transition لغو قرارداد',
    source: [salesContract],
    rule: 'تعداد transitionهای cancellation در بازه',
    exclusions: 'وضعیت snapshot بدون رخداد زمانی جایگزین transition نیست.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.sales.read',
    role: 'guardrail',
    decision: 'آیا لغوها رشد فروش را خنثی می‌کنند؟',
    comparison: 'دوره قبل، علت و خدمت',
    reportCode: 'RPT-011',
  },
  {
    id: 'cancelled-reservations',
    title: 'رزروهای لغوشده',
    technicalName: 'Cancelled Reservations',
    grain: 'یک رخداد لغو رزرو',
    source: [reservation],
    rule: 'تعداد رزروهایی که در بازه انتخابی به وضعیت لغوشده منتقل شده‌اند',
    exclusions:
      'لغو قرارداد بدون رخداد لغو رزرو، رزرو آزمایشی و transition تکراری خارج‌اند.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.operations.read',
    role: 'guardrail',
    decision: 'تعداد و علت لغو رزروها در بازه انتخابی چگونه تغییر کرده است؟',
    comparison: 'دوره قبل، نوع خدمت و علت لغو',
    reportCode: 'RPT-011',
  },
  {
    id: 'new-customers',
    title: 'مشتریان جدید',
    technicalName: 'New Customers',
    grain: 'یک مشتری در تاریخ اولین خرید موفق',
    source: [salesContract, payment],
    rule:
      'تعداد یکتای مشتریانی که نخستین خرید پرداخت‌شده آن‌ها در بازه انتخابی ثبت شده است',
    exclusions:
      'ثبت‌نام بدون خرید، پرداخت ناموفق یا برگشت‌شده و مشتری تکراری خارج‌اند.',
    dateBasis: 'paid',
    currency: 'not-applicable',
    permission: 'reports.dashboard.customers.read',
    role: 'driver',
    decision: 'در بازه انتخابی چند مشتری برای نخستین بار خرید کرده‌اند؟',
    comparison: 'دوره قبل، کانال جذب و نوع مشتری',
    reportCode: 'RPT-036',
  },
  {
    id: 'returning-customers',
    title: 'مشتریان بازگشتی',
    technicalName: 'Returning Customers',
    grain: 'یک مشتری دارای خرید پیشین و خرید موفق در بازه',
    source: [salesContract, payment],
    rule:
      'تعداد یکتای مشتریانی که پیش از شروع بازه حداقل یک خرید موفق و در بازه انتخابی نیز خرید موفق داشته‌اند',
    exclusions:
      'مشتری فقط با یک خرید، پرداخت ناموفق یا برگشت‌شده و قرارداد آزمایشی خارج‌اند.',
    dateBasis: 'paid',
    currency: 'not-applicable',
    permission: 'reports.dashboard.customers.read',
    role: 'outcome',
    decision: 'چه تعداد مشتری دوباره از خدمات شرکت خرید کرده‌اند؟',
    comparison: 'دوره قبل، کانال جذب و نوع خدمت',
    reportCode: 'RPT-036',
  },
  {
    id: 'customer-interest-coverage',
    title: 'مشتریان دارای علاقه ثبت‌شده',
    technicalName: 'Customer Interest Coverage',
    grain: 'یک مشتری با حداقل یک سیگنال علاقه معتبر در بازه',
    source: [leadPipeline, salesContract, serviceItem],
    rule:
      'تعداد یکتای مشتریانی که در بازه انتخابی حداقل یک مقصد یا خدمت را در لید متصل به مشتری درخواست کرده‌اند یا خرید موفق همان مقصد یا خدمت را داشته‌اند',
    exclusions:
      'لید بدون customerId، متن آزاد طبقه‌بندی‌نشده، خرید ناموفق یا برگشت‌شده و مشتری ادغام‌شده خارج‌اند.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.customers.read',
    role: 'driver',
    decision: 'برای چه سهمی از مشتریان می‌توان پیشنهاد مقصد یا خدمت مرتبط ساخت؟',
    comparison: 'نوع علاقه، مقصد، خدمت و دوره قبل',
    reportCode: 'RPT-025',
  },
  {
    id: 'customer-destination-demand',
    title: 'مقصدهای مورد تقاضای مشتریان',
    technicalName: 'Customer Destination Demand',
    grain: 'یک سفارش یا رزرو معتبر و مقصد',
    source: [travelFacts],
    rule:
      'تعداد سفارش‌های یکتای معتبر دارای مقصد در بازه انتخابی؛ تعداد مسافر به‌عنوان اندازه تقاضای مکمل و جداگانه نمایش داده می‌شود',
    exclusions:
      'سفارش آزمایشی یا لغوشده، مقصد نامشخص و شمارش تکراری اقلام یک سفارش خارج‌اند.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.customers.read',
    role: 'diagnostic',
    decision: 'کدام مقصدها بیشترین تقاضای ثبت‌شده مشتری را دارند؟',
    comparison: 'مقصد، مسیر و دوره قبل',
    reportCode: 'RPT-019',
  },
  {
    id: 'customer-service-usage',
    title: 'مشتریان استفاده‌کننده از خدمات',
    technicalName: 'Customers Using Services',
    grain: 'یک مشتری و نوع خدمت در خرید موفق',
    source: [salesContract, serviceItem],
    rule:
      'تعداد یکتای مشتریان دارای حداقل یک قلم خدمت در خرید موفق، به تفکیک نوع خدمت در بازه انتخابی',
    exclusions:
      'خدمت پیش‌نویس یا لغوشده، خرید ناموفق یا برگشت‌شده و تکرار همان مشتری در یک نوع خدمت خارج‌اند.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.customers.read',
    role: 'driver',
    decision: 'کدام نوع خدمت بیشترین پوشش مشتری را ایجاد کرده است؟',
    comparison: 'نوع خدمت، تعداد مشتری و دوره قبل',
    reportCode: 'RPT-002',
  },
  {
    id: 'customers-by-acquisition-channel',
    title: 'مشتریان منتسب به کانال جذب',
    technicalName: 'Customers by Acquisition Channel',
    grain: 'یک مشتری و روش آشنایی معتبر',
    source: [customerPortfolio],
    rule:
      'تعداد یکتای مشتریان فعال یا جدید دارای روش آشنایی ثبت‌شده، به تفکیک کانال جذب در بازه انتخابی',
    exclusions:
      'روش آشنایی نامشخص، مشتری ادغام‌شده یا غیرفعال خارج از بازه و انتساب‌های فاقد سیاست معتبر خارج‌اند.',
    dateBasis: 'created',
    currency: 'not-applicable',
    permission: 'reports.dashboard.customers.read',
    role: 'diagnostic',
    decision: 'کدام کانال بیشترین مشتری جدید و فعال را وارد سبد کرده است؟',
    comparison: 'کانال جذب، دوره قبل و نوع مشتری',
    reportCode: 'RPT-036',
  },
  {
    id: 'open-tickets',
    title: 'Ticketهای باز',
    technicalName: 'Open Tickets',
    grain: 'یک Ticket در زمان as-of',
    source: ['approved_customer_affairs_ticket_projection'],
    rule: 'Ticket غیرنهایی در زمان as-of',
    exclusions: 'داده PII در summary نمایش داده نمی‌شود.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.support.read',
    openDecision: 'DEC-OPEN-009',
    role: 'driver',
    decision: 'حجم کار باز پشتیبانی و نیاز ظرفیت چقدر است؟',
    comparison: 'اولویت، دسته و واحد پاسخ‌گو',
    reportCode: 'RPT-013',
  },
  {
    id: 'overdue-tasks',
    title: 'وظایف عقب‌افتاده',
    technicalName: 'Overdue Tasks',
    grain: 'یک وظیفه در زمان as-of',
    source: ['approved_task_projection'],
    rule: 'وظیفهٔ باز با due_at پیش از زمان جاری',
    exclusions: 'وظیفهٔ نهایی یا خارج از scope مجاز نمایش داده نمی‌شود.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.tasks.read',
    role: 'guardrail',
    decision: 'کدام اقدام عملیاتی از موعد تصمیم عبور کرده است؟',
    comparison: 'اولویت، مسئول و مدت تأخیر',
    reportCode: 'RPT-030',
  },
  {
    id: 'due-checks',
    title: 'چک‌های نزدیک سررسید',
    technicalName: 'Due Checks',
    grain: 'یک چک فعال',
    source: ['approved_finance_check_projection'],
    rule: 'چک فعال با due date در بازه انتخابی',
    exclusions: 'void، settled و scope غیرمجاز خارج‌اند.',
    dateBasis: 'effective',
    currency: 'required',
    permission: 'reports.dashboard.finance.read',
    role: 'guardrail',
    decision: 'کدام چک باید برای تأمین نقدینگی یا وصول پیگیری شود؟',
    comparison: 'جهت، روز تا سررسید و ارز',
    reportCode: 'RPT-007',
  },
  {
    id: 'collection-rate',
    title: 'نرخ وصول',
    technicalName: 'Collection Rate',
    grain: 'قرارداد و ارز در بازه یکسان',
    source: [salesContract, payment],
    rule: 'مبلغ وصول‌شده تأییدشده تقسیم بر فروش قابل وصول همان cohort و ارز',
    exclusions: 'ارزهای متفاوت، قرارداد void و پرداخت reversed خارج‌اند.',
    dateBasis: 'paid',
    currency: 'not-applicable',
    permission: 'reports.dashboard.finance.read',
    role: 'outcome',
    decision: 'آیا سرعت تبدیل فروش به نقدینگی مناسب است؟',
    comparison: 'دوره قبل و هدف مصوب',
    reportCode: 'RPT-008',
  },
  {
    id: 'refund-rate',
    title: 'نرخ استرداد',
    technicalName: 'Refund Rate',
    grain: 'تراکنش تکمیل‌شده در cohort فروش',
    source: [payment, travelFacts],
    rule: 'مبلغ refund تکمیل‌شده تقسیم بر فروش واجد شرایط همان ارز',
    exclusions: 'درخواست‌های باز و refund ناموفق خارج‌اند.',
    dateBasis: 'paid',
    currency: 'not-applicable',
    permission: 'reports.dashboard.finance.read',
    role: 'guardrail',
    decision: 'آیا رشد فروش با افزایش نامطلوب استرداد همراه شده است؟',
    comparison: 'دوره قبل و نوع خدمت',
    reportCode: 'RPT-011',
  },
  {
    id: 'pipeline-age',
    title: 'میانگین توقف در مرحله',
    technicalName: 'Average Stage Age',
    grain: 'یک قرارداد در آخرین وضعیت معتبر',
    source: [salesPipeline],
    rule: 'میانگین مدت از آخرین transition تا زمان گزارش برای قراردادهای فعال',
    exclusions: 'قرارداد نهایی و transition ناقص خارج‌اند.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.sales.read',
    role: 'driver',
    decision: 'کدام مرحله فروش گلوگاه تبدیل است؟',
    comparison: 'مرحله، مسئول و دوره قبل',
    reportCode: 'RPT-020',
  },
  {
    id: 'reservation-failure-rate',
    title: 'نرخ خطای رزرو',
    technicalName: 'Reservation Failure Rate',
    grain: 'یک تلاش عملیاتی رزرو',
    source: [travelFacts],
    rule: 'تلاش‌های ناموفق تقسیم بر کل تلاش‌های واجد شرایط در همان عملیات',
    exclusions: 'خطاهای validation کاربر و retry تکراری خارج‌اند.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.operations.read',
    role: 'guardrail',
    decision: 'کدام Provider یا عملیات نیازمند اقدام فوری است؟',
    comparison: 'Provider، عملیات و دوره قبل',
    reportCode: 'RPT-010',
  },
  {
    id: 'delivery-blockers',
    title: 'رزروهای دارای مانع تحویل',
    technicalName: 'Delivery Blockers',
    grain: 'یک Reservation Intake',
    source: [deliveryReadiness],
    rule: 'تعداد رزروهای در جریان با حداقل یک مانع خرید، عملیات یا تأیید مالی',
    exclusions: 'رزرو تحویل‌شده یا لغوشده خارج است.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.operations.read',
    role: 'driver',
    decision: 'کدام مانع بیشترین صف تحویل را ایجاد کرده است؟',
    comparison: 'نوع مانع و زمان انتظار',
    reportCode: 'RPT-024',
  },
  {
    id: 'issue-success-rate',
    title: 'نرخ موفقیت صدور',
    technicalName: 'Issue Success Rate',
    grain: 'یک رزرو واجد صدور',
    source: [travelFacts],
    rule: 'رزروهای صادرشده تقسیم بر رزروهای واجد صدور در بازه',
    exclusions: 'رزروهای فاقد پرداخت معتبر یا لغوشده خارج‌اند.',
    dateBasis: 'issued',
    currency: 'not-applicable',
    permission: 'reports.dashboard.operations.read',
    role: 'outcome',
    decision: 'آیا عملیات پس از پرداخت به صدور نهایی منجر می‌شود؟',
    comparison: 'Provider، خدمت و دوره قبل',
    reportCode: 'RPT-009',
  },
  {
    id: 'active-offers',
    title: 'پیشنهادهای فعال سفر',
    technicalName: 'Active Travel Offers',
    grain: 'یک Published Ticket Offer',
    source: [ticketCapacity],
    rule: 'تعداد پیشنهادهای ACTIVE در بازه حرکت انتخابی',
    exclusions: 'نسخه غیرفعال، منقضی یا حذف‌شده خارج است.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.inventory.read',
    role: 'driver',
    decision: 'آیا پوشش محصول برای تقاضای پیش‌رو کافی است؟',
    comparison: 'مسیر و تاریخ حرکت',
    reportCode: 'RPT-022',
  },
  {
    id: 'sell-through-rate',
    title: 'نرخ تکمیل ظرفیت',
    technicalName: 'Sell-through Rate',
    grain: 'یک پیشنهاد پرواز و جهت',
    source: [ticketCapacity],
    rule: 'تخصیص فعال تقسیم بر ظرفیت کل همان پیشنهاد',
    exclusions: 'تخصیص آزادشده و ظرفیت نامعتبر خارج است.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.inventory.read',
    role: 'outcome',
    decision: 'کدام ظرفیت سریع‌تر یا کندتر از انتظار مصرف می‌شود؟',
    comparison: 'مسیر، کلاس و تاریخ حرکت',
    reportCode: 'RPT-022',
  },
  {
    id: 'remaining-capacity',
    title: 'ظرفیت باقی‌مانده',
    technicalName: 'Remaining Capacity',
    grain: 'یک پیشنهاد پرواز و جهت',
    source: [ticketCapacity],
    rule: 'ظرفیت کل منهای مجموع تخصیص فعال همان پیشنهاد',
    exclusions: 'تخصیص released یا لغوشده خارج است.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.inventory.read',
    role: 'diagnostic',
    decision: 'روی کدام مسیر باید فروش یا تأمین ظرفیت تنظیم شود؟',
    comparison: 'مسیر، کلاس و روز تا حرکت',
    reportCode: 'RPT-022',
  },
  {
    id: 'low-capacity-offers',
    title: 'عرضه‌های نزدیک تکمیل',
    technicalName: 'Low Capacity Offers',
    grain: 'یک Published Ticket Offer',
    source: [ticketCapacity],
    rule: 'پیشنهاد فعال زیر آستانه ظرفیت باقی‌مانده مصوب',
    exclusions: 'آستانه بدون policy منتشر نمی‌شود.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.inventory.read',
    role: 'guardrail',
    decision: 'کدام عرضه نیازمند افزایش ظرفیت یا توقف فروش است؟',
    comparison: 'روز تا حرکت و ظرفیت باقی‌مانده',
    reportCode: 'RPT-022',
  },
  {
    id: 'supplier-spend',
    title: 'خرید خالص تأییدشده',
    technicalName: 'Approved Net Purchase',
    grain: 'یک خرید خدمت و ارز',
    source: [travelFacts],
    rule: 'جمع خرید خالص آخرین نسخه تأییدشده در همان ارز',
    exclusions: 'پیش‌نویس، نسخه superseded و ارزهای تجمیع‌نشده خارج‌اند.',
    dateBasis: 'effective',
    currency: 'required',
    permission: 'reports.dashboard.procurement.read',
    role: 'outcome',
    decision: 'هزینه تأمین در کدام Supplier یا خدمت متمرکز است؟',
    comparison: 'تأمین‌کننده، خدمت و دوره قبل',
    reportCode: 'RPT-003',
  },
  {
    id: 'pending-supplier-payments',
    title: 'خریدهای منتظر پرداخت',
    technicalName: 'Pending Supplier Payments',
    grain: 'آخرین نسخه پرداخت هر خرید خدمت',
    source: [supplierPayments],
    rule: 'تعداد خریدهای دارای آخرین وضعیت غیرنهایی پرداخت',
    exclusions: 'نسخه‌های قدیمی و پرداخت نهایی خارج‌اند.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.procurement.read',
    role: 'guardrail',
    decision: 'کدام تعهد تأمین‌کننده عملیات را در معرض ریسک قرار می‌دهد؟',
    comparison: 'وضعیت، تأمین‌کننده و مسئول',
    reportCode: 'RPT-023',
  },
  {
    id: 'supplier-payment-wait',
    title: 'میانگین انتظار پرداخت تأمین‌کننده',
    technicalName: 'Supplier Payment Wait',
    grain: 'آخرین نسخه پرداخت هر خرید خدمت',
    source: [supplierPayments],
    rule: 'میانگین زمان از ثبت خرید تا وضعیت نهایی یا زمان گزارش',
    exclusions: 'نسخه‌های superseded و رکورد بدون مبنای زمانی خارج‌اند.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.procurement.read',
    role: 'driver',
    decision: 'گلوگاه تأیید و پرداخت خرید کجاست؟',
    comparison: 'بانک، مسئول و تأمین‌کننده',
    reportCode: 'RPT-023',
  },
  {
    id: 'overdue-balance',
    title: 'مانده سررسیدگذشته',
    technicalName: 'Overdue Balance',
    grain: 'طرف حساب، حساب و ارز در زمان as-of',
    source: ['reporting_counterparty_balance_facts_v1'],
    rule: 'جمع مانده Posted با سررسید قبل از زمان گزارش در همان ارز',
    exclusions: 'draft، void و مانده بدون سررسید معتبر خارج‌اند.',
    dateBasis: 'as-of',
    currency: 'required',
    permission: 'reports.dashboard.finance.read',
    role: 'guardrail',
    decision: 'کدام طرف حساب اولویت وصول یا تسویه دارد؟',
    comparison: 'طرف حساب، نوع و سن بدهی',
    reportCode: 'RPT-005',
  },
  {
    id: 'lead-volume',
    title: 'لیدهای فعال',
    technicalName: 'Active Leads',
    grain: 'یک لید امور مشتریان',
    source: [leadPipeline],
    rule: 'تعداد لیدهای غیرنهایی در زمان گزارش',
    exclusions: 'لید بسته، تکراری یا خارج از scope مجاز خارج است.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.crm.read',
    role: 'driver',
    decision: 'آیا حجم فرصت ورودی برای فروش آینده کافی است؟',
    comparison: 'مرحله، منبع و دوره قبل',
    reportCode: 'RPT-025',
  },
  {
    id: 'new-leads',
    title: 'لیدهای جدید',
    technicalName: 'New Leads',
    grain: 'یک لید ایجادشده در بازه',
    source: [leadPipeline],
    rule:
      'تعداد لیدهای ایجادشده در بازه انتخابی که هنوز به خرید موفق منتسب نشده‌اند',
    exclusions: 'لید تکراری، حذف‌شده یا تبدیل‌شده به خرید موفق خارج است.',
    dateBasis: 'created',
    currency: 'not-applicable',
    permission: 'reports.dashboard.crm.read',
    role: 'driver',
    decision: 'در بازه انتخابی چند فرصت فروش جدید وارد شده است؟',
    comparison: 'دوره قبل، روز، منبع و کانال ورودی',
    reportCode: 'RPT-025',
  },
  {
    id: 'lead-growth-rate',
    title: 'نرخ رشد لیدها',
    technicalName: 'Lead Growth Rate',
    grain: 'یک بازه و دوره پیشین هم‌طول',
    source: [leadPipeline],
    rule:
      '(تعداد لید جدید بازه جاری منهای تعداد لید جدید دوره قبل) تقسیم بر تعداد لید جدید دوره قبل؛ اگر مخرج صفر باشد نتیجه ناموجود است',
    exclusions: 'لید تکراری یا حذف‌شده و دوره‌های غیرهم‌طول خارج‌اند.',
    dateBasis: 'created',
    currency: 'not-applicable',
    permission: 'reports.dashboard.crm.read',
    role: 'diagnostic',
    decision: 'سرعت جذب لید نسبت به دوره قبل افزایش یافته یا کاهش یافته است؟',
    comparison: 'دوره قبل هم‌طول',
    reportCode: 'RPT-025',
  },
  {
    id: 'lead-conversion-rate',
    title: 'نرخ تبدیل لید به سفارش',
    technicalName: 'Lead-to-order Conversion',
    grain: 'cohort لید با انتساب سفارش معتبر',
    source: [leadPipeline, travelFacts],
    rule: 'لیدهای منتسب به سفارش تقسیم بر لیدهای واجد شرایط همان cohort',
    exclusions: 'لید بدون cohort کامل و انتساب مبهم خارج است.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.crm.read',
    role: 'outcome',
    decision: 'کدام منبع یا مرحله بیشترین تبدیل را ایجاد می‌کند؟',
    comparison: 'منبع لید، مسئول و cohort',
    reportCode: 'RPT-018',
  },
  {
    id: 'overdue-followups',
    title: 'پیگیری‌های عقب‌افتاده',
    technicalName: 'Overdue Lead Follow-ups',
    grain: 'یک لید با موعد اقدام بعدی',
    source: [leadPipeline],
    rule: 'لید فعال با next action قبل از زمان گزارش',
    exclusions: 'لید نهایی یا فاقد مسئول مجاز خارج است.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.crm.read',
    role: 'guardrail',
    decision: 'کدام فرصت در معرض از دست‌رفتن به‌علت تأخیر است؟',
    comparison: 'مسئول، مرحله و مدت تأخیر',
    reportCode: 'RPT-025',
  },
  {
    id: 'sla-breach-rate',
    title: 'نرخ نقض SLA',
    technicalName: 'SLA Breach Rate',
    grain: 'یک Ticket واجد SLA',
    source: [supportTickets],
    rule: 'Ticketهای ناقض SLA تقسیم بر Ticketهای واجد SLA',
    exclusions: 'Ticket بدون policy SLA مصوب خارج است.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.support.read',
    role: 'guardrail',
    decision: 'کدام دسته یا اولویت کیفیت خدمت را تهدید می‌کند؟',
    comparison: 'دسته، اولویت و دوره قبل',
    reportCode: 'RPT-013',
    openDecision: 'DEC-OPEN-009',
  },
  {
    id: 'first-response-time',
    title: 'میانگین زمان پاسخ نخست',
    technicalName: 'First Response Time',
    grain: 'یک Ticket دارای اولین پاسخ',
    source: [supportTickets],
    rule: 'میانگین فاصله ایجاد Ticket تا اولین پاسخ واجد شرایط',
    exclusions:
      'پیام خودکار و Ticket بدون پاسخ از میانگین خارج و جداگانه شمارش می‌شود.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.support.read',
    role: 'driver',
    decision: 'آیا ظرفیت پاسخ‌گویی با حجم درخواست‌ها متناسب است؟',
    comparison: 'اولویت، واحد و دوره قبل',
    reportCode: 'RPT-013',
  },
  {
    id: 'low-satisfaction',
    title: 'رضایت پایین نیازمند اقدام',
    technicalName: 'Low Satisfaction Actions',
    grain: 'یک پاسخ رضایت معتبر',
    source: [customerSatisfaction],
    rule: 'تعداد پاسخ‌های زیر آستانه مصوب با اقدام اصلاحی باز',
    exclusions: 'پاسخ ناقص، تکراری یا بدون رضایت ثبت‌شده خارج است.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.support.read',
    role: 'guardrail',
    decision: 'کدام تجربه مشتری نیازمند اصلاح فوری است؟',
    comparison: 'نوع خدمت و واحد پاسخ‌گو',
    reportCode: 'RPT-026',
  },
  {
    id: 'agency-sales',
    title: 'فروش آژانس‌ها',
    technicalName: 'Agency Sales',
    grain: 'قلم سفارش، آژانس و ارز',
    source: [travelFacts],
    rule: 'جمع فروش اقلام منتسب به آژانس در همان ارز',
    exclusions: 'فروش void و قلم بدون انتساب معتبر خارج است.',
    dateBasis: 'effective',
    currency: 'required',
    permission: 'reports.dashboard.b2b.read',
    role: 'outcome',
    decision: 'کدام شریک بیشترین فروش پایدار را ایجاد می‌کند؟',
    comparison: 'آژانس، کانال و دوره قبل',
    reportCode: 'RPT-017',
  },
  {
    id: 'agency-profit',
    title: 'سود ناخالص آژانس‌ها',
    technicalName: 'Agency Gross Profit',
    grain: 'قلم سفارش، آژانس و ارز',
    source: [travelFacts],
    rule: 'فروش مصوب منهای خرید خالص مصوب اقلام منتسب به آژانس',
    exclusions: 'هزینه unmatched و ارزهای تبدیل‌نشده خارج‌اند.',
    dateBasis: 'policy-dependent',
    currency: 'required',
    permission: 'reports.dashboard.b2b.read',
    role: 'outcome',
    decision: 'کدام همکاری ارزش اقتصادی واقعی ایجاد می‌کند؟',
    comparison: 'آژانس و نوع خدمت',
    reportCode: 'RPT-017',
    openDecision: 'DEC-OPEN-004',
  },
  {
    id: 'credit-at-risk',
    title: 'اعتبار در معرض ریسک',
    technicalName: 'Credit at Risk',
    grain: 'قرارداد آژانس و ارز',
    source: [agencyRisk],
    rule: 'مبلغ سقف اعتبار سیاست‌های فعال دارای ریسک انقضا یا اقدام overdue',
    exclusions: 'سیاست غیرفعال و ارزهای ادغام‌نشده خارج‌اند.',
    dateBasis: 'as-of',
    currency: 'required',
    permission: 'reports.dashboard.b2b.read',
    role: 'guardrail',
    decision: 'کدام حساب B2B باید محدود یا بازبینی شود؟',
    comparison: 'آژانس، ارز و روز تا انقضا',
    reportCode: 'RPT-021',
    openDecision: 'DEC-OPEN-008',
  },
  {
    id: 'expiring-guarantees',
    title: 'تضمین‌های نزدیک انقضا',
    technicalName: 'Expiring Guarantees',
    grain: 'یک تضمین قرارداد آژانس',
    source: [agencyRisk],
    rule: 'تعداد تضمین فعال با تاریخ انقضا در پنجره انتخابی',
    exclusions: 'تضمین آزادشده، ردشده یا superseded خارج است.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.b2b.read',
    role: 'guardrail',
    decision: 'کدام تضمین قبل از ادامه فروش باید تمدید شود؟',
    comparison: 'نوع تضمین و روز تا انقضا',
    reportCode: 'RPT-021',
  },
  {
    id: 'attributed-sales',
    title: 'فروش منتسب به کمپین',
    technicalName: 'Attributed Campaign Sales',
    grain: 'کمپین، touchpoint و ارز',
    source: [campaign],
    rule: 'جمع فروش منتسب طبق مدل attribution مصوب در همان ارز',
    exclusions: 'touchpoint بدون consent یا انتساب معتبر خارج است.',
    dateBasis: 'effective',
    currency: 'required',
    permission: 'reports.dashboard.marketing.read',
    role: 'outcome',
    decision: 'کدام کمپین درآمد قابل اتکاتری ایجاد کرده است؟',
    comparison: 'کمپین، کانال و دوره قبل',
    reportCode: 'RPT-012',
    openDecision: 'DEC-OPEN-012',
  },
  {
    id: 'campaign-conversion',
    title: 'نرخ تبدیل کمپین',
    technicalName: 'Campaign Conversion Rate',
    grain: 'کمپین و مخاطب واجد consent',
    source: [campaign],
    rule: 'conversionهای معتبر تقسیم بر مخاطبان تحویل‌شده واجد اندازه‌گیری',
    exclusions: 'ارسال ناموفق، لغو رضایت و denominator نامعتبر خارج‌اند.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.marketing.read',
    role: 'driver',
    decision: 'کدام پیام یا کانال بهتر به اقدام منجر می‌شود؟',
    comparison: 'کمپین، کانال و دوره قبل',
    reportCode: 'RPT-012',
  },
  {
    id: 'campaign-roas',
    title: 'بازده هزینه تبلیغات',
    technicalName: 'ROAS',
    grain: 'کمپین و ارز',
    source: [campaign],
    rule: 'فروش منتسب تقسیم بر هزینه ثبت‌شده کمپین در همان ارز/FX basis',
    exclusions: 'کمپین بدون هزینه یا attribution مصوب منتشر نمی‌شود.',
    dateBasis: 'policy-dependent',
    currency: 'not-applicable',
    permission: 'reports.dashboard.marketing.read',
    role: 'outcome',
    decision: 'بودجه کدام کمپین باید افزایش، کاهش یا متوقف شود؟',
    comparison: 'کمپین و هدف مصوب',
    reportCode: 'RPT-012',
    openDecision: 'DEC-OPEN-012',
  },
  {
    id: 'consent-coverage',
    title: 'پوشش رضایت بازاریابی',
    technicalName: 'Marketing Consent Coverage',
    grain: 'مشتری، هدف و کانال',
    source: [customerConsent],
    rule: 'مشتریان دارای آخرین consent معتبر تقسیم بر مشتریان واجد ارتباط',
    exclusions: 'لغو رضایت و وضعیت نامشخص از numerator خارج است.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.marketing.read',
    role: 'guardrail',
    decision: 'اندازه audience مجاز در هر کانال چقدر است؟',
    comparison: 'هدف ارتباط، کانال و نوع مشتری',
    reportCode: 'RPT-027',
  },
  {
    id: 'employee-workdays',
    title: 'روزهای کارکرد',
    technicalName: 'Employee Workdays',
    grain: 'کارمند و دوره گزارش',
    source: [employeePerformance],
    rule: 'جمع روزهای کارکرد ثبت‌شده و تأییدشده در دوره',
    exclusions: 'رکورد حذف‌شده یا پیش‌نویس خارج است.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.hr.read',
    role: 'driver',
    decision: 'ظرفیت کاری واقعی واحدها چگونه توزیع شده است؟',
    comparison: 'واحد، سمت و دوره قبل',
    reportCode: 'RPT-014',
  },
  {
    id: 'employee-leave',
    title: 'بار مرخصی',
    technicalName: 'Leave Load',
    grain: 'کارمند، نوع مرخصی و سال',
    source: [employeePerformance],
    rule: 'جمع روزهای مرخصی تأییدشده در دوره انتخابی',
    exclusions: 'درخواست ردشده یا لغوشده خارج است.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.hr.read',
    role: 'guardrail',
    decision: 'کدام واحد در معرض کمبود ظرفیت قرار دارد؟',
    comparison: 'واحد و دوره قبل',
    reportCode: 'RPT-014',
  },
  {
    id: 'employee-overtime',
    title: 'اضافه‌کاری',
    technicalName: 'Overtime',
    grain: 'کارمند و دوره گزارش',
    source: [employeePerformance],
    rule: 'جمع اضافه‌کاری ثبت‌شده و تأییدشده در دوره',
    exclusions: 'رکورد پیش‌نویس یا خارج از policy خارج است.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.hr.read',
    role: 'guardrail',
    decision: 'آیا فشار کاری یا کمبود نیروی پایدار وجود دارد؟',
    comparison: 'واحد، سمت و دوره قبل',
    reportCode: 'RPT-014',
  },
  {
    id: 'employee-performance',
    title: 'امتیاز ارزیابی عملکرد',
    technicalName: 'Performance Score',
    grain: 'آخرین ارزیابی معتبر هر کارمند در دوره',
    source: [employeePerformance],
    rule: 'میانگین وزنی فقط طبق روش ارزیابی منتشرشده در Projection',
    exclusions: 'ارزیابی ناقص یا فاقد روش معتبر خارج است.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.hr.read',
    role: 'outcome',
    decision: 'کدام واحد به توسعه عملکرد یا بازتوزیع ظرفیت نیاز دارد؟',
    comparison: 'واحد، سمت و دوره ارزیابی',
    reportCode: 'RPT-014',
  },
  {
    id: 'expiring-hr-records',
    title: 'سوابق نزدیک انقضا',
    technicalName: 'Expiring HR Records',
    grain: 'یک HR Record فعال',
    source: [hrRecordExpiry],
    rule: 'تعداد سوابق فعال با expiresAt در پنجره انتخابی',
    exclusions: 'رکورد حذف‌شده یا superseded خارج است.',
    dateBasis: 'effective',
    currency: 'not-applicable',
    permission: 'reports.dashboard.hr.read',
    role: 'guardrail',
    decision: 'کدام مدرک یا قرارداد پیش از انقضا نیازمند اقدام است؟',
    comparison: 'نوع سابقه و روز تا انقضا',
    reportCode: 'RPT-029',
  },
  {
    id: 'incomplete-hr-records',
    title: 'سوابق ناقص کارکنان',
    technicalName: 'Incomplete HR Records',
    grain: 'یک HR Record فعال',
    source: [hrRecordExpiry],
    rule: 'تعداد سوابق فعال دارای وضعیت یا فیلد تکمیل‌نشده در Projection',
    exclusions: 'رکورد حذف‌شده و موارد غیرالزامی خارج‌اند.',
    dateBasis: 'as-of',
    currency: 'not-applicable',
    permission: 'reports.dashboard.hr.read',
    role: 'guardrail',
    decision: 'کدام پرونده پرسنلی مانع عملیات یا انطباق است؟',
    comparison: 'نوع سابقه و واحد',
    reportCode: 'RPT-029',
  },
] as const;

const visual = (
  id: string,
  title: string,
  description: string,
  kind: DashboardVisualKind,
  source: readonly string[],
  permission: string,
  drilldown: string,
  openDecision?: string,
): DashboardVisualDefinition => ({
  id,
  title,
  description,
  kind,
  source,
  permission,
  drilldown,
  openDecision,
});

export const dashboardPages: readonly DashboardPageDefinition[] = [
  {
    id: 'executive-overview',
    title: 'نمای مدیریتی',
    technicalName: 'Executive Overview',
    description:
      'فروش، مشتری، لید، لغو رزرو، سود و وضعیت نقدینگی در بازه انتخابی.',
    kpiIds: [
      'net-sales',
      'collected',
      'new-customers',
      'returning-customers',
      'new-leads',
      'lead-growth-rate',
      'lead-conversion-rate',
      'cancelled-reservations',
      'gross-profit',
      'receivables',
      'provider-payables',
      'account-balance',
    ],
    visualizations: [
      visual(
        'executive-trend',
        'روند فروش، وصول و سود',
        'مقایسه دوره‌ای فروش خالص، وصول و سود ناخالص به تفکیک ارز.',
        'line',
        [travelFacts],
        'reports.dashboard.executive.read',
        '/reports?report=contract_service_profit',
      ),
      visual(
        'executive-sales-by-service',
        'فروش بر اساس نوع خدمت',
        'مقایسه مبلغ فروش پرداخت‌شده خدمات در بازه انتخابی، بدون ادغام ارزهای تبدیل‌نشده.',
        'bar',
        [travelFacts, payment],
        'reports.dashboard.executive.read',
        '/reports?report=sales_by_service_route',
      ),
      visual(
        'executive-customer-retention',
        'مشتریان جدید و بازگشتی',
        'مقایسه مشتریان دارای اولین خرید با مشتریان دارای خرید مجدد در دوره‌های هم‌طول.',
        'stacked-bar',
        [salesContract, payment],
        'reports.dashboard.executive.read',
        '/reports?report=customer_portfolio_growth',
      ),
      visual(
        'executive-lead-acquisition',
        'روند روزانه جذب لید',
        'تعداد لیدهای جدید هر روز، نرخ رشد نسبت به دوره قبل و وضعیت تبدیل یا از‌دست‌رفتن.',
        'line',
        [leadPipeline],
        'reports.dashboard.executive.read',
        '/reports?report=lead_pipeline',
      ),
      visual(
        'executive-lead-conversion',
        'تبدیل لید به فروش',
        'تعداد لیدهای واجد شرایط، سفارش‌های منتسب و مبلغ فروش به تفکیک منبع و بازه.',
        'funnel',
        [leadPipeline, travelFacts],
        'reports.dashboard.executive.read',
        '/reports?report=lead_to_order_conversion',
      ),
      visual(
        'executive-reservation-cancellations',
        'روند و دلایل لغو رزرو',
        'مقایسه تعداد لغو رزرو بر اساس نوع خدمت، دوره و علت ثبت‌شده.',
        'stacked-bar',
        [reservation],
        'reports.dashboard.executive.read',
        '/reports?report=cancellations_refunds',
      ),
      visual(
        'executive-cash-exposure',
        'ترکیب مطالبات و بدهی‌ها',
        'مقایسه مانده سررسیدشده مشتریان و تعهدات تأمین‌کنندگان بدون ادغام ارزها.',
        'bar',
        ['reporting_counterparty_balance_facts_v1'],
        'reports.dashboard.executive.read',
        '/reports?report=receivables_payables',
      ),
      visual(
        'executive-exceptions',
        'استثناهای نیازمند تصمیم',
        'پرداخت بدون صدور، مانع تحویل، چک سررسید و پرداخت معوق تأمین‌کننده.',
        'queue',
        [travelFacts, deliveryReadiness, supplierPayments],
        'reports.dashboard.executive.read',
        '/reports?report=reservation_delivery_readiness',
      ),
    ],
  },
  {
    id: 'commercial-performance',
    title: 'عملکرد تجاری',
    technicalName: 'Commercial Performance',
    description: 'فروش، کانال، نوع خدمت و عملکرد تجاری در بازه انتخابی.',
    kpiIds: [
      'gross-sales',
      'net-sales',
      'new-orders',
      'pipeline-age',
      'cancelled-orders',
    ],
    visualizations: [
      visual(
        'sales-channel',
        'کانال فروش',
        'مقایسه مرتب‌شده Sales Channelها.',
        'bar',
        [salesContract],
        'reports.dashboard.sales.read',
        '/reports',
      ),
      visual(
        'service-type',
        'نوع خدمت',
        'ترکیب محدود خدمات در grain قلم قرارداد.',
        'stacked-bar',
        [serviceItem],
        'reports.dashboard.sales.read',
        '/reports',
      ),
      visual(
        'agent-ranking',
        'عملکرد کارشناس',
        'رتبه‌بندی permission-aware بدون افشای خارج از scope.',
        'bar',
        [salesContract],
        'reports.dashboard.sales.read',
        '/reports',
      ),
      visual(
        'commercial-pipeline',
        'قیف و عمر قراردادها',
        'تعداد، مبلغ و میانگین توقف قراردادها در هر وضعیت فروش، رزرو و تسویه.',
        'funnel',
        [salesPipeline],
        'reports.dashboard.sales.read',
        '/reports?report=sales_contract_pipeline',
      ),
    ],
  },
  {
    id: 'revenue-collections',
    title: 'وصول و درآمد',
    technicalName: 'Revenue & Collections',
    description: 'وصول، refund، مطالبات و روند درآمد با مبنای تاریخ مشخص.',
    kpiIds: [
      'collected',
      'collection-rate',
      'refunded',
      'refund-rate',
      'receivables',
      'overdue-balance',
    ],
    visualizations: [
      visual(
        'sales-collection-trend',
        'روند فروش و وصول',
        'Net Sales، Collected Amount و Refunded Amount در طول زمان.',
        'line',
        [salesContract, payment],
        'reports.dashboard.sales.read',
        '/reports',
      ),
      visual(
        'collection-status',
        'وضعیت تسویه قراردادها',
        'ترکیب مانده پرداخت‌نشده، نیمه‌تسویه و تسویه‌شده در grain قرارداد و ارز.',
        'stacked-bar',
        [salesContract, payment],
        'reports.dashboard.finance.read',
        '/reports?report=sales_by_organization',
      ),
      visual(
        'overdue-counterparties',
        'مطالبات سررسیدگذشته',
        'طرف‌حساب‌های دارای بیشترین مانده سررسیدشده با سن بدهی و ارز مستقل.',
        'bar',
        ['reporting_counterparty_balance_facts_v1'],
        'reports.dashboard.finance.read',
        '/reports?report=receivables_payables',
      ),
    ],
  },
  {
    id: 'travel-operations',
    title: 'عملیات سفر و صدور',
    technicalName: 'Travel Operations',
    description: 'مسیر قرارداد تا صدور و استثناهای Paid Not Issued/Failure.',
    kpiIds: [
      'awaiting-issue',
      'paid-not-issued',
      'issue-success-rate',
      'reservation-failure-rate',
      'delivery-blockers',
      'issued-documents',
    ],
    visualizations: [
      visual(
        'issue-funnel',
        'قیف عملیات',
        'New → Awaiting Payment → Paid → Awaiting Issue → Issued.',
        'funnel',
        [salesContract, payment, reservation, ticket],
        'reports.dashboard.operations.read',
        '/reports',
      ),
      visual(
        'issue-alerts',
        'استثناهای صدور',
        'پرداخت موفق بدون صدور و خطاهای Provider.',
        'queue',
        [reservation, ticket],
        'reports.dashboard.operations.read',
        '/reports',
      ),
      visual(
        'provider-failure-rate',
        'نرخ خطا به تفکیک Provider',
        'مقایسه نرخ شکست، تعداد خطا و مدت رفع در عملیات‌های قابل retry.',
        'bar',
        [travelFacts],
        'reports.dashboard.operations.read',
        '/reports?report=reservation_errors',
      ),
    ],
  },
  {
    id: 'inventory-products',
    title: 'ظرفیت و محصولات سفر',
    technicalName: 'Inventory & Travel Products',
    description: 'پوشش محصول، ظرفیت قابل فروش و وضعیت عرضه‌کنندگان.',
    kpiIds: [
      'active-offers',
      'sell-through-rate',
      'remaining-capacity',
      'low-capacity-offers',
    ],
    visualizations: [
      visual(
        'inventory-capacity',
        'مصرف ظرفیت به تفکیک مسیر',
        'ظرفیت کل، تخصیص فعال و ظرفیت باقی‌مانده برای هر مسیر و کلاس.',
        'stacked-bar',
        [ticketCapacity],
        'reports.dashboard.inventory.read',
        '/reports?report=ticket_capacity',
      ),
      visual(
        'inventory-departure-curve',
        'ظرفیت تا تاریخ حرکت',
        'روند تکمیل ظرفیت نسبت به روزهای باقی‌مانده تا حرکت.',
        'line',
        [ticketCapacity],
        'reports.dashboard.inventory.read',
        '/reports?report=ticket_capacity',
      ),
      visual(
        'inventory-action-queue',
        'عرضه‌های نیازمند اقدام',
        'پروازهای نزدیک تکمیل، کم‌فروش یا فاقد ظرفیت قابل اتکا برای تصمیم قیمت و تأمین.',
        'queue',
        [ticketCapacity],
        'reports.dashboard.inventory.read',
        '/ticket-management',
      ),
    ],
  },
  {
    id: 'procurement-suppliers',
    title: 'خرید و تأمین‌کنندگان',
    technicalName: 'Procurement & Suppliers',
    description: 'خرید، هزینه matched، سود معتبر و عملکرد Provider.',
    kpiIds: [
      'supplier-spend',
      'gross-profit',
      'provider-payables',
      'pending-supplier-payments',
      'supplier-payment-wait',
    ],
    visualizations: [
      visual(
        'supplier-spend-share',
        'سهم خرید تأمین‌کنندگان',
        'خرید خالص تأییدشده به تفکیک تأمین‌کننده، Provider و نوع خدمت.',
        'bar',
        [travelFacts],
        'reports.dashboard.procurement.read',
        '/reports?report=purchase_by_supplier',
      ),
      visual(
        'supplier-payment-status',
        'وضعیت پرداخت خریدها',
        'تعداد و مبلغ خریدها در هر وضعیت پرداخت با مدت انتظار.',
        'stacked-bar',
        [supplierPayments],
        'reports.dashboard.procurement.read',
        '/reports?report=supplier_payment_queue',
      ),
      visual(
        'supplier-action-queue',
        'صف تعهدات تأمین‌کننده',
        'خریدهای منتظر تأیید یا پرداخت که می‌توانند تحویل سفر را متوقف کنند.',
        'queue',
        [supplierPayments, deliveryReadiness],
        'reports.dashboard.procurement.read',
        '/reports?report=supplier_payment_queue',
      ),
      visual(
        'hotel-rate-comparison',
        'مقایسه نرخ خرید هتل',
        'نرخ نهایی ثبت‌شده برای هتل و بازه اقامت به تفکیک تأمین‌کننده و ارز.',
        'bar',
        [hotelRates],
        'reports.dashboard.procurement.read',
        '/reports?report=hotel_rate_comparison',
      ),
    ],
  },
  {
    id: 'finance-treasury',
    title: 'مالی و خزانه‌داری',
    technicalName: 'Finance & Treasury',
    description: 'گردش پرداخت، refund، مانده‌ها و چک‌های سررسید.',
    kpiIds: [
      'collected',
      'refunded',
      'receivables',
      'overdue-balance',
      'provider-payables',
      'account-balance',
      'due-checks',
    ],
    visualizations: [
      visual(
        'treasury-flow',
        'گردش خزانه',
        'نمایش currency و as-of برای هر series.',
        'line',
        [payment, journalBalance],
        'reports.dashboard.finance.read',
        '/reports',
        'DEC-OPEN-001 / DEC-OPEN-004',
      ),
      visual(
        'due-checks-queue',
        'اولویت چک‌ها',
        'لیست سررسید با severity و owner.',
        'queue',
        ['approved_finance_check_projection'],
        'reports.dashboard.finance.read',
        '/finance',
      ),
      visual(
        'counterparty-exposure',
        'ریسک طرف‌حساب‌ها',
        'مطالبات، بدهی و مانده سررسیدگذشته به تفکیک نوع طرف‌حساب و ارز.',
        'bar',
        ['reporting_counterparty_balance_facts_v1'],
        'reports.dashboard.finance.read',
        '/reports?report=receivables_payables',
      ),
    ],
  },
  {
    id: 'customer-growth',
    title: 'مشتری و رشد',
    technicalName: 'Customer & Growth',
    description: 'نمای یکپارچهٔ چرخه مشتری، کیفیت خدمت و رشد کانال‌ها.',
    kpiIds: [
      'new-orders',
      'lead-volume',
      'lead-conversion-rate',
      'customer-interest-coverage',
      'customer-destination-demand',
      'customer-service-usage',
      'customers-by-acquisition-channel',
      'consent-coverage',
      'open-tickets',
      'low-satisfaction',
    ],
    visualizations: [
      visual(
        'customer-growth-overview',
        'روند جذب تا سفارش',
        'حجم لید، سفارش و نرخ تبدیل در cohortهای هم‌دوره و قابل مقایسه.',
        'line',
        [leadPipeline, travelFacts],
        'reports.dashboard.customer-growth.read',
        '/reports?report=lead_to_order_conversion',
      ),
      visual(
        'customer-source-quality',
        'کیفیت منابع جذب',
        'مقایسه سفارش و ارزش فروش منتسب به هر منبع لید، بدون ادعای علیت.',
        'bar',
        [travelFacts],
        'reports.dashboard.customer-growth.read',
        '/reports?report=lead_to_order_conversion',
      ),
      visual(
        'customer-interest-distribution',
        'علایق ثبت‌شده مشتریان',
        'مقایسه تعداد مشتریان دارای سیگنال صریح درخواست یا خرید برای هر مقصد و نوع خدمت؛ هر مشتری در هر دسته فقط یک‌بار شمرده می‌شود.',
        'bar',
        [leadPipeline, travelFacts],
        'reports.dashboard.customer-growth.read',
        '/reports?report=lead_pipeline',
      ),
      visual(
        'customer-destination-distribution',
        'مشتریان و تقاضا بر اساس مقصد',
        'مقایسه مقصدها با تعداد سفارش یکتا و تعداد مسافر؛ این دو شمارنده جدا می‌مانند و به‌جای یکدیگر تفسیر نمی‌شوند.',
        'bar',
        [travelFacts],
        'reports.dashboard.customer-growth.read',
        '/reports?report=route_passengers',
      ),
      visual(
        'customer-service-distribution',
        'مشتریان بر اساس نوع خدمت',
        'ترکیب مشتریان استفاده‌کننده از بلیت، تور، هتل، ویزا و بیمه همراه با تعداد سفارش؛ مبلغ فروش فقط در ارزهای مستقل مقایسه می‌شود.',
        'stacked-bar',
        [salesContract, serviceItem, travelFacts],
        'reports.dashboard.customer-growth.read',
        '/reports?report=sales_by_service_route',
      ),
      visual(
        'customer-acquisition-channel-mix',
        'ترکیب مشتریان بر اساس کانال جذب',
        'سهم و تعداد مشتریان جدید یا فعال به تفکیک روش آشنایی ثبت‌شده؛ کانال نامشخص جداگانه و بدون انتساب حدسی نمایش داده می‌شود.',
        'bar',
        [customerPortfolio],
        'reports.dashboard.customer-growth.read',
        '/reports?report=customer_portfolio_growth',
      ),
      visual(
        'customer-acquisition-channel-trend',
        'روند جذب مشتری به تفکیک کانال',
        'روند زمانی تعداد مشتریان جدید هر کانال در دوره‌های هم‌طول برای تشخیص رشد یا افت پایدار.',
        'line',
        [customerPortfolio],
        'reports.dashboard.customer-growth.read',
        '/reports?report=customer_portfolio_growth',
      ),
      visual(
        'customer-trust-guardrails',
        'رضایت و کیفیت خدمت',
        'پوشش consent، نقض SLA و رضایت پایین به‌عنوان guardrail رشد.',
        'stacked-bar',
        [customerConsent, supportTickets, customerSatisfaction],
        'reports.dashboard.customer-growth.read',
        '/reports?report=customer_satisfaction',
      ),
    ],
  },
  {
    id: 'customer-crm',
    title: 'مشتری و CRM',
    technicalName: 'Customer & CRM',
    description: 'حجم لید، پیگیری، تبدیل و سرعت عبور قرارداد از مراحل فروش.',
    kpiIds: [
      'lead-volume',
      'overdue-followups',
      'lead-conversion-rate',
      'pipeline-age',
      'new-orders',
    ],
    visualizations: [
      visual(
        'crm-funnel',
        'قیف CRM',
        'Lead → Opportunity → Quotation → Contract با cohort صریح.',
        'funnel',
        [leadPipeline, salesPipeline],
        'reports.dashboard.crm.read',
        '/reports?report=lead_pipeline',
      ),
      visual(
        'lead-source-conversion',
        'تبدیل به تفکیک منبع لید',
        'مقایسه حجم لید، سفارش و نرخ تبدیل برای منابع قابل انتساب.',
        'bar',
        [leadPipeline, travelFacts],
        'reports.dashboard.crm.read',
        '/reports?report=lead_to_order_conversion',
      ),
      visual(
        'crm-followup-queue',
        'فرصت‌های نیازمند پیگیری',
        'لیدهای عقب‌افتاده و قراردادهای متوقف‌شده، مرتب‌شده براساس مدت انتظار.',
        'queue',
        [leadPipeline, salesPipeline],
        'reports.dashboard.crm.read',
        '/reports?report=lead_pipeline',
      ),
    ],
  },
  {
    id: 'support-service-quality',
    title: 'پشتیبانی و کیفیت خدمت',
    technicalName: 'Support & Service Quality',
    description: 'Ticket، SLA و کیفیت رسیدگی در scope مجاز.',
    kpiIds: [
      'open-tickets',
      'sla-breach-rate',
      'first-response-time',
      'low-satisfaction',
    ],
    visualizations: [
      visual(
        'support-breakdown',
        'ترکیب حجم و SLA',
        'Ticketهای باز و نقض SLA به تفکیک دسته، اولویت و واحد پاسخ‌گو.',
        'stacked-bar',
        [supportTickets],
        'reports.dashboard.support.read',
        '/reports?report=customer_service_sla',
        'DEC-OPEN-009',
      ),
      visual(
        'support-time-trend',
        'روند زمان پاسخ و حل',
        'تغییر زمان پاسخ نخست و زمان حل در دوره‌های قابل مقایسه.',
        'line',
        [supportTickets],
        'reports.dashboard.support.read',
        '/reports?report=customer_service_sla',
        'DEC-OPEN-009',
      ),
      visual(
        'support-recovery-queue',
        'اقدام‌های اصلاحی باز',
        'Ticketهای خارج SLA و پاسخ‌های رضایت پایین که هنوز اقدام اصلاحی باز دارند.',
        'queue',
        [supportTickets, customerSatisfaction],
        'reports.dashboard.support.read',
        '/customer-affairs',
        'DEC-OPEN-009',
      ),
    ],
  },
  {
    id: 'partners-b2b',
    title: 'آژانس‌ها و مشتریان سازمانی',
    technicalName: 'Partners & B2B',
    description: 'عملکرد آژانس‌ها، اعتبار سازمانی و فرصت‌های B2B.',
    kpiIds: [
      'agency-sales',
      'agency-profit',
      'credit-at-risk',
      'expiring-guarantees',
    ],
    visualizations: [
      visual(
        'partner-performance',
        'فروش و سود شرکا',
        'مقایسه فروش، خرید و سود ناخالص آژانس‌ها در grain قلم سفارش و ارز.',
        'bar',
        [travelFacts],
        'reports.dashboard.b2b.read',
        '/reports?report=agency_performance',
        'DEC-OPEN-008',
      ),
      visual(
        'partner-credit-risk',
        'ریسک قرارداد و اعتبار',
        'سقف اعتبار، تضمین و روز تا انقضا برای قراردادهای فعال آژانس.',
        'stacked-bar',
        [agencyRisk],
        'reports.dashboard.b2b.read',
        '/reports?report=agency_contract_risk',
        'DEC-OPEN-008',
      ),
      visual(
        'partner-action-queue',
        'قراردادهای نیازمند اقدام',
        'تضمین نزدیک انقضا، بازبینی اعتبار و قرارداد رو به پایان به تفکیک مدیر حساب.',
        'queue',
        [agencyRisk],
        'reports.dashboard.b2b.read',
        '/organizations',
        'DEC-OPEN-008',
      ),
    ],
  },
  {
    id: 'marketing-growth',
    title: 'بازاریابی و رشد',
    technicalName: 'Marketing & Growth',
    description: 'ارسال، تعامل، conversion و ROAS فقط با attribution معتبر.',
    kpiIds: [
      'attributed-sales',
      'campaign-conversion',
      'campaign-roas',
      'consent-coverage',
    ],
    visualizations: [
      visual(
        'campaign-performance',
        'قیف تعامل کمپین',
        'ارسال، تحویل، بازشدن، کلیک و conversion فقط برای audience واجد consent.',
        'funnel',
        [campaign, customerConsent],
        'reports.dashboard.marketing.read',
        '/reports?report=marketing_performance',
        'DEC-OPEN-012',
      ),
      visual(
        'campaign-value',
        'فروش منتسب و ROAS',
        'مقایسه هزینه و فروش منتسب به تفکیک کمپین و مدل attribution.',
        'bar',
        [campaign],
        'reports.dashboard.marketing.read',
        '/reports?report=marketing_performance',
        'DEC-OPEN-012',
      ),
      visual(
        'consent-coverage-chart',
        'پوشش رضایت به تفکیک کانال',
        'مشتریان مجاز و لغو رضایت به تفکیک هدف ارتباط و کانال.',
        'stacked-bar',
        [customerConsent],
        'reports.dashboard.marketing.read',
        '/reports?report=customer_consent_coverage',
      ),
    ],
  },
  {
    id: 'workforce-hr',
    title: 'سرمایه انسانی',
    technicalName: 'Workforce & HR',
    description:
      'ظرفیت تیم، پوشش نقش‌ها و شاخص‌های منابع انسانی در scope مجاز.',
    kpiIds: [
      'employee-workdays',
      'employee-leave',
      'employee-overtime',
      'employee-performance',
      'expiring-hr-records',
      'incomplete-hr-records',
    ],
    visualizations: [
      visual(
        'workforce-capacity',
        'ظرفیت کارکرد واحدها',
        'مقایسه روزهای کارکرد، مرخصی و اضافه‌کاری به تفکیک واحد و سمت.',
        'stacked-bar',
        [employeePerformance],
        'reports.dashboard.hr.read',
        '/reports?report=hr_performance',
      ),
      visual(
        'workforce-performance',
        'روند عملکرد و فشار کاری',
        'روند امتیاز ارزیابی در کنار اضافه‌کاری، بدون نمایش اطلاعات حقوقی.',
        'line',
        [employeePerformance],
        'reports.dashboard.hr.read',
        '/reports?report=hr_performance',
      ),
      visual(
        'workforce-compliance-queue',
        'سوابق پرسنلی نیازمند اقدام',
        'رکوردهای ناقص، منقضی یا نزدیک انقضا به تفکیک نوع سابقه و واحد.',
        'queue',
        [hrRecordExpiry],
        'reports.dashboard.hr.read',
        '/reports?report=hr_record_expiry',
      ),
    ],
  },
  {
    id: 'tasks-automation',
    title: 'وظایف و اتوماسیون',
    technicalName: 'Tasks & Automation',
    description: 'وظایف سررسیدشده، وضعیت اجرا و استثناهای نیازمند رسیدگی.',
    kpiIds: ['overdue-tasks'],
    visualizations: [
      visual(
        'task-automation-queue',
        'صف وظایف و اجراها',
        'وظایف عقب‌افتاده و اجرای اتوماسیون فقط از Projection تأییدشده.',
        'queue',
        ['approved_task_projection', 'approved_automation_run_projection'],
        'reports.dashboard.tasks.read',
        '/tasks',
      ),
    ],
  },
  {
    id: 'documents-reports-data-quality',
    title: 'اسناد، گزارش‌ها و کیفیت داده',
    technicalName: 'Documents, Reports & Data Quality',
    description: 'وضعیت اسناد، خروجی گزارش‌ها و کنترل کیفیت داده‌های تصمیمی.',
    kpiIds: [],
    visualizations: [
      visual(
        'document-quality-overview',
        'سلامت اسناد',
        'کامل‌بودن، اعتبار و وضعیت پردازش اسناد در Projection عمومی.',
        'table',
        ['approved_document_quality_projection'],
        'reports.dashboard.documents.read',
        '/documents',
      ),
      visual(
        'report-data-quality-overview',
        'کیفیت گزارش و داده',
        'freshness، پوشش و خطاهای اعتبارسنجی خروجی‌های گزارش.',
        'table',
        ['approved_reporting_quality_projection'],
        'reports.dashboard.quality.read',
        '/reports',
      ),
    ],
  },
] as const;

export const dashboardNavigation: readonly DashboardNavigationItem[] = [
  { pageId: 'executive-overview' },
  {
    pageId: 'commercial-performance',
    children: [
      { pageId: 'revenue-collections' },
      { pageId: 'travel-operations' },
      { pageId: 'inventory-products' },
      { pageId: 'procurement-suppliers' },
    ],
  },
  { pageId: 'finance-treasury' },
  {
    pageId: 'customer-growth',
    children: [
      { pageId: 'customer-crm' },
      { pageId: 'support-service-quality' },
      { pageId: 'partners-b2b' },
      { pageId: 'marketing-growth' },
    ],
  },
  { pageId: 'workforce-hr' },
] as const;

export const dashboardOpenDecisions = [
  ['DEC-OPEN-001', 'مرز Sub-ledger و حسابداری قانونی'],
  ['DEC-OPEN-004', 'ارز، FX، precision، rounding، tax و revenue recognition'],
  ['DEC-OPEN-008', 'سیاست اعتبار B2B'],
  ['DEC-OPEN-009', 'تقویم SLA و escalation'],
  ['DEC-OPEN-012', 'attribution model و منبع هزینه Campaign'],
] as const;
