CREATE TABLE "b2b_organization_signatories" (
  "id" UUID NOT NULL,
  "organizationId" UUID NOT NULL,
  "contactId" UUID NOT NULL,
  "branchId" UUID NOT NULL,
  "documentTypes" TEXT[] NOT NULL,
  "authorityLimit" DECIMAL(24,4),
  "currencyCode" CHAR(3),
  "validFrom" DATE NOT NULL,
  "validTo" DATE,
  "documentVersionId" UUID,
  "isActive" BOOLEAN NOT NULL DEFAULT false,
  "notes" VARCHAR(1000) NOT NULL DEFAULT '',
  "version" INTEGER NOT NULL DEFAULT 1,
  "createdByUserId" UUID NOT NULL,
  "updatedByUserId" UUID NOT NULL,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT "b2b_organization_signatories_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "b2b_signatory_dates" CHECK ("validTo" IS NULL OR "validTo" >= "validFrom"),
  CONSTRAINT "b2b_signatory_limit" CHECK (("authorityLimit" IS NULL AND "currencyCode" IS NULL) OR ("authorityLimit" >= 0 AND "authorityLimit" IS NOT NULL AND "currencyCode" IS NOT NULL)),
  CONSTRAINT "b2b_signatory_proof" CHECK (NOT "isActive" OR "documentVersionId" IS NOT NULL),
  CONSTRAINT "b2b_signatory_types" CHECK (cardinality("documentTypes") BETWEEN 1 AND 4 AND array_position("documentTypes", NULL) IS NULL AND "documentTypes" <@ ARRAY['FRAMEWORK_AGREEMENT','SALES_CONTRACT','FINANCIAL_DOCUMENT','OTHER']::text[]),
  CONSTRAINT "b2b_organization_signatories_contactId_organizationId_fkey" FOREIGN KEY ("contactId", "organizationId") REFERENCES "master_organization_contacts"("id","organizationId") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "b2b_organization_signatories_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "b2b_organization_signatories_currencyCode_fkey" FOREIGN KEY ("currencyCode") REFERENCES "master_currencies"("code") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "b2b_organization_signatories_documentVersionId_fkey" FOREIGN KEY ("documentVersionId") REFERENCES "document_versions"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX "b2b_organization_signatories_organizationId_branchId_isActive_idx" ON "b2b_organization_signatories"("organizationId","branchId","isActive");
