export const PERMISSION_SEED_DATA = [
  ['iam.users.read', 'iam', 'مشاهده کاربران'],
  ['iam.users.manage', 'iam', 'مدیریت کاربران'],
  ['iam.roles.read', 'iam', 'مشاهده نقش‌ها'],
  ['iam.roles.manage', 'iam', 'مدیریت نقش‌ها و مجوزها'],
  ['iam.sessions.manage', 'iam', 'مدیریت نشست‌ها'],
  ['iam.audit.read', 'iam', 'مشاهده رویدادهای امنیتی'],
  ['master_data.read', 'master_data', 'مشاهده اطلاعات پایه'],
  ['master_data.create', 'master_data', 'ایجاد اطلاعات پایه'],
  ['master_data.update', 'master_data', 'ویرایش اطلاعات پایه'],
  ['master_data.status.manage', 'master_data', 'مدیریت وضعیت اطلاعات پایه'],
  ['master_data.export', 'master_data', 'خروجی اطلاعات پایه'],
  ['master_data.import', 'master_data', 'ورود گروهی اطلاعات پایه'],
  ['master_data.audit.read', 'master_data', 'مشاهده تاریخچه اطلاعات پایه'],
  ['master_data.currency_rate.create', 'master_data', 'ثبت نرخ مرجع ارز'],
  [
    'master_data.currency_rate.approve',
    'master_data',
    'تأیید یا رد نرخ مرجع ارز',
  ],
  [
    'master_data.sensitive_contact.read',
    'master_data',
    'مشاهده تماس حساس به‌شکل پوشیده',
  ],
  [
    'master_data.sensitive_contact.unmask',
    'master_data',
    'آشکارسازی کنترل‌شده تماس حساس',
  ],
  ['master_data.delete', 'master_data', 'حذف مدیریتی اطلاعات پایه'],
  ['customers.read', 'customers', 'مشاهده مشتریان'],
  ['customers.create', 'customers', 'ایجاد مشتریان'],
  ['customers.update', 'customers', 'ویرایش مشتریان'],
  ['customers.merge', 'customers', 'بررسی ادغام مشتریان'],
  ['customers.consent.manage', 'customers', 'مدیریت رضایت مشتریان'],
  ['customers.sensitive.read', 'customers', 'مشاهده اطلاعات حساس مشتریان'],
  ['legal-entity.read', 'legal-entity', 'مشاهده شرکت‌های صادرکننده'],
  ['legal-entity.switch', 'legal-entity', 'تغییر شرکت فعال'],
  ['legal-entity.aggregate.read', 'legal-entity', 'مشاهده حالت تجمیعی شرکت‌ها'],
  ['legal-entity.manage', 'legal-entity', 'مدیریت شرکت‌های صادرکننده'],
  ['legal-entity.branding.manage', 'legal-entity', 'مدیریت برندینگ شرکت‌ها'],
  ['legal-entity.audit.read', 'legal-entity', 'مشاهده Audit شرکت‌ها'],
  ['legal-entity.document.issue', 'legal-entity', 'صدور سند با هویت شرکت'],
  [
    'legal-entity.document.reissue',
    'legal-entity',
    'صدور مجدد سند با هویت شرکت',
  ],
  ['documents.list', 'documents', 'مشاهده فهرست اسناد'],
  ['documents.metadata.read', 'documents', 'مشاهده اطلاعات سند'],
  ['documents.file.read', 'documents', 'مشاهده محتوای فایل'],
  ['documents.download', 'documents', 'دانلود فایل'],
  ['documents.upload', 'documents', 'بارگذاری سند'],
  ['documents.metadata.update', 'documents', 'ویرایش اطلاعات سند'],
  ['documents.version.create', 'documents', 'ایجاد نسخه جدید'],
  ['documents.share.create', 'documents', 'ایجاد اشتراک امن'],
  ['documents.share.revoke', 'documents', 'لغو اشتراک امن'],
  ['documents.owner.change', 'documents', 'تغییر مالک سند'],
  ['documents.category.manage', 'documents', 'مدیریت دسته‌بندی سند'],
  ['documents.policy.manage', 'documents', 'مدیریت سیاست سند'],
  ['documents.audit.read', 'documents', 'مشاهده سابقه دسترسی سند'],
  ['documents.quarantine.manage', 'documents', 'مدیریت قرنطینه سند'],
  ['documents.delete', 'documents', 'حذف منطقی سند'],
  ['documents.restore', 'documents', 'بازیابی سند'],
  ['documents.export', 'documents', 'اجرای خروجی اسناد'],
  ['documents.sensitive.read', 'documents', 'مشاهده اطلاعات سند حساس'],
  ['documents.sensitive.download', 'documents', 'دانلود سند حساس'],
  ['documents.customer_identity.read', 'documents', 'دسترسی اسناد هویتی'],
  ['documents.sales.read', 'documents', 'دسترسی اسناد فروش'],
  ['documents.travel.read', 'documents', 'دسترسی اسناد سفر'],
  ['documents.procurement.read', 'documents', 'دسترسی اسناد خرید'],
  ['documents.finance.read', 'documents', 'دسترسی اسناد مالی'],
  ['documents.hr.read', 'documents', 'دسترسی اسناد منابع انسانی'],
  ['documents.organization.read', 'documents', 'دسترسی اسناد سازمانی'],
  ['documents.reporting.read', 'documents', 'دسترسی گزارش‌ها و خروجی‌ها'],
  ['documents.brand.read', 'documents', 'دسترسی دارایی‌های برند'],
  ['sales.contracts.read.own', 'sales', 'مشاهده قراردادهای خود'],
  ['sales.contracts.read.branch', 'sales', 'مشاهده قراردادهای شعبه'],
  ['sales.contracts.read.all', 'sales', 'مشاهده قراردادهای همه شعب'],
  ['sales.contracts.create', 'sales', 'ایجاد قرارداد فروش'],
  ['sales.contracts.update.own', 'sales', 'ویرایش قراردادهای خود'],
  ['sales.contracts.update.branch', 'sales', 'ویرایش قراردادهای شعبه'],
  ['sales.contracts.confirm', 'sales', 'تأیید قرارداد فروش'],
  ['sales.contracts.cancel', 'sales', 'لغو قرارداد فروش'],
  ['sales.payments.create', 'sales', 'ثبت برنامه و ردیف پرداخت'],
  ['sales.payments.read', 'sales', 'مشاهده پرداخت‌های قرارداد'],
  ['sales.reservation_request.create', 'sales', 'ارسال درخواست رزرواسیون'],
  ['sales.audit.read', 'sales', 'مشاهده Audit فروش'],
  ['sales.export', 'sales', 'خروجی قراردادهای فروش'],
] as const;
