export const PERMISSION_SEED_DATA = [
  ['iam.users.read', 'iam', 'مشاهده کاربران'],
  ['iam.users.manage', 'iam', 'مدیریت کاربران'],
  ['iam.roles.read', 'iam', 'مشاهده نقش‌ها'],
  ['iam.roles.manage', 'iam', 'مدیریت نقش‌ها و مجوزها'],
  ['iam.sessions.manage', 'iam', 'مدیریت نشست‌ها'],
  ['iam.audit.read', 'iam', 'مشاهده رویدادهای امنیتی'],
  ['master_data.read', 'master_data', 'مشاهده اطلاعات پایه'],
  ['master_data.create', 'master_data', 'ایجاد اطلاعات پایه'],
  ['master_data.update', 'master_data', 'ویرایش اطلاعات پایه'],
  ['master_data.status.manage', 'master_data', 'مدیریت وضعیت اطلاعات پایه'],
  ['master_data.export', 'master_data', 'خروجی اطلاعات پایه'],
  ['customers.read', 'customers', 'مشاهده مشتریان'],
  ['customers.create', 'customers', 'ایجاد مشتریان'],
  ['customers.update', 'customers', 'ویرایش مشتریان'],
  ['customers.merge', 'customers', 'بررسی ادغام مشتریان'],
  ['customers.consent.manage', 'customers', 'مدیریت رضایت مشتریان'],
  ['customers.sensitive.read', 'customers', 'مشاهده اطلاعات حساس مشتریان'],
] as const;
