export const PROCUREMENT_PERMISSION_SEED_DATA = [
  [
    'procurement.quote.single_source',
    'procurement',
    'خرید تک‌منبعی با سیاست مصوب',
  ],
  ['procurement.emergency', 'procurement', 'خرید اضطراری با سیاست مصوب'],
  ['procurement.read.own', 'procurement', 'مشاهده خریدهای خود'],
  ['procurement.read.unit', 'procurement', 'مشاهده خریدهای واحد'],
  ['procurement.read.all', 'procurement', 'مشاهده خریدها در شعب مجاز'],
  ['procurement.request.create', 'procurement', 'ثبت درخواست خرید'],
  ['procurement.request.update', 'procurement', 'ویرایش نسخه درخواست خرید'],
  ['procurement.request.submit', 'procurement', 'ارسال درخواست خرید'],
  ['procurement.request.cancel', 'procurement', 'لغو درخواست خرید'],
  ['procurement.assign', 'procurement', 'تخصیص مسئول خرید'],
  ['procurement.approve', 'procurement', 'تأیید تجاری خرید'],
  ['procurement.quote.manage', 'procurement', 'ثبت استعلام خرید'],
  ['procurement.quote.select', 'procurement', 'انتخاب پیشنهاد خرید'],
  ['procurement.order.manage', 'procurement', 'تنظیم سفارش خرید'],
  ['procurement.order.issue', 'procurement', 'صدور سفارش خرید'],
  ['procurement.order.amend', 'procurement', 'اصلاح نسخه سفارش خرید'],
  ['procurement.order.cancel', 'procurement', 'لغو یا بستن مانده سفارش'],
  ['procurement.receipt.manage', 'procurement', 'ثبت دریافت کالا'],
  ['procurement.acceptance.manage', 'procurement', 'پذیرش خدمت'],
  ['procurement.discrepancy.manage', 'procurement', 'رسیدگی به مغایرت خرید'],
  ['procurement.return.manage', 'procurement', 'ثبت مرجوعی خرید'],
  ['procurement.invoice.manage', 'procurement', 'ثبت و تطبیق فاکتور خرید'],
  [
    'procurement.invoice.submit_finance',
    'procurement',
    'ارجاع فاکتور خرید به مالی',
  ],
  ['procurement.audit.read', 'procurement', 'مشاهده سابقه خرید'],
  ['procurement.export', 'procurement', 'خروجی خرید'],
  ['procurement.settings.manage', 'procurement', 'تنظیمات خرید'],
] as const;
